/**
 * Portuguese Brazil (pt-BR) rebuilders for math question stems.
 * English is the authority; params/numbers/operators unchanged.
 * Generated by scripts/i18n/bootstrap-pt-BR-stem-rebuilders.mjs — review instructional copy.
 */
import { BLANK } from "../math-constants.js";
import { containsHebrew, mapQuestionTextFields } from "../learning-question-content-locale.js";

const WEEKDAYS_PT = [
  "domingo",
  "segunda-feira",
  "terça-feira",
  "quarta-feira",
  "quinta-feira",
  "sexta-feira",
  "sábado"];

/** Residual HE→EN maps cleared — generators emit English. Keep empty for API stability. */
const OBJECTS_PT = Object.freeze({
  items: "itens",
  apples: "maçãs",
  balls: "bolas",
  stickers: "adesivos",
  books: "livros",
  pencils: "lápis",
  chairs: "cadeiras",
  cards: "cartas",
  boxes: "caixas",
  coins: "moedas",
});
const YES_NO = Object.freeze({ Yes: "Sim", No: "Não", yes: "sim", no: "não" });
const PRIME_COMPOSITE = Object.freeze({
  prime: "primo",
  composite: "composto",
  Prime: "Primo",
  Composite: "Composto",
});
const PARITY = Object.freeze({ even: "par", odd: "ímpar", Even: "Par", Odd: "Ímpar" });
const MATH_PHRASES = [];

function applyMathPhrases(text) {
  let out = String(text ?? "");
  for (const [he, en] of MATH_PHRASES) {
    if (out.includes(he)) out = out.split(he).join(en);
  }
  return out;
}

function inferMathLevelKey(question) {
  const lv = String(question?.params?.difficulty || question?.levelKey || "easy");
  if (lv === "hard" || lv === "medium") return lv;
  return "easy";
}

function inferSelectedOp(question) {
  return String(question?.operation || question?.params?.kind || "").replace(/^wp_/, "word_problems");
}

/** Rebuild word-problem / story stems from params when kind is known. */
export function rebuildMathStemPtBr(question) {
  const p = question?.params || {};
  const kind = String(p.kind || "");
  const gradeKey = String(question?.gradeKey || p.gradeKey || "g3");

  if (kind === "mul_groups_g1") {
    const objects = OBJECTS_PT[p.objects] || String(p.objects || "items");
    return `Existem ${p.groups} grupos. Cada grupo tem ${p.perGroup} ${objects}. Quantos ${objects} existem ao todo?`;
  }
  if (kind === "mul_skip_count_g1") {
    const seq = Array.isArray(p.seq) ? p.seq : [];
    const head = seq.slice(0, -1).join(", ");
    return `Conte de ${p.perGroup} em ${p.perGroup}: ${head}, ${BLANK}`;
  }
  if (kind === "ns_number_line" || kind === "ns_number_line_g1") {
    const nums = Array.isArray(p.numbers) ? p.numbers : [];
    const line = nums.map((n) => (n === BLANK || n === "__" ? BLANK : n)).join(" - ");
    return `Preencha o número que falta na reta numérica: ${line}`;
  }
  if (kind === "ns_even_odd" || kind === "ns_parity") {
    return `${p.n ?? p.num} é um número par?`;
  }
  if (kind === "frac_half" || kind === "frac_half_reverse") {
    if (kind === "frac_half_reverse" && p.whole != null) {
      return `Metade de ${BLANK} é ${p.whole / 2}. Qual é o número inteiro?`;
    }
    return `Quanto é metade de ${p.whole ?? p.n}?`;
  }
  if (kind === "frac_quarter" || kind === "frac_quarter_reverse") {
    if (kind === "frac_quarter_reverse" && p.whole != null) {
      return `Um quarto de ${BLANK} é ${p.whole / 4}. Qual é o número inteiro?`;
    }
    return `Quanto é um quarto de ${p.whole ?? p.n}?`;
  }
  if (
    kind === "frac_compare_like_den_g4" |
    kind === "frac_compare_like_den_g3" |
    kind === "frac_compare_same_den"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      return `Qual fração é maior — ${p.n1}/${p.den} ou ${p.n2}/${p.den}? Escreva a fração maior: ${BLANK}`;
    }
  }
  if (
    kind === "frac_same_den_add_g4" |
    kind === "frac_same_den_add" |
    kind === "frac_same_den_sub_g4" |
    kind === "frac_same_den_sub"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      const op = p.op === "add" || kind.includes("add") ? "+" : "−";
      return `${p.n1}/${p.den} ${op} ${p.n2}/${p.den} = ${BLANK}`;
    }
  }
  if (kind === "frac_simplify_intro_g4" || kind === "frac_simplify_intro_g3") {
    if (p.num != null && p.den != null) {
      return `Simplifique a fração ${p.num}/${p.den}: ${BLANK}`;
    }
  }
  if (kind === "frac_equivalent_expand" || kind === "frac_equivalent") {
    if (p.num != null && p.den != null && p.factor != null) {
      return `Encontre uma fração equivalente para ${p.num}/${p.den} (multiplique por ${p.factor}): ${BLANK}`;
    }
  }
  if (kind === "wp_simple_add" || kind === "wp_simple_add_g2") {
    if (kind === "wp_simple_add_g2") {
      return `Havia ${p.a} crianças na turma e mais ${p.b} participaram. Quantas crianças existem agora?`;
    }
    return `Leo tem ${p.a} bolas e ganha ${p.b} a mais. Quantas bolas Leo tem ao todo?`;
  }
  if (kind === "wp_simple_sub" || kind === "wp_simple_sub_g2") {
    if (kind === "wp_simple_sub_g2") {
      return `Existem ${p.total} maçãs em uma cesta. ${p.give} foram comidas. Quantas maçãs sobraram?`;
    }
    return `Leo tem ${p.total} adesivos. Ele dá ${p.give} para um amigo. Quantos adesivos Leo ainda tem?`;
  }
  if (kind === "wp_pocket_money" || kind === "wp_pocket_money_g2") {
    return `Emma tem ${p.money} reais. Ela compra um lanche por ${p.toy} reais. Quanto dinheiro resta?`;
  }
  if (kind === "wp_groups_g2") {
    return `Cada fileira possui ${p.per} cadeiras. Existem ${p.groups} fileiras como essa. Quantas cadeiras há ao todo?`;
  }
  if (kind === "wp_groups_g3") {
    return `Cada caixa contém ${p.per} lápis. Existem ${p.groups} caixas. Quantos lápis existem ao todo?`;
  }
  if (kind === "wp_groups_g4") {
    return `Cada estante contém ${p.per} livros. Existem ${p.groups} prateleiras. Quantos livros existem ao todo?`;
  }
  if (kind === "wp_groups_late_g6") {
    return `Cada contêiner possui ${p.per} peças. ${p.groups} contêineres foram entregues. Quantas peças ao todo?`;
  }
  if (kind === "wp_groups" || kind === "wp_groups_late") {
    return `Cada caixa de suprimentos contém ${p.per} pacotes. ${p.groups} caixas foram entregues. Quantos pacotes ao todo?`;
  }
  if (kind === "wp_comparison_more") {
    return `Noa tem ${p.big} cartas e Yuval tem ${p.small} cartas. Quantas cartas a mais Noa tem do que Yuval?`;
  }
  if (kind === "wp_part_whole_g4") {
    return `Um salão tem ${p.whole} assentos. ${p.partA} são levados para um show e os demais ficam vazios. Quantos assentos estão vazios?`;
  }
  if (kind === "wp_part_whole") {
    return `Uma turma tem ${p.whole} alunos. ${p.partA} estão no clube de futebol e os demais estão no clube de xadrez. Quantos alunos estão no clube de xadrez?`;
  }
  if (kind === "wp_change_stack_g4") {
    return `Um armazém tinha ${p.start} caixas. ${p.gain} novas caixas foram adicionadas e ${p.loss} foram enviadas para outra filial. Quantas caixas restam?`;
  }
  if (kind === "wp_change_stack") {
    return `Uma biblioteca tinha ${p.start} livros. ${p.gain} novos livros foram adicionados e ${p.loss} foram retirados. Quantos livros há na biblioteca agora?`;
  }
  if (kind === "wp_time_days") {
    const start = WEEKDAYS_PT[p.startDayIdx] || "segunda-feira";
    const end = WEEKDAYS_PT[p.endDayIdx] || "sexta-feira";
    return `Se hoje é ${start}, quantos dias faltam para ${end}?`;
  }
  if (kind === "wp_time_date") {
    return `Se hoje for ${p.today} do mês, em que data será daqui a ${p.daysLater} dias?`;
  }
  if (kind === "wp_coins") {
    return `Leo tem ${p.coins1} moedas de 1 real e ${p.coins2} moedas de 2 reais. Quanto dinheiro ele tem ao todo?`;
  }
  if (kind === "wp_coins_spent") {
    return `Leo tem R$ ${p.total} em moedas. Ele compra doces por R$ ${p.spent}. Quanto dinheiro resta?`;
  }
  if (kind === "wp_division_simple") {
    return `Existem ${p.total} maçãs divididas em grupos de ${p.perGroup} maçãs cada. Quantos grupos existem?`;
  }
  if (kind === "wp_leftover") {
    return `${p.total} alunos são divididos em grupos de ${p.groupSize}. Quantos alunos ficam sem um grupo completo?`;
  }
  if (kind === "wp_shop_discount") {
    return `Uma camisa custa R$ ${p.price} com um desconto de ${p.discPerc}%. Quanto você paga após o desconto?`;
  }
  if (kind === "wp_unit_cm_to_m") {
    return `Quantos metros equivalem a ${p.cm} centímetros? = ${BLANK}`;
  }
  if (kind === "wp_unit_g_to_kg") {
    return `Quantos quilogramas equivalem a ${p.g} gramas? = ${BLANK}`;
  }
  if (kind === "wp_distance_time") {
    return `Uma criança caminha a uma velocidade constante de ${p.speed} km/h durante ${p.hours} horas. Quantos quilômetros eles percorrerão?`;
  }
  if (kind === "wp_time_sum") {
    return `Um videoclipe dura ${p.l1} minutos e outro dura ${p.l2} minutos. Quantos minutos duram os dois clipes juntos?`;
  }
  if (kind === "wp_average" || kind === "wp_average_g6") {
    if (kind === "wp_average_g6") {
      return `Um projeto em grupo obteve pontuações ${p.s1}, ${p.s2} e ${p.s3} em três etapas. Qual é a pontuação média (arredondada para um número inteiro)?`;
    }
    return `Leo obteve pontuação ${p.s1}, ${p.s2} e ${p.s3} em três testes. Qual é a média dele (arredondada para um número inteiro)?`;
  }
  if (kind === "wp_multi_step" || kind === "wp_multi_step_g6") {
    return `Leo tem R$ ${p.money}. Ele compra ${p.a} canetas e ${p.b} lápis, e cada item custa R$ ${p.price}. Quanto dinheiro resta depois das compras?`;
  }
  if (kind === "operation_choice_word_problem_probe") {
    return `Existem ${p.groups} grupos com ${p.each} itens em cada grupo. Qual operação encontra o total?`;
  }

  if (kind.startsWith("wp_") || inferSelectedOp(question) === "word_problems") {
    return null;
  }

  return applyMathLevelPresentationPtBr(
    // Seed from authored stem or params.exerciseText so compare/round wrappers can attach.
    String(question?.question || question?.exerciseText || p.exerciseText || ""),
    {
      selectedOp: question?.operation || inferSelectedOp(question),
      params: p,
      mathLevelKey: inferMathLevelKey(question),
      gradeKey,
    }
  );
}

/** English mirror of applyMathLevelPresentation (math-question-generator.js). */
export function applyMathLevelPresentationPtBr(question, ctx) {
  const q0 = String(question || "");
  if (!q0.trim()) return q0;
  const { selectedOp, params, mathLevelKey, gradeKey } = ctx;
  const kind = String(params?.kind || "");
  if (kind.startsWith("wp_") || selectedOp === "word_problems") return q0;

  if (kind === "ns_complement100") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 100;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `Faça ${c}: o que você adiciona a ${b} para chegar a ${c}? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Dado ${b} + ${BLANK} = ${c}. Qual é o número que falta?`;
      }
      return `Problema de palavras: ${b} falta uma parte para chegar a ${c} — quanto adicionar? = ${BLANK}`;
    }
  }

  if (kind === "ns_complement10") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 10;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `Até ${c}: o que você adiciona a ${b} para terminar em ${c}? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Faltando na equação: ${b} + ${BLANK} = ${c}`;
      }
      return `Sem coluna: qual adição a ${c} começa com ${b}? = ${BLANK}`;
    }
  }

  if (kind === "scale_find") {
    const ml = params?.mapLength;
    const rl = params?.realLength;
    if (ml != null && rl != null) {
      if (mathLevelKey === "easy") {
        return `Em um mapa, um segmento tem ${ml} cm de comprimento e na vida real tem ${rl} cm. Complete a escala como 1:${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Comprimento do mapa ${ml} cm, comprimento real ${rl} cm. Qual é a escala? Escreva o número depois de 1: = ${BLANK}`;
      }
      return `Mapa ${ml} cm e real ${rl} cm — a escala é 1:__. Qual é o número que falta? = ${BLANK}`;
    }
  }

  if (kind === "scale_map_to_real") {
    const ml = params?.mapLength;
    const sc = params?.scale;
    if (ml != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `Na escala 1:${sc}, quantos cm reais equivalem a ${ml} cm no mapa? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Escala 1:${sc}. Uma medida de mapa de ${ml} cm — qual é o comprimento real em cm? = ${BLANK}`;
      }
      return `Escala 1:${sc}, medida do mapa ${ml} cm — encontre o comprimento real em cm = ${BLANK}`;
    }
  }

  if (kind === "scale_real_to_map") {
    const rl = params?.realLength;
    const sc = params?.scale;
    if (rl != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `Na escala 1:${sc}, comprimento real ${rl} cm — quantos cm no mapa? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Comprimento real ${rl} cm, escala 1:${sc}. Qual é o comprimento no mapa? = ${BLANK}`;
      }
      return `Converter real em mapa: ${rl} cm real em 1:${sc} — quantos cm na página? = ${BLANK}`;
    }
  }

  if (selectedOp === "compare" || kind === "cmp") {
    const raw = params?.exerciseText ? String(params.exerciseText) : "";
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 4;
    if (mathLevelKey === "easy") {
      const opts = [
        `Compare os dois números e preencha (<, =, >): ${raw}`,
        `Sinal de comparação entre os números: ${raw}`,
        `Escolha < , = ou > — compare: ${raw}`,
        `Compare os valores e preencha o sinal: ${raw}`];
      return opts[pv].trim();
    }
    if (mathLevelKey === "medium") {
      const opts = [
        `Preencha o sinal de comparação correto: ${raw}`,
        `Qual signo compara o par? ${raw}`,
        `Combine o sinal de comparação correto: ${raw}`,
        `Preencha o sinal entre as expressões numéricas: ${raw}`];
      return opts[pv].trim();
    }
    const opts = [
      `Preencha o sinal de comparação — verifique antes de escolher: ${raw}`,
      `Compare com atenção e escolha um sinal: ${raw}`,
      `Compare com cuidado e escolha um sinal: ${raw}`,
      `Verificação rápida: qual sinal se encaixa? ${raw}`];
    return opts[pv].trim();
  }

  if (selectedOp === "divisibility" || kind === "divisibility") {
    const num = params?.num;
    const div = params?.divisor;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (num != null && div != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Divisibilidade: ${num} divide igualmente por ${div}?`
          : `Verifique: ${num} é um múltiplo de ${div} (sem resto)?`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Regras de divisibilidade — ${num} divide por ${div}?`
          : `Divisão inteira: ${num} ÷ ${div} — o resultado é um número inteiro?`;
      }
      return pv === 0
        ? `Verificação de divisibilidade: ${num} divide por ${div}?`
        : `Divisores: ${div} divide ${num} exatamente?`;
    }
  }

  if (selectedOp === "prime_composite" || kind === "prime_composite") {
    const num = params?.num;
    const subKind = String(params?.subKind || "pc_classify");
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (subKind === "pc_factor_count" && num != null) {
      if (mathLevelKey === "easy") return `Números primos: quantos divisores ${num} tem?`;
      if (mathLevelKey === "medium") {
        return `Contar divisores: quantos divisores naturais ${num} possui (incluindo 1 e ele mesmo)?`;
      }
      return `Divisores: quantos divisores diferentes ${num} tem?`;
    }
    if (subKind === "pc_smallest_prime" && num != null) {
      if (mathLevelKey === "easy") return `Fator primo: qual é o menor fator primo de ${num}?`;
      if (mathLevelKey === "medium") return `Encontre o menor fator primo de ${num}.`;
      return `Fatores: qual é o menor fator primo de ${num}?`;
    }
    if (subKind === "pc_divisor_pick" && num != null && params?.divisorCandidate != null) {
      const d = params.divisorCandidate;
      if (mathLevelKey === "easy") return `Verificação do divisor: ${d} divide ${num} uniformemente?`;
      if (mathLevelKey === "medium") return `Divisores: ${num} divide por ${d}?`;
      return `Divisores: ${d} divide ${num} exatamente?`;
    }
    if (num != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Números primos: ${num} é primo ou composto?`
          : `Classificação básica: ${num} — primo ou composto?`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Classifique o número: ${num} — primo ou composto?`
          : `${num} tem exatamente dois divisores naturais diferentes?`;
      }
      return pv === 0
        ? `${num} é primo ou composto? Pense antes de escolher.`
        : `Prova rápida: ${num} pode ser dividido em dois fatores maiores que 1?`;
    }
  }

  if (selectedOp === "powers" && (kind === "power_base" || kind === "power_calc")) {
    if (kind === "power_calc") {
      if (mathLevelKey === "easy") return `Poderes: ${q0}`;
      if (mathLevelKey === "medium") return `Avalie o poder — ${q0}`;
      return `Poderes: ${q0}`;
    }
    if (kind === "power_base") {
      if (mathLevelKey === "easy") return `Encontre a base na potência: ${q0}`;
      if (mathLevelKey === "medium") return `Quebra-cabeça de poder — ${q0}`;
      return `Base faltando no poder: ${q0}`;
    }
  }

  if (selectedOp === "estimation") {
    if (kind === "est_add") {
      if (mathLevelKey === "easy") return q0.replace(/^Estimate\b/i, "Estimativa de arredondamento: estimativa");
      return q0;
    }
    if (kind === "est_mul" || kind === "est_quantity") return q0;
  }

  if (
    kind === "frac_half" |
    kind === "frac_half_reverse" |
    kind === "frac_quarter" |
    kind === "frac_quarter_reverse"
  ) {
    if (mathLevelKey === "easy") return `Frações: ${q0}`;
    if (mathLevelKey === "medium") return `Fração como parte de um todo: ${q0}`;
    return `Frações: ${q0}`;
  }

  if (kind === "fm_factor") {
    if (mathLevelKey === "easy") return `Fatores: ${q0}`;
    if (mathLevelKey === "medium") return `Identifique um divisor: ${q0}`;
    return `Divisores e fatores: ${q0}`;
  }
  if (kind === "fm_multiple") {
    if (mathLevelKey === "easy") return `Múltiplos: ${q0}`;
    if (mathLevelKey === "medium") return `Verifique múltiplos: ${q0}`;
    return `Múltiplos: ${q0}`;
  }

  if (selectedOp === "percentages" || selectedOp === "ratio" || selectedOp === "scale") return q0;

  if (kind === "fm_gcd" && params?.a != null && params?.b != null) {
    const { a, b } = params;
    if (mathLevelKey === "easy") {
      return `GCF: qual é o maior divisor comum de ${a} e ${b}? = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return `Maior fator comum (GCD) de ${a} e ${b} — o que é? = ${BLANK}`;
    }
    return `MDC: pense primeiro - MDC(${a}, ${b}) = ${BLANK}`;
  }

  if (kind === "round" && params?.n != null && params?.toWhat != null) {
    const { n, toWhat } = params;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (toWhat === 10) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Arredondar para dezenas: para onde ${n} arredonda? = ${BLANK}`
          : `Dez mais próximos: ${n} → ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Arredonde ${n} para a dezena mais próxima - resultado? = ${BLANK}`
          : `Regra de arredondamento por dezenas: ${n} = ${BLANK}`;
      }
      return pv === 0
        ? `Arredondar para dezenas: ${n} → ? = ${BLANK}`
        : `Número correto após arredondar ${n} para dezenas = ${BLANK}`;
    }
    if (mathLevelKey === "easy") {
      return pv === 0
        ? `Arredondar para centenas: para que ${n} arredonda? = ${BLANK}`
        : `Centena mais próxima: ${n} = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return pv === 0
        ? `Arredonde ${n} para a centena mais próxima - resultado? = ${BLANK}`
        : `Arredondar para centenas: ${n} → ? = ${BLANK}`;
    }
    return pv === 0
      ? `Arredondar para centenas: ${n} → ? = ${BLANK}`
      : `Número após arredondamento ${n} para centenas = ${BLANK}`;
  }

  if (kind === "dec_add" || kind === "dec_sub") {
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    const a = params?.a;
    const b = params?.b;
    const pl = params?.places ?? 1;
    if (a != null && b != null) {
      const af = Number(a).toFixed(pl);
      const bf = Number(b).toFixed(pl);
      if (kind === "dec_add") {
        if (mathLevelKey === "easy") {
          return pv === 0
            ? `Adicione decimais: ${af} + ${bf} = ${BLANK}`
            : `Soma direta: ${af} + ${bf} = ${BLANK}`;
        }
        return `Adicione decimais: ${af} + ${bf} = ${BLANK}`;
      }
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Subtraia decimais: ${af} − ${bf} = ${BLANK}`
          : `Diferença direta: ${af} − ${bf} = ${BLANK}`;
      }
      return `Subtraia decimais: ${af} − ${bf} = ${BLANK}`;
    }
  }

  if (selectedOp === "sequences") {
    if (mathLevelKey === "easy") {
      return q0.replace(/^Continue the sequence\b/i, "Continue o padrão numérico");
    }
    return q0;
  }

  const looksNumericExercise =
    /=\s*__|=\s*\?\?|___|\?\?=/.test(q0) |
    (/^\d/.test(q0.trim()) && /[+\-×÷]/.test(q0));

  if (looksNumericExercise) return q0;
  if (/^Exercise\b/i.test(q0)) return q0;

  if (containsHebrew(q0) && params?.exerciseText && !containsHebrew(String(params.exerciseText))) {
    return String(params.exerciseText);
  }

  return q0;
}

function isShortAnswerField(field) {
  return field === "answers" || field === "options" || field === "aceitoRespostas";
}

function localizeMathField(_field, value, question) {
  const text = String(value ?? "");
  if (!containsHebrew(text)) return text;

  if (YES_NO[text.trim()]) return YES_NO[text.trim()];
  if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
  if (PARITY[text.trim()]) return PARITY[text.trim()];

  const rebuilt = rebuildMathStemPtBr(question);
  if (rebuilt && !containsHebrew(rebuilt) && (_field === "question" || _field === "exercícioTexto" || _field === "questionLabel")) {
    return rebuilt;
  }

  const presented = applyMathLevelPresentationPtBr(text, {
    selectedOp: question?.operation || inferSelectedOp(question),
    params: question?.params || {},
    mathLevelKey: inferMathLevelKey(question),
    gradeKey: question?.gradeKey || "g3",
  });
  if (presented && !containsHebrew(presented)) return presented;

  const phrased = applyMathPhrases(text);
  if (!containsHebrew(phrased)) return phrased;

  const stripped = phrased
    .replace(/(\d+)\s+remainder\s+(\d+)/gu, "$ 1 restante $ 2")
    .replace(/(?!)/gu, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  return stripped || text;
}

function isNearlyEmptyStem(text) {
  const t = String(text ?? "")
    .replace(/[_\s.:=?\-−–—,/|]+/g, "")
    .trim();
  return t.length < 2;
}

const OP_SYMBOL_PT = Object.freeze({
  addition: "+",
  subtraction: "−",
  multiplication: "×",
  division: "÷",
});

/**
 * Build display stem from params/kind only (no Hebrew sentence translation).
 * @param {Record<string, unknown>} question
 */
function resolveMathDisplayStem(question) {
  const rebuilt = rebuildMathStemPtBr(question);
  if (rebuilt && String(rebuilt).trim() && !containsHebrew(rebuilt)) {
    return { stem: rebuilt, source: "params" };
  }
  const p = question?.params && typeof question.params === "object" ? question.params : {};
  const opRaw = String(question?.operation || p.kind || "").replace(/^wp_/, "");
  const a = p.a ?? question?.a;
  const b = p.b ?? question?.b;
  if (a != null && b != null && OP_SYMBOL_PT[opRaw]) {
    return { stem: `Quanto é ${a} ${OP_SYMBOL_PT[opRaw]} ${b}?`, source: "generic" };
  }
  for (const candidate of [p.exerciseText, question?.exerciseText, question?.question]) {
    if (typeof candidate === "string" && candidate.trim() && !containsHebrew(candidate)) {
      return { stem: String(candidate).trim(), source: "passthrough" };
    }
  }
  return { stem: null, source: "none" };
}

/**
 * Localize math question for Portuguese Brazil (pt-BR) display.
 * Display stems come from params/kind templates — not from translating Hebrew prose.
 * Option tokens use closed dictionaries (logical labels), not sentence MT.
 */
export function localizeMathQuestionPtBr(question) {
  if (!question) return question;

  const base = { ...question };
  // Drop authored Hebrew stems so params are the sole stem authority.
  if (typeof base.question === "string" && containsHebrew(base.question)) base.question = "";
  if (typeof base.exerciseText === "string" && containsHebrew(base.exerciseText)) base.exerciseText = "";
  if (typeof base.questionLabel === "string" && containsHebrew(base.questionLabel)) base.questionLabel = "";

  const { stem, source } = resolveMathDisplayStem({ ...question, ...base, params: question.params });
  const resolvedStem = stem || "Resolva.";

  const out = mapQuestionTextFields({ ...base }, (field, value, q) => {
    if (field === "question" || field === "exercícioTexto" || field === "questionLabel") {
      if (!value || containsHebrew(value) || isNearlyEmptyStem(value)) return resolvedStem;
      return value;
    }
    // Answers/options: closed token maps only (no full-sentence HE→EN).
    if (isShortAnswerField(field)) {
      const text = String(value ?? "");
      if (!containsHebrew(text)) return text;
      if (YES_NO[text.trim()]) return YES_NO[text.trim()];
      if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
      if (PARITY[text.trim()]) return PARITY[text.trim()];
      if (OBJECTS_PT[text.trim()]) return OBJECTS_PT[text.trim()];
      const digitsOnly = text.replace(/(?!)/gu, "").trim();
      return digitsOnly || text;
    }
    if (!containsHebrew(String(value ?? ""))) return value;
    return value;
  });

  out.question = resolvedStem;
  if (!out.exerciseText || containsHebrew(String(out.exerciseText)) || isNearlyEmptyStem(out.exerciseText)) {
    out.exerciseText = resolvedStem;
  }
  out.displayStemSource = source;

  if (typeof out.correctAnswer === "string") {
    const ca = out.correctAnswer.trim();
    if (YES_NO[ca]) out.correctAnswer = YES_NO[ca];
    else if (PRIME_COMPOSITE[ca]) out.correctAnswer = PRIME_COMPOSITE[ca];
    else if (PARITY[ca]) out.correctAnswer = PARITY[ca];
    else if (containsHebrew(ca)) {
      out.correctAnswer = ca.replace(/(?!)/gu, "").trim() || ca;
    }
  }
  if (Array.isArray(out.answers)) {
    out.answers = out.answers.map((a) =>
      typeof a === "string" ? localizeMathField("answers", a, out) : a
    );
  }
  return out;
}
