/**
 * Math taxonomy — implementation of the stage1-scientific-blueprint-source-of-truth document §5.1
 * Machine fields: explicit recurrence thresholds per the document.
 * @typedef {import("./taxonomy-types.js").TaxonomyRow} TaxonomyRow
 */

/** @type {TaxonomyRow[]} */
export const MATH_TAXONOMY_ROWS = [
  {
    id: "M-01",
    subjectId: "math",
    domainHe: "Number",
    topicHe: "Structure",
    subskillHe: "10+1 decomposition",
    patternHe: "Errors converting between representations",
    minWrong: 3,
    minDistinctPatternFamilies: 2,
    minDistinctDays: 0,
    observableMarkersHe: ["Same error across two representations", "Hesitation before answering"],
    counterEvidenceHe: "Succeeds with a representation shown without a long explanation",
    countsWhenHe: "Equivalent tasks; no hint that shows the full solution",
    doesNotCountWhenHe: "Full hint given; single task only",
    rootsHe: ["Representation gap"],
    competitorsHe: ["Reading comprehension"],
    doNotConcludeHe: ["Not an arithmetic issue"],
    probeHe: "Two representations of the same number",
    interventionHe: "Manipulatives, then a gradual move to symbols",
    escalationHe: "Fails on every representation",
  },
  {
    id: "M-02",
    subjectId: "math",
    domainHe: "Operations",
    topicHe: "Addition",
    subskillHe: "Carrying",
    patternHe: "Error in the tens column",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 2,
    observableMarkersHe: ["Same error type across different magnitudes"],
    counterEvidenceHe: "Correct when there is no carrying",
    countsWhenHe: "Written digits",
    doesNotCountWhenHe: "Only extreme-sized numbers without a carrying basis",
    rootsHe: ["Carrying algorithm"],
    competitorsHe: ["Carelessness"],
    doNotConcludeHe: ["Lack of number sense"],
    probeHe: "Addition with/without carrying",
    interventionHe: "Carrying with the intermediate step written out",
    escalationHe: "Depends on the intermediate step with no progress",
  },
  {
    id: "M-03",
    subjectId: "math",
    domainHe: "Operations",
    topicHe: "Multiplication",
    subskillHe: "Multiplication fact",
    patternHe: "Same pairs wrong repeatedly",
    minWrong: 4,
    minDistinctPatternFamilies: 2,
    minDistinctDays: 0,
    observableMarkersHe: ["Overlapping list of wrong pairs"],
    counterEvidenceHe: "Other pairs correct in the same session",
    countsWhenHe: "Regular practice; not only a speed test",
    doesNotCountWhenHe: "Speed test only",
    rootsHe: ["Fact gap"],
    competitorsHe: ["Time pressure"],
    doNotConcludeHe: ["Cannot multiply at all"],
    probeHe: "Double the time for the same set",
    interventionHe: "Targeted pair practice",
    escalationHe: "Fails on every pair even when slow",
  },
  {
    id: "M-04",
    subjectId: "math",
    domainHe: "Fractions",
    topicHe: "Representation",
    subskillHe: "Part-whole",
    patternHe: "Comparing by numerator only",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error even when the diagram is complete"],
    counterEvidenceHe: "Correct when denominators happen to match",
    countsWhenHe: "Diagram/fraction strip available",
    doesNotCountWhenHe: "Verbal only, without a representation not yet taught",
    rootsHe: ["Fraction concept gap"],
    competitorsHe: ["Carelessness"],
    doNotConcludeHe: ["Cannot do fractions at all"],
    probeHe: "With/without a diagram",
    interventionHe: "Concrete part-whole work",
    escalationHe: "No improvement in any representation",
  },
  {
    id: "M-05",
    subjectId: "math",
    domainHe: "Fractions",
    topicHe: "Addition",
    subskillHe: "Denominator expansion",
    patternHe: "Error at the same step",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error in repeated multiplication/expansion"],
    counterEvidenceHe: "Correct with matching denominators",
    countsWhenHe: "Small denominators within the taught range",
    doesNotCountWhenHe: "Large denominators before basic multiplication is solid",
    rootsHe: ["Expansion algorithm"],
    competitorsHe: ["Weak multiplication"],
    doNotConcludeHe: ["Cannot do fractions at all"],
    probeHe: "Expansion factors 2, 3, 4",
    interventionHe: "Written steps with a parallel worked example",
    escalationHe: "Fails at basic multiplication",
  },
  {
    id: "M-06",
    subjectId: "math",
    domainHe: "Decimals",
    topicHe: "Place value",
    subskillHe: "Rounding/comparison",
    patternHe: "Wrong rounding direction",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Repeated error on the same rule"],
    counterEvidenceHe: "Correct with a place-value chart",
    countsWhenHe: "Non-round numbers",
    doesNotCountWhenHe: "Only round numbers in the task",
    rootsHe: ["Place-value gap"],
    competitorsHe: ["Reading comprehension"],
    doNotConcludeHe: ["Cannot do decimals at all"],
    probeHe: "With/without a place-value chart",
    interventionHe: "Color-coding place values",
    escalationHe: "Fails even with the chart",
  },
  {
    id: "M-07",
    subjectId: "math",
    domainHe: "Word problems",
    topicHe: "Phrasing",
    subskillHe: "Units",
    patternHe: "Correct number, wrong unit",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Repeats an inappropriate unit"],
    counterEvidenceHe: "Correct when only a number is requested",
    countsWhenHe: "Unit explicit in the text",
    doesNotCountWhenHe: "Question has no unit in the original",
    rootsHe: ["Reading the question"],
    competitorsHe: ["Calculation"],
    doNotConcludeHe: ["No comprehension at all"],
    probeHe: "With/without a unit field",
    interventionHe: "Number plus a unit line",
    escalationHe: "Struggles even without a unit",
  },
  {
    id: "M-08",
    subjectId: "math",
    domainHe: "Word problems",
    topicHe: "Modeling",
    subskillHe: "Multi-step",
    patternHe: "Fails only when combining steps",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error at the same final step"],
    counterEvidenceHe: "Succeeds with printed steps",
    countsWhenHe: "Numbered steps",
    doesNotCountWhenHe: "Version without steps when not yet taught",
    rootsHe: ["Working-memory load"],
    competitorsHe: ["Calculation gap"],
    doNotConcludeHe: ["Cannot do word problems at all"],
    probeHe: "With a step template",
    interventionHe: "Steps plus a working-backward check",
    escalationHe: "Fails even on single-step problems",
  },
  {
    id: "M-09",
    subjectId: "math",
    domainHe: "Operations",
    topicHe: "Subtraction",
    subskillHe: "Making ten",
    patternHe: "Reversed direction / adds instead of subtracting",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Repeated direction error"],
    counterEvidenceHe: "Correct on a number line",
    countsWhenHe: "Number line/track available",
    doesNotCountWhenHe: "Long verbal problem without a representation when not yet taught",
    rootsHe: ["Subtraction concept"],
    competitorsHe: ["Reading comprehension"],
    doNotConcludeHe: ["General arithmetic problem"],
    probeHe: "Number line plus symbolic",
    interventionHe: "Number line plus a distance model",
    escalationHe: "No improvement in either representation",
  },
  {
    id: "M-10",
    subjectId: "math",
    domainHe: "Multiplication/Division",
    topicHe: "Ratio",
    subskillHe: "Inverse operations",
    patternHe: "Picks a multiplication fact that doesn't match the division",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error when no multiplication sentence is shown"],
    counterEvidenceHe: "Correct when the multiplication sentence is shown",
    countsWhenHe: "Small numbers",
    doesNotCountWhenHe: "Large numbers before multiplication is mastered",
    rootsHe: ["Inverse relationship"],
    competitorsHe: ["Carelessness"],
    doNotConcludeHe: ["Cannot divide at all"],
    probeHe: "With/without the multiplication sentence",
    interventionHe: "Linking multiplication and division",
    escalationHe: "Fails consistently",
  },
];
