/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const SCIENCE_TAXONOMY_ROWS = [
  {
    id: "S-01",
    subjectId: "science",
    domainHe: "Concept",
    topicHe: "Classification",
    subskillHe: "Property vs process",
    patternHe: "Category confusion",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on two similar concepts"],
    counterEvidenceHe: "Correct after an examples table",
    countsWhenHe: "Guided table",
    doesNotCountWhenHe: "Homophone distractors only",
    rootsHe: ["Concept confusion"],
    competitorsHe: ["Reading"],
    doNotConcludeHe: ["No science"],
    probeHe: "Separate property from process (focused practice)",
    interventionHe: "Property/process table",
    escalationHe: "No improvement",
  },
  {
    id: "S-02",
    subjectId: "science",
    domainHe: "Method",
    topicHe: "Experiment",
    subskillHe: "Isolated variable",
    patternHe: "Changing everything",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on single-change scenarios"],
    counterEvidenceHe: "Correct with a variables table",
    countsWhenHe: "Table available",
    doesNotCountWhenHe: "Long text without a table",
    rootsHe: ["Experiment understanding"],
    competitorsHe: ["Memory"],
    doNotConcludeHe: ["No thinking"],
    probeHe: "Same experiment with a table",
    interventionHe: "One variable",
    escalationHe: "Repeated failure",
  },
  {
    id: "S-03",
    subjectId: "science",
    domainHe: "Body",
    topicHe: "Systems",
    subskillHe: "Location/flow",
    patternHe: "Wrong order/location",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on a simple body map"],
    counterEvidenceHe: "Correct with numbering",
    countsWhenHe: "Numbered diagram",
    doesNotCountWhenHe: "Latin names not yet taught",
    rootsHe: ["Coarse spatial map"],
    competitorsHe: ["Language"],
    doNotConcludeHe: ["Medical issue"],
    probeHe: "Vertical vs horizontal",
    interventionHe: "Location cards",
    escalationHe: "Medical report",
  },
  {
    id: "S-04",
    subjectId: "science",
    domainHe: "Matter",
    topicHe: "States of matter",
    subskillHe: "Mass conservation",
    patternHe: "Disappears without conservation",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error when a states diagram is present"],
    counterEvidenceHe: "Correct after a diagram",
    countsWhenHe: "Diagram available",
    doesNotCountWhenHe: "Word without taught states",
    rootsHe: ["Mass conservation"],
    competitorsHe: ["Language"],
    doNotConcludeHe: ["No physics"],
    probeHe: "With/without diagram",
    interventionHe: "States diagram",
    escalationHe: "No improvement",
  },
  {
    id: "S-05",
    subjectId: "science",
    domainHe: "Energy",
    topicHe: "Units",
    subskillHe: "Unit conversion",
    patternHe: "Unit confusion",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on the same unit"],
    counterEvidenceHe: "Correct with a key",
    countsWhenHe: "Key available",
    doesNotCountWhenHe: "Before the unit is taught",
    rootsHe: ["Units"],
    competitorsHe: ["Computation"],
    doNotConcludeHe: ["No understanding"],
    probeHe: "Two units for the same amount",
    interventionHe: "Unit key",
    escalationHe: "Always fails",
  },
  {
    id: "S-06",
    subjectId: "science",
    domainHe: "Measurement",
    topicHe: "Graph",
    subskillHe: "Reading an axis",
    patternHe: "Wrong value from a graph",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on two graphs"],
    counterEvidenceHe: "Correct when the axis is highlighted",
    countsWhenHe: "Scaled axes",
    doesNotCountWhenHe: "Unscaled graph",
    rootsHe: ["Graph reading"],
    competitorsHe: ["Computation"],
    doNotConcludeHe: ["No science"],
    probeHe: "With/without point highlight",
    interventionHe: "Practice a point on an axis",
    escalationHe: "Vision report",
  },
  {
    id: "S-07",
    subjectId: "science",
    domainHe: "Ecology",
    topicHe: "Relationships",
    subskillHe: "Food web",
    patternHe: "Repeated wrong level",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error when a diagram is present"],
    counterEvidenceHe: "Correct on a closed list",
    countsWhenHe: "Diagram or list",
    doesNotCountWhenHe: "Text only without teaching",
    rootsHe: ["System structure"],
    competitorsHe: ["Name recall"],
    doNotConcludeHe: ["No systems"],
    probeHe: "Partial web",
    interventionHe: "Cards",
    escalationHe: "No improvement",
  },
  {
    id: "S-08",
    subjectId: "science",
    domainHe: "Science safety",
    topicHe: "Reasoning",
    subskillHe: "Source for a claim",
    patternHe: "Unsupported claim",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Repeats when an explicit source is present"],
    counterEvidenceHe: "Correct when a source is requested",
    countsWhenHe: "Sources marked",
    doesNotCountWhenHe: "Ad distractor",
    rootsHe: ["Critical thinking"],
    competitorsHe: ["Reading"],
    doNotConcludeHe: ["Personal values"],
    probeHe: "With/without source",
    interventionHe: "Ask how we know",
    escalationHe: "Social studies teacher",
  },
];
