/** @type {import("./taxonomy-types.js").TaxonomyRow[]} */
export const ENGLISH_TAXONOMY_ROWS = [
  {
    id: "E-01",
    subjectId: "english",
    domainHe: "Vocabulary",
    topicHe: "Context",
    subskillHe: "collocation",
    patternHe: "Incorrect literal translation",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Same root across different sentences"],
    counterEvidenceHe: "Correct after two examples",
    countsWhenHe: "Clear sentences",
    doesNotCountWhenHe: "False-friend distractor only",
    rootsHe: ["false friend"],
    competitorsHe: ["Grammar"],
    doNotConcludeHe: ["No English"],
    probeHe: "Parallel sentences",
    interventionHe: "Sentence cards",
    escalationHe: "Difficulty across every topic",
  },
  {
    id: "E-02",
    subjectId: "english",
    domainHe: "Grammar",
    topicHe: "Tenses",
    subskillHe: "Time marker",
    patternHe: "past/present",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error when yesterday/now is explicit"],
    counterEvidenceHe: "Correct with a markers chart",
    countsWhenHe: "Marker highlighted",
    doesNotCountWhenHe: "Mixed tense without prior teaching",
    rootsHe: ["Tense map"],
    competitorsHe: ["Vocabulary"],
    doNotConcludeHe: ["No grammar"],
    probeHe: "Identical sentences, different marker",
    interventionHe: "Markers chart",
    escalationHe: "No improvement",
  },
  {
    id: "E-03",
    subjectId: "english",
    domainHe: "Reading",
    topicHe: "Layout",
    subskillHe: "Line tracking",
    patternHe: "Error in two-column layout",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error only in two-column layout"],
    counterEvidenceHe: "Correct in one wide column",
    countsWhenHe: "Readable font",
    doesNotCountWhenHe: "Tiny font without a scaffold",
    rootsHe: ["Line tracking"],
    competitorsHe: ["Vocabulary"],
    doNotConcludeHe: ["No reading"],
    probeHe: "Large font vs small",
    interventionHe: "Line number / finger tracking",
    escalationHe: "Vision report",
  },
  {
    id: "E-04",
    subjectId: "english",
    domainHe: "Grammar",
    topicHe: "Agreement",
    subskillHe: "Pronoun–subject",
    patternHe: "he/she/it",
    minWrong: 4,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error", "Subject highlighted"],
    counterEvidenceHe: "Correct when very slow",
    countsWhenHe: "Explicit subject",
    doesNotCountWhenHe: "Fast typing only",
    rootsHe: ["Syntactic agreement"],
    competitorsHe: ["Speed"],
    doNotConcludeHe: ["No knowledge"],
    probeHe: "Chain with subject",
    interventionHe: "Subject–pronoun chart",
    escalationHe: "Always fails",
  },
  {
    id: "E-05",
    subjectId: "english",
    domainHe: "Vocabulary",
    topicHe: "Usage",
    subskillHe: "preposition",
    patternHe: "Same wrong preposition",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error with different verbs"],
    counterEvidenceHe: "Correct on a closed list",
    countsWhenHe: "Taught prepositions",
    doesNotCountWhenHe: "Verbs not yet taught",
    rootsHe: ["Specific vocabulary"],
    competitorsHe: ["General grammar"],
    doNotConcludeHe: ["No language"],
    probeHe: "Same verb, two prepositions",
    interventionHe: "Minimal pairs",
    escalationHe: "No improvement",
  },
  {
    id: "E-06",
    subjectId: "english",
    domainHe: "Reading",
    topicHe: "Comprehension",
    subskillHe: "inference",
    patternHe: "Fact instead of inference",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error only on inference"],
    counterEvidenceHe: "Correct on an explicit fact",
    countsWhenHe: "Question type marked",
    doesNotCountWhenHe: "Before inference is taught",
    rootsHe: ["Strategy"],
    competitorsHe: ["Vocabulary"],
    doNotConcludeHe: ["No thinking"],
    probeHe: "Fact vs inference",
    interventionHe: "Inference signal words",
    escalationHe: "Failure on facts too",
  },
  {
    id: "E-07",
    subjectId: "english",
    domainHe: "Writing",
    topicHe: "Spelling",
    subskillHe: "Silent patterns",
    patternHe: "Repeated errors",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Same pattern"],
    counterEvidenceHe: "Correct with slow dictation",
    countsWhenHe: "Taught words",
    doesNotCountWhenHe: "Before the rule",
    rootsHe: ["Phonology"],
    competitorsHe: ["Typing"],
    doNotConcludeHe: ["Disorder"],
    probeHe: "Controlled handwriting",
    interventionHe: "Mini spelling rule",
    escalationHe: "Professional report",
  },
  {
    id: "E-08",
    subjectId: "english",
    domainHe: "Listening",
    topicHe: "Phonemic",
    subskillHe: "minimal pairs",
    patternHe: "Confusing a sound pair",
    minWrong: 3,
    minDistinctPatternFamilies: 0,
    minDistinctDays: 0,
    observableMarkersHe: ["Error on the same pair"],
    counterEvidenceHe: "Correct with slow double listening",
    countsWhenHe: "Clear recording",
    doesNotCountWhenHe: "Known noise",
    rootsHe: ["Phonemics"],
    competitorsHe: ["Noise"],
    doNotConcludeHe: ["Hearing disorder"],
    probeHe: "Same pair in different words",
    interventionHe: "Pair practice",
    escalationHe: "Hearing report",
  },
];
