/**
 * French France (fr-FR) rebuilders for geometry question stems.
 * Anglais is the authority; params/numbers/operators unchanged.
 * Generated by scripts/i18n/bootstrap-fr-FR-stem-rebuilders.mjs — review instructional copy.
 */
import { containsHebrew, mapQuestionTextFields } from "../learning-question-content-locale.js";
import { resolveRegisteredContentPack } from "../../lib/content/resolve-registered-pack.js";

const geometryContent =
  resolveRegisteredContentPack("en", "learning", "geometry-content.json") || {};

export const GEOMETRY_FR_LABEL_OPTIONS = geometryContent.labelOptions;
export const GEOMETRY_SOLID_NAMES_FR = geometryContent.solidNames;

/** Anglais-keyed solid aliases from content pack (no HE keys in this module). */
const SOLID_ALIASES = geometryContent.solidAliases || {};

/** Phrase HE→EN table cleared — generators emit Anglais. */
const PHRASES = [];

/** Anglais label options only — residual HE stems are stripped, not phrase-translated. */
const SHAPE_WORDS = {
  ...(geometryContent.shapeWords && !Object.keys(geometryContent.shapeWords).some((k) => /(?!)/.test(k))
    ? geometryContent.shapeWords
    : {}),
  ...SOLID_ALIASES,
};

function mapGeometryLabel(text) {
  const t = String(text ?? "").trim();
  if (SOLID_ALIASES[t]) return SOLID_ALIASES[t];
  if (SHAPE_WORDS[t]) return SHAPE_WORDS[t];
  for (const opts of Object.values(GEOMETRY_FR_LABEL_OPTIONS || {})) {
    if (Array.isArray(opts) && opts.includes(t)) return t;
  }
  return null;
}

function isNearlyEmptyStem(text) {
  const t = String(text ?? "")
    .replace(/[_\s.:=?\-−–—,/|()π=3.14]+/gi, "")
    .replace(/radius|diameter|circle|area|perimeter|circumference|of|the|a|what|is/gi, "")
    .trim();
  return t.length < 1;
}

/** Rebuild common procedural stems from params (IDs unchanged). */
export function rebuildGeometryStemFrFr(question) {
  const p = question?.params || {};
  const kind = String(p.kind || "").replace(/^story_/, "");
  const radius = Number(p.radius);
  const hasRadius = Number.isFinite(radius) && radius > 0;

  if (kind === "circle_area" && hasRadius) {
    return `Un disque de rayon ${radius}. Quelle est son aire ? (π = 3.14)`;
  }
  if (kind === "circle_perimeter" && hasRadius) {
    return `Un cercle de rayon ${radius}. Quelle est la circonférence ? (π = 3.14)`;
  }
  if (kind === "concept_circle" && p.patternFamily === "radius_diameter") {
    return "Dans un cercle, la relation entre le diamètre et le rayon est :";
  }

  const side = Number(p.side ?? p.sideLength);
  const length = Number(p.length ?? p.a);
  const width = Number(p.width ?? p.b);
  if ((kind === "square_area" || kind.includes("square_area")) && Number.isFinite(side) && side > 0) {
    return `Quelle est l'aire du carré de côté ${side} ?`;
  }
  if ((kind === "square_perimeter" || kind.includes("square_perimeter")) && Number.isFinite(side) && side > 0) {
    return `Quel est le périmètre du carré de côté ${side} ?`;
  }
  if (
    (kind === "rectangle_area" || kind.includes("rect_area")) &&
    Number.isFinite(length) &&
    Number.isFinite(width) &&
    length > 0 &&
    width > 0
  ) {
    return `Quelle est l'aire du rectangle de longueur ${length} et de largeur ${width} ?`;
  }
  if (
    (kind === "rectangle_perimeter" || kind.includes("rect_perimeter")) &&
    Number.isFinite(length) &&
    Number.isFinite(width) &&
    length > 0 &&
    width > 0
  ) {
    return `Quel est le périmètre du rectangle de longueur ${length} et de largeur ${width} ?`;
  }

  return null;
}

function translateGeometryPhrase(text) {
  let out = String(text ?? "").trim();
  if (!out) return out;
  if (!containsHebrew(out)) return out;
  if (SHAPE_WORDS[out]) return SHAPE_WORDS[out];

  const mapped = mapGeometryLabel(out);
  if (mapped) return mapped;

  for (const [from, to] of PHRASES) {
    if (out.includes(from)) out = out.split(from).join(to);
  }

  out = out
    .replace(/(?!)/gu, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  return out;
}

function isShortAnswerField(field) {
  return field === "answers" || field === "options" || field === "acceptedAnswers";
}

export function localizeGeometryQuestionFrFr(question) {
  if (!question) return question;

  const base = { ...question };
  if (typeof base.question === "string" && containsHebrew(base.question)) base.question = "";
  if (typeof base.exerciseText === "string" && containsHebrew(base.exerciseText)) base.exerciseText = "";
  if (typeof base.questionLabel === "string" && containsHebrew(base.questionLabel)) base.questionLabel = "";

  const rebuilt = rebuildGeometryStemFrFr({ ...question, ...base, params: question.params });
  let resolvedStem = rebuilt && !containsHebrew(rebuilt) ? rebuilt : null;
  if (!resolvedStem) {
    const existing = String(question?.question || question?.exerciseText || "").trim();
    if (existing && !containsHebrew(existing)) resolvedStem = existing;
  }
  if (!resolvedStem) resolvedStem = "Calcule.";

  const out = mapQuestionTextFields({ ...base }, (field, value) => {
    if (field === "question" || field === "exerciseText" || field === "questionLabel") {
      if (!value || containsHebrew(value) || isNearlyEmptyStem(value)) return resolvedStem;
      return value;
    }
    if (isShortAnswerField(field)) {
      const label = mapGeometryLabel(value) || SHAPE_WORDS[String(value ?? "").trim()];
      if (label) return label;
      const text = String(value ?? "");
      if (!containsHebrew(text)) return text;
      return text.replace(/(?!)/gu, "").trim() || text;
    }
    if (!containsHebrew(String(value ?? ""))) return value;
    return translateGeometryPhrase(value);
  });

  out.question = resolvedStem;
  if (!out.exerciseText || containsHebrew(String(out.exerciseText)) || isNearlyEmptyStem(out.exerciseText)) {
    out.exerciseText = resolvedStem;
  }
  out.displayStemSource = rebuilt ? "params" : "passthrough";

  if (typeof out.correctAnswer === "string") {
    const mapped =
      mapGeometryLabel(out.correctAnswer) || SHAPE_WORDS[out.correctAnswer.trim()];
    if (mapped) out.correctAnswer = mapped;
  }

  return out;
}
