/**
 * French France (fr-FR) rebuilders for math question stems.
 * Anglais is the authority; params/numbers/operators unchanged.
 * Generated by scripts/i18n/bootstrap-fr-FR-stem-rebuilders.mjs — review instructional copy.
 */
import { BLANK } from "../math-constants.js";
import { containsHebrew, mapQuestionTextFields } from "../learning-question-content-locale.js";

const WEEKDAYS_FR = [
  "dimanche",
  "lundi",
  "mardi",
  "mercredi",
  "jeudi",
  "vendredi",
  "samedi"];

/** Residual HE→EN maps cleared — generators emit Anglais. Keep empty for API stability. */
const OBJECTS_FR = {};
const YES_NO = {};
const PRIME_COMPOSITE = {};
const PARITY = {};
const MATH_PHRASES = [];

function applyMathPhrases(text) {
  let out = String(text ?? "");
  for (const [he, en] of MATH_PHRASES) {
    if (out.includes(he)) out = out.split(he).join(en);
  }
  return out;
}

function inferMathLevelKey(question) {
  const lv = String(question?.params?.difficulty || question?.levelKey || "easy");
  if (lv === "hard" || lv === "medium") return lv;
  return "easy";
}

function inferSelectedOp(question) {
  return String(question?.operation || question?.params?.kind || "").replace(/^wp_/, "word_problems");
}

/** Rebuild word-problem / story stems from params when kind is known. */
export function rebuildMathStemFrFr(question) {
  const p = question?.params || {};
  const kind = String(p.kind || "");
  const gradeKey = String(question?.gradeKey || p.gradeKey || "g3");

  if (kind === "mul_groups_g1") {
    const objects = OBJECTS_FR[p.objects] || String(p.objects || "items");
    return `Il existe des groupes ${p.groups}. Chaque groupe a ${p.perGroup} ${objects}. Combien y a-t-il de ${objects} en tout ?`;
  }
  if (kind === "mul_skip_count_g1") {
    const seq = Array.isArray(p.seq) ? p.seq : [];
    const head = seq.slice(0, -1).join(", ");
    return `Compter par ${p.perGroup} : ${head}, ${BLANK}`;
  }
  if (kind === "ns_number_line" || kind === "ns_numéro_line_g1") {
    const nums = Array.isArray(p.numbers) ? p.numbers : [];
    const line = nums.map((n) => (n === BLANK || n === "__" ? BLANK : n)).join(" - ");
    return `Remplissez le nombre manquant sur la droite numérique : ${line}`;
  }
  if (kind === "ns_even_odd" || kind === "ns_parity") {
    return `${p.n ?? p.num} est-il un nombre pair ?`;
  }
  if (kind === "frac_half" || kind === "frac_half_reverse") {
    if (kind === "frac_half_reverse" && p.whole != null) {
      return `La moitié de ${BLANK} est ${p.whole / 2}. Quel est le nombre entier ?`;
    }
    return `Quelle est la moitié de ${p.whole ?? p.n} ?`;
  }
  if (kind === "frac_quarter" || kind === "frac_quarter_reverse") {
    if (kind === "frac_quarter_reverse" && p.whole != null) {
      return `Un quart de ${BLANK} équivaut à ${p.whole / 4}. Quel est le nombre entier ?`;
    }
    return `Qu'est-ce qu'un quart de ${p.whole ?? p.n} ?`;
  }
  if (
    kind === "frac_compare_like_den_g4" |
    kind === "frac_compare_like_den_g3" |
    kind === "frac_compare_same_den"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      return `Quelle fraction est la plus grande : ${p.n1}/${p.den} ou ${p.n2}/${p.den} ? Écrivez la plus grande fraction : ${BLANK}`;
    }
  }
  if (
    kind === "frac_same_den_add_g4" |
    kind === "frac_same_den_add" |
    kind === "frac_same_den_sub_g4" |
    kind === "frac_same_den_sub"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      const op = p.op === "add" || kind.includes("add") ? "+" : "−";
      return `${p.n1}/${p.den} ${op} ${p.n2}/${p.den} = ${BLANK}`;
    }
  }
  if (kind === "frac_simplify_intro_g4" || kind === "frac_simplify_intro_g3") {
    if (p.num != null && p.den != null) {
      return `Simplifiez la fraction ${p.num}/${p.den} : ${BLANK}`;
    }
  }
  if (kind === "frac_equivalent_expand" || kind === "frac_equivalent") {
    if (p.num != null && p.den != null && p.factor != null) {
      return `Trouver une fraction équivalente pour ${p.num}/${p.den} (multiplier par ${p.factor}) : ${BLANK}`;
    }
  }
  if (kind === "wp_simple_add" || kind === "wp_simple_add_g2") {
    if (kind === "wp_simple_add_g2") {
      return `Il y avait ${p.a} enfants en classe et ${p.b} de plus. Combien d'enfants y a-t-il maintenant ?`;
    }
    return `Leo a ${p.a} balles et en reçoit ${p.b} de plus. Combien de balles Léo a-t-il en tout ?`;
  }
  if (kind === "wp_simple_sub" || kind === "wp_simple_sub_g2") {
    if (kind === "wp_simple_sub_g2") {
      return `Il y a ${p.total} pommes dans un panier. ${p.give} ont été mangés. Combien reste-t-il de pommes ?`;
    }
    return `Lion a ${p.total} autocollants. Il donne ${p.give} à un ami. Combien d’autocollants reste-t-il à Léo ?`;
  }
  if (kind === "wp_pocket_money" || kind === "wp_pocket_money_g2") {
    return `Emma a ${p.money} euros. Elle achète une collation pour ${p.toy} euros. Combien d'argent reste-t-il ?`;
  }
  if (kind === "wp_groups_g2") {
    return `Chaque rangée comporte ${p.per} chaises. Il y a ${p.groups} lignes comme ça. Combien y a-t-il de chaises en tout ?`;
  }
  if (kind === "wp_groups_g3") {
    return `Chaque boîte contient ${p.per} crayons. Il y a ${p.groups} cases. Combien y a-t-il de crayons en tout ?`;
  }
  if (kind === "wp_groups_g4") {
    return `Chaque étagère contient ${p.per} livres. Il y a ${p.groups} étagères. Combien y a-t-il de livres en tout ?`;
  }
  if (kind === "wp_groups_late_g6") {
    return `Chaque conteneur contient ${p.per} pièces. ${p.groups} conteneurs ont été livrés. Combien de pièces en tout ?`;
  }
  if (kind === "wp_groups" || kind === "wp_groups_late") {
    return `Chaque caisse de fournitures contient ${p.per} paquets. ${p.groups} caisses ont été livrées. Combien de colis en tout ?`;
  }
  if (kind === "wp_comparison_more") {
    return `Noa a ${p.big} cartes et Yuval a ${p.small} cartes. Combien de cartes Noa possède-t-elle de plus que Yuval ?`;
  }
  if (kind === "wp_part_whole_g4") {
    return `Une salle compte ${p.whole} places. ${p.partA} sont pris pour un spectacle et les autres sont vides. Combien de sièges sont vides ?`;
  }
  if (kind === "wp_part_whole") {
    return `Une classe compte ${p.whole} élèves. ${p.partA} sont dans un club de football et les autres sont dans un club d'échecs. Combien d’élèves y a-t-il dans le club d’échecs ?`;
  }
  if (kind === "wp_change_stack_g4") {
    return `Un entrepôt comptait ${p.start} cartons. ${p.gain} de nouvelles boîtes ont été ajoutées et ${p.loss} ont été envoyées dans une autre agence. Combien de cartons reste-t-il ?`;
  }
  if (kind === "wp_change_stack") {
    return `Une bibliothèque contenait ${p.start} livres. ${p.gain} nouveaux livres ont été ajoutés et ${p.loss} ont été extraits. Combien de livres y a-t-il actuellement dans la bibliothèque ?`;
  }
  if (kind === "wp_time_days") {
    const start = WEEKDAYS_FR[p.startDayIdx] || "lundi";
    const end = WEEKDAYS_FR[p.endDayIdx] || "vendredi";
    return `Si aujourd'hui il est ${start}, combien de jours avant ${end} ?`;
  }
  if (kind === "wp_time_date") {
    return `Si aujourd'hui est le ${p.today}ème du mois, quelle date sera-t-il dans ${p.daysLater} jours ?`;
  }
  if (kind === "wp_coins") {
    return `Leo a ${p.coins1} pièces de 1 euro et ${p.coins2} pièces de 2 euros. Combien d’argent a-t-il en tout ?`;
  }
  if (kind === "wp_coins_spent") {
    return `Leo a ${p.total} euros en pièces. Il achète des bonbons pour ${p.spent} euros. Combien d'argent reste-t-il ?`;
  }
  if (kind === "wp_division_simple") {
    return `Il y a ${p.total} pommes divisées en groupes de ${p.perGroup} pommes chacun. Combien y a-t-il de groupes ?`;
  }
  if (kind === "wp_leftover") {
    return `Les élèves ${p.total} sont répartis en groupes de ${p.groupSize}. Combien d’élèves restent-ils sans groupe complet ?`;
  }
  if (kind === "wp_shop_discount") {
    return `Un t-shirt coûte ${p.price} euros avec une réduction de ${p.discPerc} %. Combien paies-tu après la réduction ?`;
  }
  if (kind === "wp_unit_cm_to_m") {
    return `Combien de mètres font ${p.cm} centimètres ? = ${BLANK}`;
  }
  if (kind === "wp_unit_g_to_kg") {
    return `Combien de kilogrammes font ${p.g} grammes ? = ${BLANK}`;
  }
  if (kind === "wp_distance_time") {
    return `Un enfant marche à une vitesse constante de ${p.speed} km/h pendant ${p.hours} heures. Combien de kilomètres parcourront-ils ?`;
  }
  if (kind === "wp_time_sum") {
    return `Un clip vidéo dure ${p.l1} minutes et un autre dure ${p.l2} minutes. Combien de minutes durent les deux clips ensemble ?`;
  }
  if (kind === "wp_average" || kind === "wp_average_g6") {
    if (kind === "wp_average_g6") {
      return `Un projet de groupe a obtenu les scores ${p.s1}, ${p.s2} et ${p.s3} sur trois étapes. Quel est le score moyen (arrondi à un nombre entier) ?`;
    }
    return `Leo a obtenu ${p.s1}, ${p.s2} et ${p.s3} à trois tests. Quelle est sa moyenne (arrondie à un nombre entier) ?`;
  }
  if (kind === "wp_multi_step" || kind === "wp_multi_step_g6") {
    return `Leo a ${p.money} euros. Il achète ${p.a} stylos et ${p.b} crayons, et chaque article coûte ${p.price} euros. Combien d’argent reste-t-il après les courses ?`;
  }
  if (kind === "operation_choice_word_problem_probe") {
    return `Il y a ${p.groups} groupes avec ${p.each} éléments dans chaque groupe. Quelle opération trouve le total ?`;
  }

  if (kind.startsWith("wp_") || inferSelectedOp(question) === "word_problems") {
    return null;
  }

  return applyMathLevelPresentationFrFr(
    String(question?.question || question?.exerciseText || ""),
    {
      selectedOp: question?.operation || inferSelectedOp(question),
      params: p,
      mathLevelKey: inferMathLevelKey(question),
      gradeKey,
    }
  );
}

/** Anglais mirror of applyMathLevelPresentation (math-question-generator.js). */
export function applyMathLevelPresentationFrFr(question, ctx) {
  const q0 = String(question || "");
  if (!q0.trim()) return q0;
  const { selectedOp, params, mathLevelKey, gradeKey } = ctx;
  const kind = String(params?.kind || "");
  if (kind.startsWith("wp_") || selectedOp === "word_problems") return q0;

  if (kind === "ns_complement100") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 100;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `Complète jusqu’à ${c} : que faut-il ajouter à ${b} pour atteindre ${c} ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Étant donné ${b} + ${BLANK} = ${c}. Quel est le numéro manquant ?`;
      }
      return `Problème de mots : il manque une partie à ${b} pour atteindre ${c} — combien ajouter ? = ${BLANK}`;
    }
  }

  if (kind === "ns_complement10") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 10;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `Jusqu’à ${c} : que faut-il ajouter à ${b} pour arriver à ${c} ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Manquant dans l'équation : ${b} + ${BLANK} = ${c}`;
      }
      return `Sans colonne : quel ajout à ${c} commence par ${b} ? = ${BLANK}`;
    }
  }

  if (kind === "scale_find") {
    const ml = params?.mapLength;
    const rl = params?.realLength;
    if (ml != null && rl != null) {
      if (mathLevelKey === "easy") {
        return `Sur une carte, un segment mesure ${ml} cm de long et dans la vraie vie il mesure ${rl} cm. Complétez l'échelle comme 1:${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Longueur de la carte ${ml} cm, longueur réelle ${rl} cm. Quelle est l'échelle ? Écrivez le nombre après 1 : = ${BLANK}`;
      }
      return `Carte ${ml} cm et réel ${rl} cm — l'échelle est 1:__. Quel est le numéro manquant ? = ${BLANK}`;
    }
  }

  if (kind === "scale_map_to_real") {
    const ml = params?.mapLength;
    const sc = params?.scale;
    if (ml != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `À l'échelle 1 :${sc}, combien de cm réels équivalent à ${ml} cm sur la carte ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Échelle 1 :${sc}. Une mesure cartographique de ${ml} cm — quelle est la longueur réelle en cm ? = ${BLANK}`;
      }
      return `Échelle 1 :${sc}, mesure cartographique ${ml} cm — trouvez la longueur réelle en cm = ${BLANK}`;
    }
  }

  if (kind === "scale_real_to_map") {
    const rl = params?.realLength;
    const sc = params?.scale;
    if (rl != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `A l'échelle 1 :${sc}, longueur réelle ${rl} cm — combien de cm sur la carte ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `Longueur réelle ${rl} cm, échelle 1:${sc}. Quelle est la longueur sur la carte ? = ${BLANK}`;
      }
      return `Convertir le réel en carte : ${rl} cm réel à 1:${sc} — combien de cm sur la page ? = ${BLANK}`;
    }
  }

  if (selectedOp === "compare" || kind === "cmp") {
    const raw = params?.exerciseText ? String(params.exerciseText) : "";
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 4;
    if (mathLevelKey === "easy") {
      const opts = [
        `Comparez les deux nombres et remplissez (<, =, >) : ${raw}`,
        `Signe de comparaison entre les nombres : ${raw}`,
        `Choisis < , = ou > — comparez : ${raw}`,
        `Comparez les valeurs et remplissez le signe : ${raw}`];
      return opts[pv].trim();
    }
    if (mathLevelKey === "medium") {
      const opts = [
        `Remplissez le bon signe de comparaison : ${raw}`,
        `Quel signe compare la paire ? ${raw}`,
        `Faites correspondre le signe de comparaison correct : ${raw}`,
        `Remplissez le signe entre les expressions numériques : ${raw}`];
      return opts[pv].trim();
    }
    const opts = [
      `Remplissez le signe de comparaison — vérifiez avant de choisir : ${raw}`,
      `Comparez soigneusement et choisissez un signe : ${raw}`,
      `Comparez avec soin et choisissez un signe : ${raw}`,
      `Vérification rapide : quel panneau convient ? ${raw}`];
    return opts[pv].trim();
  }

  if (selectedOp === "divisibility" || kind === "divisibility") {
    const num = params?.num;
    const div = params?.divisor;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (num != null && div != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Divisibilité : est-ce que ${num} se divise uniformément par ${div} ?`
          : `Vérifie : ${num} est-il un multiple de ${div} (pas de reste) ?`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Règles de divisibilité : est-ce que ${num} divise par ${div} ?`
          : `Division entière : ${num} ÷ ${div} — le résultat est-il un nombre entier ?`;
      }
      return pv === 0
        ? `Contrôle de divisibilité : est-ce que ${num} divise par ${div} ?`
        : `Diviseurs : est-ce que ${div} divise exactement ${num} ?`;
    }
  }

  if (selectedOp === "prime_composite" || kind === "prime_composite") {
    const num = params?.num;
    const subKind = String(params?.subKind || "pc_classify");
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (subKind === "pc_factor_count" && num != null) {
      if (mathLevelKey === "easy") return `Nombres premiers : combien de diviseurs possède ${num} ?`;
      if (mathLevelKey === "medium") {
        return `Compter les diviseurs : combien de diviseurs naturels possède ${num} (y compris 1 et lui-même) ?`;
      }
      return `Diviseurs : combien de diviseurs différents possède ${num} ?`;
    }
    if (subKind === "pc_smallest_prime" && num != null) {
      if (mathLevelKey === "easy") return `Facteur premier : quel est le plus petit facteur premier de ${num} ?`;
      if (mathLevelKey === "medium") return `Trouvez le plus petit facteur premier de ${num}.`;
      return `Facteurs : quel est le plus petit facteur premier de ${num} ?`;
    }
    if (subKind === "pc_divisor_pick" && num != null && params?.divisorCandidate != null) {
      const d = params.divisorCandidate;
      if (mathLevelKey === "easy") return `Vérification du diviseur : est-ce que ${d} divise ${num} de manière égale ?`;
      if (mathLevelKey === "medium") return `Diviseurs : est-ce que ${num} divise par ${d} ?`;
      return `Diviseurs : est-ce que ${d} divise exactement ${num} ?`;
    }
    if (num != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Nombres premiers : ${num} est-il premier ou composé ?`
          : `Classification de base : ${num} — premier ou composite ?`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Classez le nombre : ${num} — premier ou composite ?`
          : `Est-ce que ${num} a exactement deux diviseurs naturels différents ?`;
      }
      return pv === 0
        ? `${num} est-il premier ou composite ? Réfléchissez avant de choisir.`
        : `Preuve rapide : ${num} peut-il être divisé en deux facteurs supérieurs à 1 ?`;
    }
  }

  if (selectedOp === "powers" && (kind === "power_base" || kind === "power_calc")) {
    if (kind === "power_calc") {
      if (mathLevelKey === "easy") return `Pouvoirs : ${q0}`;
      if (mathLevelKey === "medium") return `Évaluer la puissance — ${q0}`;
      return `Pouvoirs : ${q0}`;
    }
    if (kind === "power_base") {
      if (mathLevelKey === "easy") return `Trouver la base dans la puissance : ${q0}`;
      if (mathLevelKey === "medium") return `Puzzle de puissance — ${q0}`;
      return `Base manquante au pouvoir : ${q0}`;
    }
  }

  if (selectedOp === "estimation") {
    if (kind === "est_add") {
      if (mathLevelKey === "easy") return q0.replace(/^Estimate\b/i, "Estimation d'arrondi : estimation");
      return q0;
    }
    if (kind === "est_mul" || kind === "est_quantity") return q0;
  }

  if (
    kind === "frac_half" |
    kind === "frac_half_reverse" |
    kind === "frac_quarter" |
    kind === "frac_quarter_reverse"
  ) {
    if (mathLevelKey === "easy") return `Fractions : ${q0}`;
    if (mathLevelKey === "medium") return `Fraction faisant partie d'un tout : ${q0}`;
    return `Fractions : ${q0}`;
  }

  if (kind === "fm_factor") {
    if (mathLevelKey === "easy") return `Facteurs : ${q0}`;
    if (mathLevelKey === "medium") return `Identifiez un diviseur : ${q0}`;
    return `Diviseurs et facteurs : ${q0}`;
  }
  if (kind === "fm_multiple") {
    if (mathLevelKey === "easy") return `Multiples : ${q0}`;
    if (mathLevelKey === "medium") return `Vérifie les multiples : ${q0}`;
    return `Multiples : ${q0}`;
  }

  if (selectedOp === "percentages" || selectedOp === "ratio" || selectedOp === "scale") return q0;

  if (kind === "fm_gcd" && params?.a != null && params?.b != null) {
    const { a, b } = params;
    if (mathLevelKey === "easy") {
      return `GCF : quel est le plus grand facteur commun de ${a} et ${b} ? = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return `Le plus grand facteur commun (PGCD) de ${a} et ${b} — qu'est-ce que c'est ? = ${BLANK}`;
    }
    return `GCF : réfléchissez d'abord — GCD(${a}, ${b}) = ${BLANK}`;
  }

  if (kind === "round" && params?.n != null && params?.toWhat != null) {
    const { n, toWhat } = params;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (toWhat === 10) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Arrondir aux dizaines : à quoi arrondit ${n} ? = ${BLANK}`
          : `Dix les plus proches : ${n} → ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `Arrondir ${n} à la dizaine la plus proche — résultat ? = ${BLANK}`
          : `Règle de l'arrondi par dizaines : ${n} = ${BLANK}`;
      }
      return pv === 0
        ? `Arrondir aux dizaines : ${n} → ? = ${BLANK}`
        : `Nombre correct après avoir arrondi ${n} aux dizaines = ${BLANK}`;
    }
    if (mathLevelKey === "easy") {
      return pv === 0
        ? `Arrondir à la centaine : à quoi arrondit ${n} ? = ${BLANK}`
        : `Centaine la plus proche : ${n} = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return pv === 0
        ? `Arrondir ${n} à la centaine la plus proche — résultat ? = ${BLANK}`
        : `Arrondir à la centaine : ${n} → ? = ${BLANK}`;
    }
    return pv === 0
      ? `Arrondir à la centaine : ${n} → ? = ${BLANK}`
      : `Nombre après arrondi ${n} à des centaines = ${BLANK}`;
  }

  if (kind === "dec_add" || kind === "dec_sub") {
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    const a = params?.a;
    const b = params?.b;
    const pl = params?.places ?? 1;
    if (a != null && b != null) {
      const af = Number(a).toFixed(pl);
      const bf = Number(b).toFixed(pl);
      if (kind === "dec_add") {
        if (mathLevelKey === "easy") {
          return pv === 0
            ? `Ajouter des décimales : ${af} + ${bf} = ${BLANK}`
            : `Somme directe : ${af} + ${bf} = ${BLANK}`;
        }
        return `Ajouter des décimales : ${af} + ${bf} = ${BLANK}`;
      }
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `Soustraire les décimales : ${af} − ${bf} = ${BLANK}`
          : `Différence directe : ${af} − ${bf} = ${BLANK}`;
      }
      return `Soustraire les décimales : ${af} − ${bf} = ${BLANK}`;
    }
  }

  if (selectedOp === "sequences") {
    if (mathLevelKey === "easy") {
      return q0.replace(/^Continue the sequence\b/i, "Continue le modèle de numéro");
    }
    return q0;
  }

  const looksNumericExercise =
    /=\s*__|=\s*\?\?|___|\?\?=/.test(q0) |
    (/^\d/.test(q0.trim()) && /[+\-×÷]/.test(q0));

  if (looksNumericExercise) return q0;
  if (/^Exercise\b/i.test(q0)) return q0;

  if (containsHebrew(q0) && params?.exerciseText && !containsHebrew(String(params.exerciseText))) {
    return String(params.exerciseText);
  }

  return q0;
}

function isShortAnswerField(field) {
  return field === "answers" || field === "options" || field === "acceptedAnswers";
}

function localizeMathField(_field, value, question) {
  const text = String(value ?? "");
  if (!containsHebrew(text)) return text;

  if (YES_NO[text.trim()]) return YES_NO[text.trim()];
  if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
  if (PARITY[text.trim()]) return PARITY[text.trim()];

  const rebuilt = rebuildMathStemFrFr(question);
  if (rebuilt && !containsHebrew(rebuilt) && (_field === "question" || _field === "exerciseText" || _field === "questionLabel")) {
    return rebuilt;
  }

  const presented = applyMathLevelPresentationFrFr(text, {
    selectedOp: question?.operation || inferSelectedOp(question),
    params: question?.params || {},
    mathLevelKey: inferMathLevelKey(question),
    gradeKey: question?.gradeKey || "g3",
  });
  if (presented && !containsHebrew(presented)) return presented;

  const phrased = applyMathPhrases(text);
  if (!containsHebrew(phrased)) return phrased;

  const stripped = phrased
    .replace(/(\d+)\s+remainder\s+(\d+)/gu, "1 $ reste 2 $")
    .replace(/(?!)/gu, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  return stripped || text;
}

function isNearlyEmptyStem(text) {
  const t = String(text ?? "")
    .replace(/[_\s.:=?\-−–—,/|]+/g, "")
    .trim();
  return t.length < 2;
}

const OP_SYMBOL_FR = Object.freeze({
  addition: "+",
  subtraction: "−",
  multiplication: "×",
  division: "÷",
});

/**
 * Build display stem from params/kind only (no Hébreu sentence translation).
 * @param {Record<string, unknown>} question
 */
function resolveMathDisplayStem(question) {
  const rebuilt = rebuildMathStemFrFr(question);
  if (rebuilt && String(rebuilt).trim() && !containsHebrew(rebuilt)) {
    return { stem: rebuilt, source: "params" };
  }
  const p = question?.params && typeof question.params === "object" ? question.params : {};
  const opRaw = String(question?.operation || p.kind || "").replace(/^wp_/, "");
  const a = p.a ?? question?.a;
  const b = p.b ?? question?.b;
  if (a != null && b != null && OP_SYMBOL_FR[opRaw]) {
    return { stem: `Combien de polices ${a} ${OP_SYMBOL_FR[opRaw]} ${b} ?`, source: "generic" };
  }
  for (const candidate of [p.exerciseText, question?.exerciseText, question?.question]) {
    if (typeof candidate === "string" && candidate.trim() && !containsHebrew(candidate)) {
      return { stem: String(candidate).trim(), source: "passthrough" };
    }
  }
  return { stem: null, source: "none" };
}

/**
 * Localize math question for French France (fr-FR) display.
 * Display stems come from params/kind templates — not from translating Hébreu prose.
 * Option tokens use closed dictionaries (logical labels), not sentence MT.
 */
export function localizeMathQuestionFrFr(question) {
  if (!question) return question;

  const base = { ...question };
  // Drop authored Hébreu stems so params are the sole stem authority.
  if (typeof base.question === "string" && containsHebrew(base.question)) base.question = "";
  if (typeof base.exerciseText === "string" && containsHebrew(base.exerciseText)) base.exerciseText = "";
  if (typeof base.questionLabel === "string" && containsHebrew(base.questionLabel)) base.questionLabel = "";

  const { stem, source } = resolveMathDisplayStem({ ...question, ...base, params: question.params });
  const resolvedStem = stem || "Calcule.";

  const out = mapQuestionTextFields({ ...base }, (field, value, q) => {
    if (field === "question" || field === "exerciseText" || field === "questionLabel") {
      if (!value || containsHebrew(value) || isNearlyEmptyStem(value)) return resolvedStem;
      return value;
    }
    // Answers/options: closed token maps only (no full-sentence HE→EN).
    if (isShortAnswerField(field)) {
      const text = String(value ?? "");
      if (!containsHebrew(text)) return text;
      if (YES_NO[text.trim()]) return YES_NO[text.trim()];
      if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
      if (PARITY[text.trim()]) return PARITY[text.trim()];
      if (OBJECTS_FR[text.trim()]) return OBJECTS_FR[text.trim()];
      const digitsOnly = text.replace(/(?!)/gu, "").trim();
      return digitsOnly || text;
    }
    if (!containsHebrew(String(value ?? ""))) return value;
    return value;
  });

  out.question = resolvedStem;
  if (!out.exerciseText || containsHebrew(String(out.exerciseText)) || isNearlyEmptyStem(out.exerciseText)) {
    out.exerciseText = resolvedStem;
  }
  out.displayStemSource = source;

  if (typeof out.correctAnswer === "string") {
    const ca = out.correctAnswer.trim();
    if (YES_NO[ca]) out.correctAnswer = YES_NO[ca];
    else if (PRIME_COMPOSITE[ca]) out.correctAnswer = PRIME_COMPOSITE[ca];
    else if (PARITY[ca]) out.correctAnswer = PARITY[ca];
    else if (containsHebrew(ca)) {
      out.correctAnswer = ca.replace(/(?!)/gu, "").trim() || ca;
    }
  }
  if (Array.isArray(out.answers)) {
    out.answers = out.answers.map((a) =>
      typeof a === "string" ? localizeMathField("answers", a, out) : a
    );
  }
  return out;
}
