/**
 * English UI strings for parent worksheets module.
 * @module lib/worksheets/worksheet-ui
 */

export const WORKSHEET_UI_EN = {
  hubTitle: "Printable worksheets",
  hubSubtitle:
    "Pick a ready-made worksheet, create a custom one, or get worksheets recommended by the system based on your child's practice.",
  hubIntro:
    "Every worksheet opens in a preview before printing. An optional answer key is available for your convenience.",
  tabReady: "Ready worksheet",
  tabGenerator: "Create new",
  tabRecommendations: "System recommendation",
  print: "Print",
  preview: "Preview",
  answerKey: "Answer key",
  answerKeySeparate: "Separate answer key - generated only on explicit request",
  inkSave: "Ink saver",
  noAnswersInWorksheet: "No answers on the worksheet",
  subjectMath: "Math",
  subjectGeometry: "Geometry",
  subjectHebrew: "Hebrew",
  subjectEnglish: "English",
  blockedAudio: "This question requires audio and cannot be printed",
  blockedImage: "This question requires an image and cannot be printed",
  questionLabel: "Question",
  nameField: "Name",
  dateField: "Date",
  gradeField: "Grade",
  topicField: "Topic",
  practiceFormatField: "Practice type",
  levelField: "Level",
  countField: "Number of questions",
  includeAnswers: "Include answer key",
  preferMcq: "Multiple choice",
  preferMcqHint: "If available, multiple-choice options will be shown",
  preferMcqUnavailable: "No multiple-choice questions are available for this topic",
  createWorksheet: "Create worksheet",
  viewAndPrint: "View and print",
  back: "Back",
  loading: "Loading…",
  errorGeneric: "Something went wrong. Please try again.",
  noStudents: "No children are linked to this account.",
  selectChild: "Select a child",
  recommendationsEmpty: "After a bit more practice, we'll be able to suggest worksheets tailored to your child.",
  recommendationsEmptyTitle: "No recommendations yet",
  recommendationsTitle: "Recommendations based on practice",
  recommendationsHint: "Recommendations are based on topics your child practiced recently - not on the parent report.",
  readyTitle: "Ready-made worksheets",
  readyHint: "30 ready worksheets · 12 questions each.",
  readyEmptyTitle: "No worksheets found",
  readyEmptyText: "Try changing the filters - or select all subjects, grades and levels.",
  createTitle: "Create a new worksheet",
  createHint: "Choose a subject, grade, topic and level - then create a worksheet ready to print.",
  mixedTopicsTitle: "Choose topics for mixed practice",
  mixedTopicsHint: "Check the topics to include in the mixed practice. All topics are checked by default.",
  mixedTopicsSelectAll: "Select all topics",
  mixedTopicsEmptyError: "Please select at least one topic for practice.",
  previewTitle: "Preview",
  documentTitle: "Worksheet",
  answerKeyTitle: "Answer key",
  noPreviewData: "No worksheet to preview. Go back to create one.",
  generating: "Creating worksheet…",
  refreshQuestions: "Refresh questions",
  refreshingQuestions: "Generating new questions…",
  refreshQuestionsError: "We couldn't generate new questions. Please try again.",
  answerKeyStale: "The answer key was updated to match the current questions. Try opening the answer key again.",
  questionCount: "questions",
  createFromRecommendation: "Create worksheet from recommendation",
  publicDemoTitle: "Try the worksheet generator",
  publicDemoHint: "A short 8-question demo - choose a subject, grade and topic.",
  publicDemoLockedTopic: "More topics are available in the full parent system",
  publicReadyTitle: "Ready-made worksheets by grade",
  publicReadyHint: "35 ready worksheets - filter, preview, print and check with an answer key.",
  publicPreviewLost: "Preview data is not available. Go back to the worksheets page and choose a worksheet again.",
  publicPreviewLostCta: "Back to worksheets",
};

/** @deprecated use WORKSHEET_UI_EN */
export const WORKSHEET_UI_HE = WORKSHEET_UI_EN;
