import { globalBurnDownCopy } from "../../lib/i18n/global-burn-down-copy.js";
/**
 * English UI strings for parent worksheets module.
 * @module lib/worksheets/worksheet-ui
 */

export const WORKSHEET_UI_EN = {
  hubTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "printable_worksheets"),
  hubSubtitle:
    "Pick a ready-made worksheet, create a custom one, or get worksheets recommended by the system based on your child's practice.",
  hubIntro:
    "Every worksheet opens in a preview before printing. An optional answer key is available for your convenience.",
  tabReady: globalBurnDownCopy("lib__worksheets__worksheet-ui", "ready_worksheet"),
  tabGenerator: globalBurnDownCopy("lib__worksheets__worksheet-ui", "create_new"),
  tabRecommendations: globalBurnDownCopy("lib__worksheets__worksheet-ui", "system_recommendation"),
  print: "Print",
  preview: globalBurnDownCopy("lib__worksheets__worksheet-ui", "preview"),
  answerKey: globalBurnDownCopy("lib__worksheets__worksheet-ui", "answer_key"),
  answerKeySeparate: globalBurnDownCopy("lib__worksheets__worksheet-ui", "separate_answer_key_generated_only_on_explicit_request"),
  inkSave: globalBurnDownCopy("lib__worksheets__worksheet-ui", "ink_saver"),
  noAnswersInWorksheet: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_answers_on_the_worksheet"),
  subjectMath: "Math",
  subjectGeometry: "Geometry",
  subjectHebrew: globalBurnDownCopy("lib__worksheets__worksheet-ui", "hebrew"),
  subjectEnglish: "English",
  blockedAudio: globalBurnDownCopy("lib__worksheets__worksheet-ui", "this_question_requires_audio_and_cannot_be_printed"),
  blockedImage: globalBurnDownCopy("lib__worksheets__worksheet-ui", "this_question_requires_an_image_and_cannot_be_printed"),
  questionLabel: globalBurnDownCopy("lib__worksheets__worksheet-ui", "question"),
  nameField: "Name",
  dateField: "Date",
  gradeField: "Grade",
  topicField: "Topic",
  practiceFormatField: globalBurnDownCopy("lib__worksheets__worksheet-ui", "practice_type"),
  levelField: "Level",
  countField: globalBurnDownCopy("lib__worksheets__worksheet-ui", "number_of_questions"),
  includeAnswers: globalBurnDownCopy("lib__worksheets__worksheet-ui", "include_answer_key"),
  preferMcq: globalBurnDownCopy("lib__worksheets__worksheet-ui", "multiple_choice"),
  preferMcqHint: globalBurnDownCopy("lib__worksheets__worksheet-ui", "if_available_multiple_choice_options_will_be_shown"),
  preferMcqUnavailable: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_multiple_choice_questions_are_available_for_this_topic"),
  createWorksheet: globalBurnDownCopy("lib__worksheets__worksheet-ui", "create_worksheet"),
  viewAndPrint: globalBurnDownCopy("lib__worksheets__worksheet-ui", "view_and_print"),
  back: "Back",
  loading: globalBurnDownCopy("lib__worksheets__worksheet-ui", "loading"),
  errorGeneric: globalBurnDownCopy("lib__worksheets__worksheet-ui", "something_went_wrong_please_try_again"),
  noStudents: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_children_are_linked_to_this_account"),
  selectChild: globalBurnDownCopy("lib__worksheets__worksheet-ui", "select_a_child"),
  recommendationsEmpty: "After a bit more practice, we'll be able to suggest worksheets tailored to your child.",
  recommendationsEmptyTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_recommendations_yet"),
  recommendationsTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "recommendations_based_on_practice"),
  recommendationsHint: globalBurnDownCopy("lib__worksheets__worksheet-ui", "recommendations_are_based_on_topics_your_child_practiced_recently_not_on"),
  readyTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "ready_made_worksheets"),
  readyHint: "30 ready worksheets · 12 questions each.",
  readyEmptyTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_worksheets_found"),
  readyEmptyText: globalBurnDownCopy("lib__worksheets__worksheet-ui", "try_changing_the_filters_or_select_all_subjects_grades_and_levels"),
  createTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "create_a_new_worksheet"),
  createHint: globalBurnDownCopy("lib__worksheets__worksheet-ui", "choose_a_subject_grade_topic_and_level_then_create_a_worksheet_ready_to_"),
  mixedTopicsTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "choose_topics_for_mixed_practice"),
  mixedTopicsHint: globalBurnDownCopy("lib__worksheets__worksheet-ui", "check_the_topics_to_include_in_the_mixed_practice_all_topics_are_checked"),
  mixedTopicsSelectAll: globalBurnDownCopy("lib__worksheets__worksheet-ui", "select_all_topics"),
  mixedTopicsEmptyError: globalBurnDownCopy("lib__worksheets__worksheet-ui", "please_select_at_least_one_topic_for_practice"),
  previewTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "preview"),
  documentTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "worksheet"),
  answerKeyTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "answer_key"),
  noPreviewData: globalBurnDownCopy("lib__worksheets__worksheet-ui", "no_worksheet_to_preview_go_back_to_create_one"),
  generating: globalBurnDownCopy("lib__worksheets__worksheet-ui", "creating_worksheet"),
  refreshQuestions: globalBurnDownCopy("lib__worksheets__worksheet-ui", "refresh_questions"),
  refreshingQuestions: globalBurnDownCopy("lib__worksheets__worksheet-ui", "generating_new_questions"),
  refreshQuestionsError: "We couldn't generate new questions. Please try again.",
  answerKeyStale: globalBurnDownCopy("lib__worksheets__worksheet-ui", "the_answer_key_was_updated_to_match_the_current_questions_try_opening_th"),
  questionCount: "questions",
  createFromRecommendation: globalBurnDownCopy("lib__worksheets__worksheet-ui", "create_worksheet_from_recommendation"),
  publicDemoTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "try_the_worksheet_generator"),
  publicDemoHint: "A short 8-question demo - choose a subject, grade and topic.",
  publicDemoLockedTopic: globalBurnDownCopy("lib__worksheets__worksheet-ui", "more_topics_are_available_in_the_full_parent_system"),
  publicReadyTitle: globalBurnDownCopy("lib__worksheets__worksheet-ui", "ready_made_worksheets_by_grade"),
  publicReadyHint: "35 ready worksheets - filter, preview, print and check with an answer key.",
  publicPreviewLost: globalBurnDownCopy("lib__worksheets__worksheet-ui", "preview_data_is_not_available_go_back_to_the_worksheets_page_and_choose_"),
  publicPreviewLostCta: globalBurnDownCopy("lib__worksheets__worksheet-ui", "back_to_worksheets"),
};

/** @deprecated use WORKSHEET_UI_EN */
export const WORKSHEET_UI_HE = WORKSHEET_UI_EN;
