/**
 * Build map-chunk-16.json from strings-chunk-16.json + ordered ID translations.
 * Ensures exact English keys (including curly apostrophes).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(__dirname, "strings-chunk-16.json"), "utf8"));

const id = [
  "Mengamati dan memotret satwa liar tanpa mengganggunya.",
  "Lautan dan atmosfer saling bertukar energi dan kelembapan.",
  "Arus laut juga memindahkan air hangat dan dingin mengelilingi bumi, memengaruhi suhu di seluruh dunia.",
  "Arus laut mengubah suhu seluruh planet setiap musim",
  "Peristiwa di laut dapat menggabungkan beberapa faktor pendukung.",
  "Lautan dan es membantu menstabilkan pola iklim.",
  "Lautan adalah sumber utama air yang menguap ke atmosfer.",
  "Lautan menghilangkan semua sinar matahari",
  "Lautan menghentikan Bumi bergerak",
  "Lautan, angin, awan, dan daya pantul permukaan juga membentuk sabuk iklim",
  "Dari kulit.",
  "Minyak — tercampur rata dengan air saat diaduk.",
  "Omnivora dapat makan lebih banyak jenis makanan.",
  "Omnivora dapat makan banyak jenis makanan.",
  "Pada hari cerah pantai menghangat; di malam hari laut tetap relatif hangat. Deskripsi mana yang cocok untuk angin laut khas di siang hari?",
  "Pada hari cerah, udara hangat naik karena panas berpindah dari tanah yang hangat ke udara yang lebih sejuk di atasnya.",
  "Di darat",
  "Di tanah.",
  "Satu lengan dan satu kaki",
  "Yang hanya berdasarkan tebakan beruntung tanpa pengujian",
  "Yang hanya berdasarkan perasaan",
  "Satu batang cokelat memberi semua zat gizi selamanya.",
  "Yang dipilih secara acak",
  "Satu faktor yang kamu ubah dengan sengaja",
  "Satu kata terakhir tanpa dukungan data",
  "Satu putaran penuh sekitar satu hari.",
  "Satu putaran penuh memakan waktu sekitar 24 jam.",
  "Satu putaran penuh Bumi memakan waktu sekitar satu hari.",
  "Yang dibuat tanpa percobaan",
  "Satu variabel utama membuat hasil lebih jelas.",
  "Satu pengukuran selalu cukup",
  "Satu kali menanam menghilangkan semua risiko selamanya",
  "Satu hasil saja jarang cukup untuk menarik kesimpulan ilmiah yang kuat.",
  "Satu warna polos tanpa pola di kulit",
  "Yang didukung oleh hasil pengukuran",
  "Yang mengubah angka agar terlihat lebih bagus",
  "Yang mengabaikan semua pengukuran",
  "Yang sesuai dengan data dan menjelaskan apa yang ditunjukkan data",
  "Satu uji coba selalu cukup, tidak peduli seberapa presisi yang dibutuhkan",
  "Satu uji coba bisa saja kebetulan beruntung. Hasil yang mirip pada pengulangan membuat temuan lebih dapat dipercaya.",
  "Satu kali mengelilingi Matahari memakan waktu sekitar satu tahun.",
  "Satu uji coba yang aneh mungkin merupakan kesalahan.",
  "Satu variabel yang dipilih untuk diubah dengan sengaja",
  "Hanya perubahan warna tanpa kaitan dengan kelangsungan hidup",
  "Hanya hutan, tidak pernah laut atau padang rumput",
  "Hanya gas di alam di setiap musim",
  "Hanya jantung, tanpa paru-paru atau organ lain",
  "Hanya lapisan kulit kayu pohon",
  "Hanya daftar nama teman",
  "Hanya perubahan denyut tanpa kaitan dengan panas",
  "Hanya batang tanpa daun",
  "Hanya dewasa tanpa tahapan",
  "Hanya telur tanpa perkembangan",
  "Hanya hewan yang membutuhkan udara",
  "Hanya hewan yang bermigrasi di malam hari",
  "Hanya penampilan, tanpa peran perlindungan",
  "Hanya sebagai hewan yang memburu ikan",
  "Hanya pada siang hari setiap hari sepanjang tahun",
  "Hanya pada siang hari di pertengahan musim panas",
  "Hanya di ujung sebagai predator puncak",
  "Hanya bulu burung",
  "Hanya permen",
  "Hanya permen dan soda",
  "Hanya respirasi seluler seperti pada hewan",
  "Hanya papan tulis di kelas",
  "Hanya air hujan bersih",
  "Hanya jumlah awan, tanpa kaitan dengan waktu dalam tahun",
  "Hanya awan yang menentukan lama siang",
  "Hanya musim dingin dan hujan yang ada di semua tempat di Bumi.",
  "Hanya warna yang menentukan konduktivitas",
  "Hanya warna yang menunjukkan kekerasan",
  "Hanya kegelapan dan oli mesin",
  "Hanya kegelapan dan tanpa air",
  "Hanya kegelapan dan garam",
  "Hanya laut dalam, tidak pernah pantai, hutan, atau terumbu",
  "Hanya jauh di bawah laut",
  "Hanya menggambar yang penting",
  "Hanya kertas kering",
  "Hanya selama gelombang panas",
  "Hanya selama badai petir yang hebat.",
  "Hanya di siang hari, saat Matahari juga ada.",
  "Hanya selama minggu musim panas kering yang paling panas",
  "Hanya emoji tanpa data",
  "Hanya pabrik yang membutuhkan air; rumah tidak pernah",
  "Hanya kekerasan kuku",
  "Hanya sisik ikan",
  "Hanya makanan — hewan tidak perlu minum air.",
  "Hanya es beku selamanya",
  "Hanya jamur yang memburu mamalia",
  "Hanya menebak dan tidak pernah memeriksa di kehidupan nyata",
  "Hanya tebakan tanpa mencatat hasil",
  "Hanya bersenang-senang tanpa aturan pelindung",
  "Hanya suhu tinggi yang membahayakan serangga",
  "Hanya di bulu hewan selamanya",
  "Hanya di awan",
  "Hanya di air dalam tempat tidak ada sinar matahari.",
  "Hanya di tanah, tidak pernah di air.",
  "Hanya di kuku jari",
  "Hanya di folikel rambut",
  "Hanya di telinga luar",
  "Hanya di air, tidak pernah di tanah.",
  "Hanya di dalam kotak logam",
  "Hanya di dalam kulit kayu pohon",
  "Hanya ke dalam air",
  "Hanya lelucon tanpa angka",
  "Hanya daun tanpa kelopak atau nektar",
  "Hanya sisa makanan",
  "Hanya sisa cahaya",
  "Hanya nelayan legal yang memengaruhi ukuran populasi",
  "Hanya es cair",
  "Hanya logam hidup",
  "Hanya makhluk hidup yang memiliki wujud zat",
  "Hanya paru-paru, tanpa jantung atau ginjal",
  "Hanya mencairkan padatan menjadi cairan",
  "Hanya mencairkan es menjadi air",
  "Hanya kaleng logam",
  "Hanya potongan logam",
  "Hanya logam yang memiliki wujud zat",
  "Hanya siklus suasana hati tanpa kaitan dengan suhu atau hujan",
  "Hanya cahaya bulan",
  "Hanya bulan yang mengorbit Bumi",
  "Hanya otot dan gerakan yang menjaga hewan tetap hidup.",
  "Hanya sampel museum tanpa lingkungan hidup",
  "Hanya penglihatan malam dalam kegelapan total",
  "Hanya ikan laut",
  "Hanya garam laut",
  "Hanya gelombang laut",
  "Hanya satu hewan memakan satu tumbuhan selamanya",
  "Hanya satu kelompok makanan yang pernah berguna",
  "Hanya satu bahan padat",
  "Hanya satu sistem yang pernah dibutuhkan",
  "Hanya pendapat tanpa bukti",
  "Hanya sapi lain",
  "Hanya kelinci lain",
  "Hanya zat gizi kemasan yang dibeli dari toko",
  "Hanya memetik dengan izin, dan sisakan cukup tanaman tumbuh untuk alam.",
  "Hanya planet dan tetesan air tinggi di atmosfer.",
  "Hanya tumbuhan yang dapat beradaptasi dengan lingkungannya — hewan tidak bisa.",
  "Hanya plastik dan kristal garam",
  "Hanya plastik untuk kemasan",
  "Hanya tanah plastik",
  "Hanya air tercemar yang biasanya membahayakan manusia",
  "Hanya air garam murni",
  "Hanya gula cepat yang menjadi sumber energi stabil",
  "Hanya air hujan",
  "Hanya batu",
  "Hanya batu dan mineral",
  "Hanya batu dan mineral tanpa kehidupan",
  "Hanya batu tanpa udara",
  "Hanya akar yang berespirasi, bukan daun",
  "Hanya akar tanpa bunga",
  "Hanya musim, tanpa siang dan malam",
  "Hanya teduh dan udara lebih sejuk",
  "Hanya bayangan dari sinar matahari",
  "Hanya warna langit, tanpa kaitan dengan musim",
  "Hanya padat dan gas, tidak pernah dalam bentuk cair",
  "Hanya gelombang suara",
  "Hanya suara dari luar",
  "Hanya gula dan tidak ada yang lain",
  "Hanya sinar matahari dan udara segar untuk tetap hidup",
  "Hanya angin kencang, tanpa pengaruh Bulan",
  "Hanya kemampuan mencerna batu",
  "Hanya jumlah plastik di kota",
  "Hanya jumlah sinar matahari yang diukur di satu tempat tertentu.",
  "Hanya otot lengan",
  "Hanya warna buku catatan murid",
  "Hanya warna bangunan kota",
  "Hanya warna celana seseorang",
  "Hanya warna pakaianmu",
  "Hanya warna buku catatanmu",
  "Hanya kedalaman inti Bumi",
  "Hanya nama percobaan",
  "Hanya tebakan akhir, dengan metode dihapus",
  "Hanya kuku jari",
  "Hanya wujud gas pada setiap suhu",
  "Hanya kepala yang tumbuh, bukan bagian lain",
  "Hanya Bulan, yang ada di langit malam.",
  "Hanya jarak Bulan dari Bumi, tanpa kaitan dengan Matahari",
  "Hanya nama dinosaurus kuno",
  "Hanya jumlah jendela kelas",
  "Hanya jumlah batu di taman",
  "Hanya jumlah hari libur sekolah",
  "Hanya warna kaos pengamat",
  "Hanya laut yang menentukan suhu, dan gas rumah kaca hanya memengaruhi gravitasi",
  "Hanya suhu laut jauh dari daratan",
  "Hanya warna luar yang menentukan jenisnya",
  "Hanya bagian Bulan yang menghadap Bumi yang diterangi Matahari yang terlihat, dan posisi Bulan berubah sepanjang bulan.",
  "Hanya posisi planet di tata surya",
  "Hanya batu jauh di bawah permukaan Bumi",
  "Hanya ukuran sampel, tanpa kaitan dengan nilai yang dicatat",
  "Hanya ukuran potongan yang penting",
  "Hanya tata surya tanpa galaksi lain",
  "Hanya rasa mineral tanah",
  "Hanya nama guru, tanpa kaitan dengan langit",
  "Hanya judul film favoritmu",
  "Hanya lidah",
  "Hanya prakiraan cuaca",
  "Hanya memikirkan alam selama satu hari khusus setiap tahun.",
  "Hanya untuk menjaga sistem tubuh sepenuhnya terpisah",
  "Hanya untuk menjaga tubuh tetap hangat",
  "Hanya untuk memindahkan darah sesuai detak jantung",
  "Hanya untuk mengisi waktu tanpa pertanyaan percobaan yang jelas",
  "Hanya untuk menyimpan energi, tanpa kaitan dengan informasi",
  "Hanya untuk memperkuat rambut",
  "Hanya predator puncak tanpa mangsa",
  "Hanya kulit kayu untuk sarang di laut",
  "Hanya teduh pohon",
  "Hanya dua musim dalam setahun",
  "Hanya di bawah gelombang laut",
  "Hanya akar di bawah tanah",
  "Hanya batu yang tidak tercerna",
  "Hanya batu yang tidak terpakai",
  "Hanya air laut yang sangat dingin",
  "Hanya sangat pagi sebelum matahari terbit.",
  "Hanya mencuci rambutmu setiap pagi.",
  "Hanya air — makanan tidak penting bagi sebagian besar hewan.",
  "Hanya air — makanan tidak diperlukan.",
  "Hanya apa yang kamu harapkan akan terjadi",
  "Hanya ketika matahari paling dekat pada tengah malam",
  "Kaca buram yang tidak bisa kamu lihat tembus",
  "Bahan buram menghalangi semua cahaya, dan bahan tembus cahaya sebagian hanya membiarkan sedikit cahaya lewat.",
  "Benda buram menghalangi cahaya dan membentuk bayangan.",
  "Batu buram",
  "Membuka laporan sebelum percobaan",
  "Hanya perubahan cuaca harian biasa",
  "Sistem organ bekerja sama menjaga kondisi tetap stabil.",
  "Sistem organ saling berbagi pekerjaan yang tumpang tindih.",
  "Pupuk organik berasal dari bahan hewan atau tumbuhan yang terurai dan menambah zat gizi ke tanah.",
  "Bahan organik berasal dari makhluk hidup—contohnya kayu, kapas, dan wol.",
  "Bahan organik berasal dari makhluk hidup—kayu, kapas, dan wol adalah contohnya.",
  "Atur berbagi kendaraan atau bersepeda di jalur aman jika memungkinkan",
  "Data yang teratur lebih mudah dibandingkan.",
  "Data yang teratur mendukung kesimpulan yang lebih baik.",
  "Pengukuran dan pengamatan yang teratur dari setiap uji coba",
  "Catatan yang teratur memudahkan analisis.",
  "Organ seperti lambung dan usus membantu mencerna makanan.",
  "Kondisi lain dijaga sama agar perbandingan adil.",
  "Spesies lain yang bergantung padanya mungkin kehilangan makanan atau keseimbangan dalam sistem",
  "Orang lain tidak dapat memeriksa temuan dengan baik",
  "Orang lain harus bisa membaca tabelmu.",
  "Galaksi kita disebut Bima Sakti.",
  "Tata surya kita memiliki delapan planet: Merkurius, Venus, Bumi, Mars, Jupiter, Saturnus, Uranus, dan Neptunus.",
  "Matahari kita adalah bintang di pusat tata surya kita.",
  "Belajar di luar ruangan membawa kewajiban untuk bertindak bertanggung jawab.",
  "Planet luar selalu lebih kecil daripada planet dalam",
  "Ada data pencilan. Lebih banyak uji coba membantumu melihat apakah suatu pola nyata atau hanya gangguan.",
  "Data pencilan perlu diperiksa: bisa ekstrem yang nyata atau kesalahan. Ilmuwan mendokumentasikan keputusan agar transparan.",
  "Terlalu banyak air dapat membuat akar tidak mendapat cukup udara dan dapat merusak tanaman.",
  "Burung hantu memburu mangsa untuk makanan. Hubungan predator–mangsa memindahkan energi melalui jaring makanan.",
  "Oksigen",
];

if (id.length !== en.length) {
  console.error(`Length mismatch: en=${en.length} id=${id.length}`);
  process.exit(1);
}

const map = Object.fromEntries(en.map((k, i) => [k, id[i]]));
fs.writeFileSync(path.join(__dirname, "map-chunk-16.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("wrote map-chunk-16.json keys=", Object.keys(map).length);
