import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(__dirname, "strings-chunk-18.json"), "utf8"));

const id = [
  "Predator adalah konsumen dalam rantai makanan.",
  "Predator menangkap dan memakan mangsa. Elang adalah karnivora yang memburu hewan lebih kecil.",
  "Predator membantu mengendalikan jumlah mangsa. Dengan lebih sedikit predator, mangsa dapat bertambah sampai makanan atau ruang menjadi terbatas.",
  "Predator membantu mengendalikan populasi mangsa.",
  "Predator membantu menjaga jumlah hewan tetap seimbang.",
  "Predator membantu mengatur jumlah mangsa. Tanpa mereka, penggembalaan berlebih atau ketidakseimbangan lain dapat terjadi.",
  "Predator berburu; mangsa diburu.",
  "Predator membatasi seberapa besar populasi mangsa dapat tumbuh.",
  "Predator juga dapat memakai kamuflase saat berburu.",
  "Predator berhenti membutuhkan energi",
  "Predator akan mulai berfotosintesis sebagai gantinya.",
  "Persiapan mendukung kinerja yang aman.",
  "Tanah yang disiapkan tanpa batang atau daun",
  "Berpura-pura tes tidak pernah terjadi",
  "Mencegah erosi melindungi kualitas air dan tanah.",
  "Mencegah pencemaran melindungi komunitas dan alam.",
  "Mencegah pencemaran melindungi ekosistem.",
  "Pencegahan menjaga orang dan alam lebih aman.",
  "Hewan mangsa diburu oleh predator.",
  "Mangsa dapat bersembunyi dari pemburu, dan pemburu dapat mendekat diam-diam ke mangsa.",
  "Mangsa selalu hewan yang memburu yang lain dalam rantai makanan",
  "Populasi mangsa mungkin tumbuh lebih besar untuk sementara",
  "Spesies mangsa juga punya pertahanan, seperti bersembunyi atau kecepatan.",
  "Mangsa akan langsung menjadi produsen.",
  "Prosedur, pengamatan, pengukuran, dan tanggal",
  "Kayu olahan yang masih mengandung sel tumbuhan",
  "Menghasilkan serbuk sari untuk tumbuhan",
  "Menghasilkan urin untuk ginjal",
  "Produsen",
  "Tumbuhan produsen membuat bahan organik yang memberi makan banyak tingkat jaring makanan.",
  "Produsen menangkap energi dari matahari.",
  "Produsen membentuk dasar sebagian besar jaring makanan.",
  "Produsen membentuk dasar energi. Konsumen bergantung pada energi itu secara langsung atau tidak langsung.",
  "Produsen membuat energi makanan dari sinar matahari. Hewan yang memakan tumbuhan bergantung pada makanan itu.",
  "Produsen memulai rantai makanan dengan membuat makanan kaya energi. Herbivora memakan tumbuhan, lalu hewan lain mungkin memakan herbivora itu.",
  "Produsen seperti tumbuhan menangkap sinar matahari dan membuat makanan. Energi makanan itu lalu bergerak ke hewan yang memakan tumbuhan dan ke hewan yang memakan hewan lain.",
  "Produsen seperti tumbuhan menangkap sinar matahari dan menyediakan energi makanan bagi konsumen.",
  "Produsen seperti alga dan tumbuhan air membentuk fondasi setiap jaring makanan air.",
  "Menghasilkan oksigen untuk fotosintesis",
  "Menghasilkan serbuk sari untuk bunga",
  "Sifat memandu bagaimana bahan digunakan.",
  "Sifat memandu pilihan bahan.",
  "Melindungi hanya gigi",
  "Melindungi tubuh dan membantu merasakan sentuhan",
  "Melindungi luka saat sembuh",
  "Lindungi telingamu di tempat yang bising.",
  "Melindungi dan menggunakan sumber daya alam dengan hati-hati",
  "Melindungi lebah membantu ekosistem.",
  "Melindungi telinga membantu melindungi pendengaran.",
  "Melindungi mata dari ketegangan dan silau terang membantu menjaga penglihatan nyaman dan lebih aman.",
  "Melindungi hutan membantu keanekaragaman hayati.",
  "Melindungi habitat dan spesies asli mendukung keanekaragaman hayati taman.",
  "Melindungi habitat membantu melindungi keanekaragaman hayati.",
  "Melindungi habitat membantu melindungi satwa liar.",
  "Melindungi habitat membantu satwa liar bertahan hidup.",
  "Melindungi habitat melindungi keanekaragaman hayati.",
  "Melindungi habitat melindungi banyak spesies sekaligus.",
  "Melindungi habitat melindungi banyak spesies.",
  "Melindungi lahan menghilangkan semua makhluk hidup",
  "Melindungi lahan menghilangkan semua tumbuhan",
  "Melindungi alam adalah tanggung jawab bersama.",
  "Melindungi alam, hewan, dan tumbuhan",
  "Melindungi laut melindungi satwa liar.",
  "Melindungi habitat penyerbuk itu penting.",
  "Melindungi spesies membantu mencegah kepunahan.",
  "Melindungi tubuh dan membantu mengendalikan suhu",
  "Melindungi lingkungan membantu menjaga alam sehat agar orang dapat menghirup udara bersih, minum air bersih, dan hidup di dunia yang lebih bersih.",
  "Melindungi lingkungan mencakup mengurangi limbah, mendaur ulang, dan menghemat sumber daya.",
  "Perlindungan biasanya tidak diperlukan",
  "Perlindungan, membantu mengendalikan suhu, dan merasakan lingkungan sekitar",
  "Peralatan pelindung dan prosedur mengurangi risiko.",
  "Protein, karbohidrat, lemak, vitamin, dan mineral masing-masing berperan. Makan seimbang mendukung fungsi tubuh.",
  "Membuktikan setiap hipotesis benar secara otomatis",
  "Menyediakan energi dan bahan untuk pertumbuhan dan perbaikan",
  "Cabut setiap tanaman yang kamu lihat.",
  "Denyut hanya bergantung pada suhu ruangan, bukan otot",
  "Denyut tidak punya kaitan dengan jantung",
  "Denyut adalah tanda detak jantung.",
  "Denyut adalah cara merasakan detak jantung.",
  "Denyut adalah jendela ke aktivitas jantung. Denyut dapat menunjukkan istirahat, respons olahraga, atau kemungkinan masalah kesehatan.",
  "Denyut selalu sama tidak peduli aktivitasnya",
  "Denyut terkait dengan aktivitas jantung.",
  "Denyut adalah denyutan darah dari jantung.",
  "Denyut tidak pernah berubah",
  "Titik denyut termasuk pergelangan tangan dan leher.",
  "Laju denyut adalah petunjuk aktivitas yang berguna.",
  "Laju denyut adalah pengamatan kesehatan yang berguna.",
  "Laju denyut sesuai dengan detak jantung. Olahraga, kegembiraan, atau demam dapat meningkatkan seberapa sering jantung berdetak.",
  "Laju denyut naik saat olahraga dan perasaan kuat.",
  "Memompa udara ke telinga",
  "Memompa udara ke paru-paru",
  "Hanya memompa udara keluar dari paru-paru",
  "Memompa darah sebagai ganti jantung",
  "Memompa darah melalui daun",
  "Memompa darah melalui sistem peredaran darah",
  "Memompa darah ke jantung hewan",
  "Hanya memompa darah ke kaki",
  "Memompa darah ke paru-paru",
  "Memompa darah ke jari kaki",
  "Memompa darah tanpa jantung",
  "Memompa oksigen ke paru-paru",
  "Memompa oksigen langsung ke telinga",
  "Memompa oksigen langsung ke paru-paru",
  "Memompa udara ke bulu",
  "Hanya memompa darah melalui paru-paru",
  "Memompa air tanah atau mengubah aliran dapat mengurangi pengisian ulang akuifer yang memberi makan mata air",
  "Memompa getah seperti jantung hewan",
  "Batu basal murni tanpa pengolahan",
  "Emas murni yang menempel kuat pada magnet permanen",
  "Batu kapur murni tanpa senyawa organik",
  "Batu pasir murni tanpa sisa makhluk hidup",
  "Besi yang dimurnikan yang tidak pernah merespons magnet",
  "Letakkan permen di dahimu.",
  "Masukkan ke tempat sampah atau wadah daur ulang yang tepat",
  "Susun tahapan siklus air berurutan dari pertama sampai terakhir:",
  "Memasukkannya ke freezer yang lebih dingin",
  "Memasukkan kertas dan oli bekas ke kantong sampah yang sama tanpa memilah",
  "Membuang sampah ke tempat sampah, bukan ke jalan",
  "Membuang sampah ke tempat sampah—bukan ke jalan—membantu menjaga tempat tetap bersih dan nyaman.",
  "Pertanyaan menentukan apakah kamu hanya mengamati atau juga bereksperimen.",
  "Tindakan cepat tanpa urutan atau perbandingan",
  "Berhenti belajar Sains selamanya.",
  "Kelinci adalah herbivora. Gigi dan sistem pencernaannya cocok untuk makanan tumbuhan.",
  "Kelinci adalah herbivora. Apa artinya itu?",
  "Geometri radiasi dan anggaran energi sepanjang tahun menentukan berapa banyak energi yang mencapai setiap satuan luas — fondasi untuk sabuk iklim.",
  "Hujan selalu mencuci semua pencemaran sebelum dapat membahayakan makhluk hidup apa pun",
  "Hujan menjadi berbahaya bagi tumbuhan",
  "Hujan menjadi tidak diperlukan",
  "Hujan membawa air tawar ke tanah, yang dibutuhkan tumbuhan dan hewan untuk bertahan hidup.",
  "Awan hujan menutupi Matahari dan membuat semuanya gelap.",
  "Awan hujan menjauh agar sinar matahari lewat.",
  "Hujan hanya berasal dari tumbuhan tanpa penguapan",
  "Hujan hanya berasal dari pipa bawah tanah",
  "Hujan jatuh ke laut tanpa penguapan kembali ke udara",
  "Hujan adalah tahap penting dalam siklus air.",
  "Hujan adalah bagian penting dari siklus air. Hujan membawa air tawar ke daratan, mengisi sungai, danau, dan tanah agar tumbuhan, hewan, dan manusia dapat menggunakannya.",
  "Hujan adalah air yang naik ke atas dari tanah ke awan.",
  "Hujan adalah penyebab panas bergerak ke atas ke langit.",
  "Hujan membuat tanah lebih keras dan mencegah air mencapai akar tumbuhan.",
  "Hujan tidak pernah memindahkan tanah",
  "Hujan tidak pernah mencapai sungai di kota",
  "Hujan hanya membuat genangan di permukaan dan tidak punya tujuan lain.",
  "Hujan berhenti turun selamanya",
  "Hujan yang selalu mencuci kotoran tanpa sisa",
  "Air hujan hanya terbentuk dari salju dan es yang mencair di gunung dingin.",
  "Perilaku acak tanpa kaitan dengan lingkungan",
  "Kesalahan acak dapat muncul dalam satu uji coba.",
  "Kesalahan acak dapat terjadi.",
  "Spesies langka hanya makan beton, jadi lebih banyak jalan lebih baik",
  "Data mentah mendukung transparansi.",
  "Catatan mentah membiarkanmu memeriksa apakah penafsiran sesuai dengan fakta. Catatan itu juga mendukung tinjauan orang lain dan pemeriksaan sendiri.",
  "Laju reaksi dan ekspansi gas bergantung pada suhu, yang dapat mengacaukan efek cuka",
  "Baca skala dengan hati-hati setinggi mata.",
  "Baca langkah-langkahnya, kumpulkan bahan, dan ikuti aturan keselamatan.",
  "Membaca sumber primer tetap membutuhkan pemikiran kritis kamu sendiri.",
  "Periksa ulang pengukuran dan cari kesalahan",
  "Catat massa dengan satuan seperti gram.",
  "Catat suhu dengan satuan yang benar, seperti °F atau °C.",
  "Catat apa yang terjadi dan ukur lagi dengan hati-hati.",
  "Mencatat data sambil berjalan berarti kamu punya informasi akurat dan terperinci untuk dilihat kembali. Tanpa pengamatan tertulis, mudah lupa atau salah ingat apa yang terjadi. Catatan yang baik membiarkanmu menemukan pola, membandingkan hasil, serta mendukung atau menantang hipotesismu dengan bukti nyata.",
  "Pencatatan menjaga jejak yang jelas tentang apa yang terjadi dalam penyelidikan.",
  "Mencatat pengamatan dan pengukuran membiarkanmu memeriksa pekerjaanmu dan membandingkan hasil nanti.",
  "Mencatat suhu di jurnal",
  "Pemulihan adalah bagian dari menjaga kesehatan.",
  "Daur ulang, hemat air dan listrik, serta hindari membuang sampah sembarangan di luar",
  "Daur ulang, hemat air, dan kurangi jumlah limbah yang kamu hasilkan.",
  "Daur ulang selalu memakai lebih banyak energi daripada membuat kertas baru, jadi sia-sia",
  "Daur ulang dapat menghemat bahan dan mengurangi pembuangan, terutama jika digabung dengan mengurangi dan memakai kembali.",
  "Daur ulang dapat menghemat sumber daya dan mengurangi limbah di tempat pembuangan.",
  "Mendaur ulang elektronik itu penting.",
  "Daur ulang membantu memakai kembali bahan dan mengurangi limbah",
  "Daur ulang adalah salah satu cara merawat lingkungan.",
  "Daur ulang menjaga bahan tetap dipakai lebih lama dan dapat mengurangi pencemaran serta sampah di tempat pembuangan.",
  "Daur ulang menjaga bahan berguna tetap dipakai dan dapat mengurangi sampah yang merusak lingkungan.",
  "Daur ulang memungkinkan bahan berguna dibuat menjadi produk baru.",
  "Daur ulang membuat sampah bertambah lebih cepat",
  "Daur ulang berarti mengumpulkan bahan bekas agar dapat dibuat menjadi produk baru.",
  "Daur ulang berarti memakai bahan lama lagi untuk membuat produk baru alih-alih membuangnya.",
  "Mendaur ulang kertas memakai kembali serat sehingga lebih sedikit sumber daya baru mungkin dibutuhkan dan lebih sedikit sampah menumpuk.",
  "Mendaur ulang kertas, plastik, dan kaca di tempat yang tepat",
  "Daur ulang mengurangi limbah, menghemat bahan mentah, dan membantu melindungi lingkungan.",
  "Daur ulang menghilangkan semua oksigen dari udara",
  "Daur ulang menghemat sumber daya dan membantu mengurangi pencemaran.",
  "Daur ulang mengubah taman menjadi gurun",
  "Daur ulang mengubah bahan bekas menjadi produk baru alih-alih mengirimkannya ke tempat pembuangan. Mengurangi limbah berarti membeli dan memakai lebih sedikit sejak awal. Menjaga bahan kimia dan sampah keluar dari air melindungi ekosistem. Bersama-sama, tindakan ini menurunkan pencemaran dan menghemat sumber daya alam.",
  "Daur ulang mengubah bahan bekas menjadi produk baru, menghemat energi dan sumber daya.",
  "Daur ulang mengubah bahan bekas seperti plastik, kertas, dan kaca menjadi produk baru alih-alih membuangnya.",
  "Daur ulang bekerja paling baik saat bahan dipilah dengan benar.",
  "Daur ulang, mengurangi limbah, dan menghindari pencemaran air.",
  "Sel darah merah membantu membawa oksigen.",
  "Kurangi dan pakai kembali juga kebiasaan yang membantu.",
  "Kurangi dan pakai kembali tetap didahulukan.",
  "Kurangi datang sebelum daur ulang.",
  "Kurangi datang sebelum pakai kembali, dan pakai kembali datang sebelum daur ulang.",
  "Kurangi, pakai kembali, dan daur ulang membantu planet.",
  "Kurangi, pakai kembali, atau kirim bahan ke daur ulang.",
  "Mengurangi pencemaran udara membantu orang dan alam.",
  "Mengurangi memotong permintaan dan limbah sebelum terjadi; daur ulang menangani limbah setelah dibuat",
  "Mengurangi seberapa banyak yang kita pakai adalah cara paling efektif untuk membantu lingkungan.",
  "Mengurangi hanya berarti membuang lebih sedikit tanpa mengubah produksi",
  "Mengurangi pencemaran membantu komunitas.",
  "Mengurangi limbah menjaga lingkungan tetap bersih dan sehat.",
  "Mengurangi limbah dimulai sebelum daur ulang.",
  "Mengurangi, memakai kembali, dan mendaur ulang bahan membantu melindungi lingkungan dengan menciptakan lebih sedikit limbah dan menghemat sumber daya alam.",
  "Pemantulan dan penyerapan bersama membentuk anggaran energi Bumi.",
  "Refleks dapat bertindak sangat cepat.",
  "Refleks terjadi cepat untuk melindungi tubuh, sering sebelum kamu memikirkannya.",
  "Refleks membantu menjagamu lebih aman.",
  "Aktivitas teratur membuat jantung lebih kuat sehingga dapat memompa darah lebih efektif.",
  "Makan teratur mendukung kebiasaan sehat.",
  "Makan teratur dan seimbang membantu menjaga energi lebih stabil sepanjang hari.",
  "Keandalan tumbuh dari data berulang dan pemeriksaan kesalahan yang cermat.",
  "Keandalan tumbuh dengan pengulangan yang cermat.",
  "Data andal memungkinkan menarik kesimpulan yang dapat dipercaya dan berbagi temuan dengan orang lain.",
  "Hasil andal dapat diulang dalam kondisi yang mirip.",
  "Jumlah air yang tersisa adalah hasil terikat; panas, lokasi, atau penutup adalah faktor yang kamu ubah",
  "Lepaskan label dari botol bahan kimia untuk bersenang-senang.",
  "Menghilangkan kebutuhan akan habitat yang bersih",
  "Menghilangkan pohon yang hewan dan tanah bergantung padanya",
  "Menghilangkan asam laktat dengan menghentikan pernapasan",
  "Menghilangkan satuan dari semua data",
  "Menghilangkan semua air",
  "Menghilangkan semua tumbuhan",
  "Menghilangkan setiap tanaman untuk membuat beton datar",
  "Menghilangkan tumbuhan memengaruhi seluruh rantai.",
  "Menghilangkan pelarut sepenuhnya",
  "Mengeluarkan limbah dan air berlebih dari darah",
  "Energi terbarukan tidak pernah membuat listrik",
  "Energi terbarukan mengurangi emisi bahan bakar fosil, tetapi tetap membutuhkan infrastruktur, bahan, dan penanganan akhir masa pakai. Pandangan siklus hidup penuh itu penting.",
  "Mengulang pengukuran mengurangi kesalahan acak.",
  "Mengulang pengukuran dapat mengungkapkan kesalahan.",
  "Mengulang pengukuran membantu menangkap kesalahan dan menegaskan bahwa hasilnya andal. Jika kedua pengukuran memberi jawaban yang sama, kamu bisa lebih yakin itu benar. Jika berbeda, kamu tahu ada yang mungkin salah dan kamu dapat mengukur lagi.",
  "Mengulang tes membantu menegaskan bahwa hasil bukan kecelakaan sekali saja.",
  "Mengulang tes membantu menunjukkan apakah hasil terjadi lagi dan bukan hanya kebetulan beruntung.",
  "Mengulang uji coba dapat menegaskan atau memperbaiki hasil.",
  "Mengulang selalu menghapus hasil percobaan pertama",
  "Mengulang menghapus kebutuhan akan data apa pun.",
  "Mengulang membantu memeriksa apakah hasil andal.",
  "Mengulang meningkatkan keandalan dan membantu menunjukkan seberapa banyak hasil bervariasi.",
  "Mengulang membuat aturan keselamatan tidak diperlukan.",
  "Mengulang mengurangi kesalahan acak.",
  "Mengulang mengurangi ketidakpastian.",
  "Mengulang uji coba membantu menunjukkan apakah temuan andal.",
  "Mengulang uji coba melanggar aturan laboratorium.",
  "Mengulang uji coba mengurangi peluang kesalahan sekali saja.",
  "Mengulang mengubah pendapat menjadi mantra sihir.",
  "Pengulangan selalu tidak diperlukan jika hasil terlihat bagus",
  "Pengulangan dapat mengungkapkan kesalahan.",
  "Pengulangan mengubah tujuan asli tanpa alasan",
  "Pengulangan membantu mengungkapkan sebaran dan kesalahan pengukuran",
];

if (id.length !== en.length) {
  console.error(`Length mismatch: en=${en.length} id=${id.length}`);
  process.exit(1);
}

const map = Object.fromEntries(en.map((k, i) => [k, id[i]]));
fs.writeFileSync(path.join(__dirname, "map-chunk-18.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("wrote map-chunk-18.json keys=", Object.keys(map).length);
