import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(__dirname, "strings-chunk-19.json"), "utf8"));

const id = [
  "Pengulangan mengungkapkan konsistensi. Data pencilan menjadi lebih jelas, dan tren rata-rata lebih dapat dipercaya.",
  "Ganti sinar matahari dengan sinar senter",
  "Menggantikan tugas jantung",
  "Menggantikan kebutuhan akan pengamatan apa pun",
  "Menggantikan kebutuhan oksigen sepenuhnya",
  "Menggantikan kebutuhan mencuci tangan",
  "Mengganti otak saat tidur",
  "Replikasi selalu mengubah pertanyaan asli",
  "Replikasi membangun keyakinan. Jika pola muncul lagi, lebih kecil kemungkinannya hanya kebetulan beruntung.",
  "Replikasi memeriksa keandalan. Jika orang lain—atau kamu—dapat mengulang metode dan menemukan hasil yang mirip, keyakinan tumbuh.",
  "Replikasi adalah gagasan inti dalam Sains. Tanpa protokol, temuan tetap cerita pribadi alih-alih pengetahuan bersama.",
  "Replikasi tidak diperlukan jika hanya kesimpulan yang ditulis",
  "Replikasi berarti orang lain dapat memperoleh hasil yang mirip, yang membangun keyakinan pada temuan.",
  "Laporkan semua uji coba yang jujur, bukan hanya yang favorit.",
  "Melapor sekali setahun sudah cukup, tidak peduli anginnya",
  "Reproduksi melanjutkan siklus hidup untuk generasi berikutnya.",
  "Reproduksi—membantu tumbuhan membuat biji",
  "Aktivitas reptil dapat melambat di cuaca dingin.",
  "Reptil adalah hewan berdarah dingin yang tertutup kulit kering bersisik. Sisik membantu melindungi mereka dan mengurangi kehilangan air dari tubuh.",
  "Reptil tertutup kulit kering bersisik yang melindungi tubuh dan mengurangi kehilangan air. Tidak seperti mamalia, reptil berdarah dingin dan bergantung pada lingkungan untuk kehangatan.",
  "Reptil memiliki kulit kering bersisik yang membantu melindungi tubuh dan menghemat air.",
  "Reptil memiliki bulu tebal yang menjaga mereka tetap hangat di cuaca dingin.",
  "Reptil mencakup ular, kadal, kura-kura, dan buaya.",
  "Reptil menjaga suhu tubuh tetap hangat dari dalam, sama seperti manusia.",
  "Reptil hanya hidup di air dan bernapas melalui insang.",
  "Reptil sering berjemur di tempat hangat.",
  "Reptil biasanya memiliki kulit kering dengan sisik.",
  "Peneliti terus mempelajarinya.",
  "Cagar alam membantu melindungi spesies hewan dan tumbuhan.",
  "Resolusi dan akurasi adalah gagasan yang berbeda.",
  "Batas sumber daya, toksisitas pada jumlah tinggi, dan efisiensi yang berubah berarti kurva pertumbuhan sering bukan garis lurus sederhana.",
  "Pengelolaan sumber daya membutuhkan aturan, pemantauan, dan dukungan komunitas.",
  "Hormati makhluk hidup di luar ruangan.",
  "Hormati satwa liar dan rumah mereka.",
  "Pengunjung yang hormat melindungi habitat agar orang lain dan satwa liar juga dapat menikmatinya.",
  "Sistem pernapasan dan peredaran darah bekerja sama.",
  "Kesehatan pernapasan memengaruhi energi dan daya tahan.",
  "Istirahat dan cairan membantu tubuhmu pulih. Tangan bersih membantu menghentikan kuman menyebar.",
  "Istirahat dan tidur memberi tubuhmu waktu pulih agar kamu merasa siap lagi.",
  "Istirahat membantu otot pulih setelah aktivitas.",
  "Istirahat membantu tubuh dan otak.",
  "Istirahat membantu tubuh memulihkan energi",
  "Istirahat adalah bagian dari gaya hidup sehat.",
  "Istirahat secara permanen menghentikan pernapasan",
  "Istirahat menghilangkan kebutuhan akan air",
  "Istirahat mendukung tubuh dan pikiran yang sehat.",
  "Istirahat mendukung fokus dan kesehatan.",
  "Istirahat mengubah otot menjadi batu",
  "Istirahat, minum cairan, dan jaga tangan tetap bersih",
  "Istirahat menurunkan detak jantung kembali.",
  "Istirahat menurunkan denyut kembali.",
  "Laju istirahat biasanya lebih rendah daripada laju olahraga.",
  "Hasil dapat mendukung atau tidak mendukung hipotesis.",
  "Hasil mungkin mendukung atau tidak mendukung hipotesis.",
  "Hasil mungkin mendukung atau menolaknya.",
  "Hasil yang tidak 100% selalu salah dan harus diabaikan.",
  "Barang yang dapat dipakai ulang dapat dipakai berulang kali, seperti botol kaca. Barang sekali pakai dimaksudkan untuk satu kali pakai, seperti kantong plastik sekali pakai.",
  "Barang yang dapat dipakai ulang mengurangi kebutuhan plastik sekali buang.",
  "Barang yang dapat dipakai ulang mengurangi sampah di sekolah.",
  "Bahan yang dapat dipakai ulang dapat dipakai lagi; yang sekali pakai dimaksudkan untuk satu kali pakai",
  "Bahan yang dapat dipakai ulang harus selalu buatan dan menjadi berbahaya lebih cepat",
  "Pakai kembali dan daur ulang bahan alih-alih membuangnya",
  "Memakai kembali dan mendaur ulang bahan mengurangi limbah dan membantu melindungi lingkungan dengan menjaga barang berbahaya keluar dari tempat pembuangan dan saluran air.",
  "Peninjau memeriksa metode, konsistensi, dan relevansi sebelum penerimaan",
  "Peninjau menjamin setiap kesimpulan 100% benar sebelum percobaan apa pun",
  "Revisi kesimpulan agar sesuai dengan bukti.",
  "Revisi pemikiran saat bukti tidak cocok.",
  "Batu",
  "Batu selalu tetap menjadi fosil selamanya tanpa perubahan",
  "Batu-batu",
  "Batu larut menjadi oksigen murni",
  "Batu melompat ke awan",
  "Batu mencatat sejarah proses masa lalu.",
  "Batu yang hanya memakai kegelapan",
  "Suhu ruangan dan aliran udara di sekitar es",
  "Ayam jantan",
  "Rambut akar meningkatkan penyerapan air.",
  "Sistem akar dapat dangkal atau dalam.",
  "Akar menyerap air dan mineral dari tanah serta menambatkan tumbuhan di tempatnya.",
  "Akar menyerap air dan zat gizi dari tanah untuk memberi makan tumbuhan.",
  "Akar menyerap air dan zat gizi dari tanah. Zat itu bergerak ke atas melalui batang dan ke seluruh tumbuhan, mendukung pertumbuhannya.",
  "Akar menambatkan tumbuhan di tanah dan menyerap air serta zat gizi yang dibutuhkan untuk tumbuh.",
  "Akar menambatkan tumbuhan di tanah dan menyerap air serta zat gizi yang dibutuhkan tumbuhan untuk tumbuh. Zat itu naik melalui batang ke seluruh tumbuhan.",
  "Akar dan struktur tanah mendukung penyaringan mekanis dan sebagian penyerapan kimia",
  "Akar adalah sistem pengambilan bawah tanah tumbuhan. Air dan mineral masuk di sini dan bergerak ke atas.",
  "Akar adalah tempat hewan menemukan perlindungan saat cuaca dingin.",
  "Akar mengikat partikel tanah bersama-sama.",
  "Akar bisa terlalu basah dan tumbuhan mungkin menjadi tidak sehat",
  "Akar bisa terlalu basah dan tumbuhan mungkin sakit atau mati.",
  "Akar dapat membantu menstabilkan tanah seiring waktu saat penanaman direncanakan dengan hati-hati",
  "Akar menangkap sinar matahari dan menyimpannya untuk dipakai tumbuhan.",
  "Akar menangkap sinar matahari untuk semua bagian tumbuhan.",
  "Akar tumbuh ke bawah ke dalam tanah.",
  "Akar tumbuh ke bawah ke dalam tanah.",
  "Akar tumbuh di tanah di bagian bawah tumbuhan.",
  "Akar tumbuh di tanah. Akar menahan tumbuhan di tempatnya dan mengambil air serta mineral.",
  "Akar tumbuh di tanah. Akar menyerap air dan zat gizi serta menjaga tumbuhan agar tidak roboh.",
  "Akar tumbuh di bawah tanah dan menyerap air serta mineral terlarut dari tanah. Air lalu naik melalui batang untuk mencapai daun dan bagian lain tumbuhan. Tanpa akar mengambil air, tumbuhan akan mengering dan mati.",
  "Akar tumbuh di bawah tanah dan menambatkan tumbuhan di tanah.",
  "Akar membantu daun bernapas dengan menyaring udara dari tanah.",
  "Akar membantu tumbuhan mendapat air dari tanah.",
  "Akar membantu tumbuhan mendapat air dan mineral.",
  "Akar membantu tumbuhan berdiri kokoh.",
  "Akar membutuhkan oksigen untuk respirasi seluler.",
  "Akar membutuhkan sedikit udara di tanah. Banjir terus-menerus dapat menyakiti akar dan seluruh tumbuhan.",
  "Akar terbuka untuk melepaskan biji saat bunga mekar.",
  "Akar melepaskan biji ke tanah sekitar.",
  "Akar berhenti bekerja jika orang berjalan di dekatnya",
  "Akar mengambil air dari tanah.",
  "Akar mengambil air dari tanah dan mengirimkannya ke atas ke daun.",
  "Akar mengambil air dari tanah.",
  "Akar yang tumbuh ke dalam tanah",
  "Akar di bawah tanah",
  "Akar biasanya tumbuh di bawah tanah dan mengambil air.",
  "Akar, biasanya",
  "Permukaan kasar punya tonjolan atau tekstur yang bisa kamu rasakan, dan sering lebih mencengkeram daripada permukaan licin.",
  "Membulatkan ke apa pun yang terlihat paling bagus",
  "Gosok kotoran ke matamu setiap pagi",
  "Gosok kotoran ke hidungmu",
  "Penggaris mengukur jarak atau panjang. Alat lain mengukur besaran berbeda seperti waktu, massa, atau suhu.",
  "Aturan dan peralatan pelindung mencegah cedera. Mendengarkan dengan hati-hati menjaga semua orang lebih aman selama penyelidikan.",
  "Lari cepat tanpa minum",
  "Lari dengan peralatan kaca untuk uji kecepatan.",
  "Lari dengan pisau untuk bersenang-senang",
  "Berlari lebih cepat di musim dingin agar tetap hangat",
  "Berlari meningkatkan penggunaan energi. Napas lebih cepat dan dalam membantu bertukar gas agar otot tetap bekerja.",
  "Berlari menggantikan pernapasan selamanya.",
  "Berlari memakai banyak energi. Jantungmu berdetak lebih cepat agar darah dapat membawa lebih banyak oksigen ke otot yang bekerja.",
  "Aliran permukaan tidak punya kaitan dengan kualitas air",
  "Aliran permukaan meningkat di tanah beraspal.",
  "Olahraga aman mencakup waktu pemanasan dan pendinginan.",
  "Pengamatan Matahari yang aman membutuhkan alat khusus.",
  "Keselamatan datang sebelum tindakan percobaan apa pun.",
  "Keselamatan didahulukan dalam setiap penyelidikan.",
  "Keselamatan didahulukan.",
  "Tanda tangan kontrak keselamatan",
  "Peralatan keselamatan membantu mencegah cedera.",
  "Peralatan keselamatan mengurangi risiko selama olahraga.",
  "Jenis kacamata pelindung",
  "Kacamata pelindung melindungi matamu dari percikan, bahan kimia berbahaya, dan partikel terbang yang mungkin terjadi selama percobaan.",
  "Keselamatan tidak punya kaitan dengan pilihan bahan",
  "Keselamatan adalah bagian dari persiapan.",
  "Keselamatan adalah bagian dari praktik ilmiah.",
  "Keselamatan adalah aturan paling penting.",
  "Keselamatan sangat penting dalam percobaan.",
  "Keselamatan penting dalam perawatan Sains sehari-hari.",
  "Keselamatan penting saat menguji bahan listrik.",
  "Aturan keselamatan dan bantuan orang dewasa mencegah cedera",
  "Aturan keselamatan hanya berlaku untuk murid yang lebih tua di kelas Sains tingkat lanjut.",
  "Aturan keselamatan bersifat opsional selama guru mengawasi.",
  "Aturan keselamatan menyembunyikan semua hasil",
  "Aturan keselamatan melindungi orang di rumah.",
  "Aturan keselamatan melindungi murid.",
  "Aturan keselamatan mengurangi bahaya dari tumpahan, panas, alat tajam, dan risiko laboratorium lainnya.",
  "Air liur membantu memecah makanan dan membuat menelan lebih mudah.",
  "Air liur bercampur dengan makanan saat kamu mengunyah.",
  "Air liur membasahi makanan dan mengandung zat yang mulai memecah sebagian makanan.",
  "Garam — larut dan tercampur sepenuhnya ke dalam air.",
  "Garam selalu membatalkan pemanasan",
  "Garam larut dalam air, artinya pecah menjadi partikel yang menyebar merata. Pasir dan minyak tidak larut dalam air.",
  "Air asin dan teduh dalam untuk tumbuh dengan baik",
  "Air asin dapat membuat mengapung terasa lebih mudah.",
  "Kondisi yang sama mendukung uji yang adil.",
  "Ukuran sampel dan pengulangan penting.",
  "Bias pengambilan sampel adalah jebakan penelitian yang umum.",
  "Pengambilan sampel di satu tempat dan waktu mencapai kelompok terbatas. Klaim tentang “semua orang” membutuhkan rencana pengambilan sampel yang lebih luas atau pernyataan batas yang jelas.",
  "Pengambilan sampel menghemat waktu dan sumber daya.",
  "Pasir — pecah menjadi potongan kecil yang tercampur secara permanen ke dalam air.",
  "Pasir dan cuaca beku dingin untuk bertahan hidup",
  "Pasir menciptakan hujan tropis setiap jam",
  "Pasir tidak larut dalam air. Penyaringan dapat menangkap pasir sementara air lewat.",
  "Pasir lebih padat daripada air dan mengendap.",
  "Batu pasir dan batu kapur adalah batuan sedimen yang umum.",
  "Menghemat air dan menghemat sinar matahari adalah hal yang sama persis",
  "Menghemat air penting di habitat kering.",
  "Skala dan waktu penting saat mengenali efek arah.",
  "Sisik dan tubuh panjang kurus saja",
  "Sisik yang menutupi seluruh tubuh",
  "Menakut-nakuti semua sinar matahari",
  "Data sekolah menunjukkan skor rata-rata di Cabang A lebih tinggi daripada Cabang B secara keseluruhan, meskipun di setiap kelas terpisah rata-rata Cabang A lebih rendah. Bagaimana itu mungkin?",
  "Sains memungkinkan kesimpulan tegas setelah satu kali coba saja",
  "Sains menjadi lebih kuat saat hasil dapat diulang.",
  "Sains bergantung pada komunikasi yang jelas.",
  "Sains bergantung pada bukti yang dapat kamu tinjau.",
  "Sains bergantung pada pencatatan dan peninjauan data.",
  "Sains bergantung pada pemeriksaan kritis yang berulang.",
  "Sains bergantung pada hasil yang dapat diuji tim lain.",
  "Percobaan Sains dapat melibatkan bahan kimia yang mengiritasi kulit atau mata, peralatan panas yang menyebabkan luka bakar, atau alat tajam yang menyebabkan sayatan. Aturan keselamatan — seperti memakai kacamata pelindung, memakai peralatan dengan hati-hati, dan mengikuti petunjuk guru — melindungi semua orang di kelas agar tidak terluka.",
  "Sains dibangun di atas pertanyaan, pengamatan, dan percobaan.",
  "Sains kadang-kadang menyenangkan.",
  "Sains tidak pernah memakai lebih dari satu pengukuran.",
  "Keselamatan Sains melindungi tubuhmu.",
  "Sains biasanya dimulai dengan pertanyaan dan tebakan, lalu tes yang cermat dan catatan tentang apa yang terjadi.",
  "Sains menghargai hasil yang dapat diulang.",
  "Kesimpulan ilmiah mengutip bukti. Kesimpulan menggambarkan apa yang ditunjukkan data, bukan hanya keinginan atau keberuntungan yang tidak terkait.",
  "Pengetahuan ilmiah tumbuh melalui tinjauan kritis komunitas.",
  "Pengetahuan ilmiah harus bersifat publik dan dapat diuji.",
  "Hukum ilmiah didasarkan pada banyak percobaan dan pengamatan yang diulang.",
  "Hukum ilmiah merangkum pola yang teruji dengan baik; hukum tidak sama dengan hipotesis awal.",
  "Pertanyaan ilmiah adalah pertanyaan yang dapat kamu uji dengan pengukuran. Pertanyaan tentang keindahan dan opini murni bukan sasaran percobaan yang adil.",
  "Ilmuwan selalu mencocokkan alat ukur dengan besaran yang diukur: termometer untuk suhu, penggaris untuk panjang, neraca untuk massa, gelas ukur untuk volume cairan.",
  "Ilmuwan memilih alat yang sesuai dengan apa yang ingin mereka ukur.",
  "Ilmuwan membandingkan sifat dengan tes sederhana.",
  "Ilmuwan mengendalikan variabel saat mempelajari pelarutan.",
  "Ilmuwan mengoreksi bias dan membandingkan jaringan yang berbeda dengan hati-hati. Kehati-hatian metode adalah tentang akurasi, bukan “ragu demi ragu sendiri.”",
  "Ilmuwan mengharapkan dan memeriksa kesalahan.",
  "Ilmuwan mengelompokkan hewan berdasarkan ciri bersama seperti penutup tubuh (bulu, sisik, bulu burung), jumlah kaki, dan cara bergerak (berenang, terbang, berjalan).",
  "Ilmuwan menyimpan catatan prosedur dan data dengan cermat.",
  "Ilmuwan merencanakan sebelum menguji.",
  "Ilmuwan mencatat pengamatan dalam tabel, bagan, atau buku catatan selama percobaan.",
  "Ilmuwan mencatat apa yang mereka amati.",
  "Ilmuwan menulis hipotesis sebelum menguji gagasan.",
  "Hewan laut dapat mengira plastik sebagai makanan, yang membahayakan atau membunuh mereka.",
  "Iklim musiman dan kondisi setempat sama-sama penting.",
  "Pola iklim musiman bergabung dengan kelembapan laut dan panas kota setempat",
  "Warna bulu musiman yang cocok dengan salju membuat kelinci lebih sulit dilihat. Kamuflase meningkatkan peluang bertahan hidup.",
  "Lama siang musiman berubah dengan kemiringan dan orbit Bumi.",
  "Migrasi musiman suatu populasi tanpa perubahan genetik",
  "Pola hujan musiman membentuk pasokan air.",
  "Musim disebabkan oleh perubahan jauh di dalam inti Bumi yang melepaskan jumlah panas berbeda",
  "Musim hanya disebabkan oleh putaran harian pada sumbu Bumi",
  "Musim adalah bagian tahun dengan pola cuaca khas.",
  "Musim adalah hasil orbit Bumi digabung dengan kemiringannya.",
  "Musim mengubah sumber daya yang tersedia.",
  "Musim berubah karena kemiringan Bumi.",
  "Musim mengubah lama siang sepanjang tahun.",
  "Musim mengubah pola suhu.",
  "Musim mengikuti pola iklim tahunan.",
  "Musim terjadi hanya karena putaran harian pada sumbu",
  "Musim terkait dengan lama siang dan seberapa langsung sinar matahari mengenai suatu tempat sepanjang tahun.",
  "Musim terkait dengan sudut sinar matahari dan lama siang dalam model sederhana.",
  "Air laut mengalir langsung ke bawah tanah ke sungai.",
  "Air laut tetap permanen di laut dan tidak pernah bergerak atau berubah.",
  "Kerangka kedua di luar kulit",
  "Batuan sedimen terbentuk saat lapisan sedimen menumpuk dan mengeras seiring waktu.",
  "Sedimen dapat berasal dari batuan yang aus, cangkang, atau bahan lain.",
  "Melihat pola dan membandingkan hasil lebih mudah",
  "Lihat mana yang lebih mudah menggores yang lain",
  "Penyebaran biji memindahkan biji menjauh dari tumbuhan induk agar tumbuhan baru dapat tumbuh di tempat lain. Angin, air, dan hewan adalah cara umum biji berpindah.",
  "Penyebaran biji memindahkan biji menjauh dari tumbuhan induk.",
  "Penyebaran biji menyebarkan tumbuhan di suatu area.",
  "Hanya biji, akar, bunga, buah",
  "Biji berasal dari bunga.",
  "Biji mengandung awal tumbuhan baru. Dengan air, kehangatan, dan kondisi yang tepat, biji dapat berkecambah.",
  "Biji terbentuk setelah bunga diserbuki.",
  "Biji tumbuh menjadi tumbuhan baru.",
  "Biji memiliki lapisan pelindung.",
  "Biji menyimpan tumbuhan bayi dan cadangan makanan.",
  "Biji membutuhkan ruang, cahaya, air, dan zat gizi untuk tumbuh dengan baik.",
  "Biji membutuhkan air, kehangatan, dan kadang cahaya agar berhasil berkecambah.",
];

if (id.length !== en.length) {
  console.error(`Length mismatch: en=${en.length} id=${id.length}`);
  process.exit(1);
}

const map = Object.fromEntries(en.map((k, i) => [k, id[i]]));
fs.writeFileSync(path.join(__dirname, "map-chunk-19.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("wrote map-chunk-19.json keys=", Object.keys(map).length);
