import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(__dirname, "strings-chunk-17.json"), "utf8"));

const id = [
  "Oksigen dan zat gizi ke bagian tubuh",
  "Oksigen masuk ke darah di paru-paru.",
  "Oksigen masuk ke darah di paru-paru. Darah yang bersirkulasi lalu mengantarkan oksigen itu ke sel-sel di seluruh tubuh.",
  "Oksigen dari udara masuk ke darah di paru-paru.",
  "Oksigen membantu otot tetap bergerak.",
  "Oksigen membantu otot melepaskan energi dari zat gizi makanan.",
  "Oksigen membantu otot melepaskan energi dari zat gizi",
  "Oksigen membantu melepaskan energi dari zat gizi.",
  "Oksigen dicerna di usus besar terlebih dahulu.",
  "Oksigen dibutuhkan oleh sel-sel tubuh.",
  "Oksigen dibutuhkan baik dari udara maupun dari air.",
  "Oksigen hanya digunakan oleh folikel rambut.",
  "Oksigen membuat otot berhenti bergerak.",
  "Oksigen mengecat otot dengan warna baru",
  "Oksigen mengecat otot dengan warna baru",
  "Oksigen mencapai sel hanya melalui kelenjar keringat kulit.",
  "Oksigen mengganti tulang saat olahraga",
  "Oksigen menghentikan otot agar tidak pernah beristirahat",
  "Oksigen hanya berjalan melalui helai rambut.",
  "Oksigen hanya berjalan melalui rambut",
  "Oksigen mengubah otot menjadi tulang",
  "Oksigen mengubah otot menjadi tulang.",
  "Darah kaya oksigen memberi bahan bakar bagi sel yang aktif.",
  "Masukkan semuanya ke satu kantong tanpa memilah untuk menghemat ruang",
  "Mengemas sampah sampai kantong sobek sebelum memasukkannya ke tempat sampah",
  "Nyeri bisa menjadi sinyal dari tubuhmu.",
  "Nyeri tidak pernah dipelajari dalam Sains",
  "Nyeri yang tajam atau parah harus dilaporkan kepada orang dewasa.",
  "Mengecat batu tanpa meminta izin orang dewasa",
  "Kertas — menjadi lebih berat saat dipanaskan.",
  "Kertas menyerap zat tersebut, sehingga tampak menghilang lebih cepat.",
  "Kertas berasal dari bahan tumbuhan.",
  "Induk burung sering merawat anak di sarang.",
  "Perawatan induk umum pada mamalia.",
  "Induk sering memberi makan dan menjaga anak di sarang.",
  "Taman dan cagar alam membantu melindungi habitat.",
  "Taman perlu perawatan agar makhluk hidup dapat berkembang.",
  "Bagian ( ), bagian ( bones ) ( ).",
  "Kehati-hatian sebagian tanpa persiapan sebelumnya",
  "Partikel dan gas dapat mencapai ketinggian tinggi serta mengubah kualitas udara dan pola radiasi",
  "Bagian ujung akar tanaman",
  "Pola mendukung kesimpulan.",
  "Tinjauan sejawat selamanya menghalangi setiap peneliti untuk menerbitkan",
  "Tinjauan sejawat adalah langkah penyaringan dan perbaikan, bukan ramalan. Temuan masih bisa berubah setelah pengulangan kemudian, tetapi tinjauan mengurangi kesalahan yang jelas.",
  "Tinjauan sejawat menggantikan percobaan lapangan",
  "Manusia juga mamalia.",
  "Orang dapat membantu dengan mengurangi gangguan dan sampah.",
  "Orang dapat mendaur ulang, menghemat air dan listrik, menghindari membuang sampah sembarangan, serta menanam pohon dan tanaman.",
  "Manusia sama sekali tidak membutuhkan zat gizi.",
  "Orang berpakaian hangat untuk cuaca dingin.",
  "Manusia memiliki gigi pemotong, gigi taring, dan gigi geraham.",
  "Manusia memiliki lima indera utama yang membantu memahami dunia.",
  "Manusia memiliki dua ginjal.",
  "Manusia memiliki dua paru-paru—satu di kanan dan satu di kiri.",
  "Orang telah menggunakan kuda untuk berkuda dan bekerja.",
  "Orang berbagi tanggung jawab atas lingkungan.",
  "Orang harus membuang sampah dengan benar.",
  "Alat pelindung diri, seperti kacamata pelindung dan sarung tangan, dipakai untuk mengurangi risiko cedera.",
  "Pestisida hanya memengaruhi tanaman dan tidak pernah masuk ke hewan",
  "Kelopak dan nektar yang menarik serangga",
  "Hewan peliharaan adalah hewan yang didomestikasi.",
  "Fotosintesis juga melepaskan oksigen.",
  "Fotosintesis terjadi di kloroplas, terutama di daun.",
  "Fotosintesis terutama terjadi di daun hijau.",
  "Fotosintesis di sel hewan",
  "Fotosintesis adalah cara tumbuhan menggunakan sinar matahari, air, dan karbon dioksida untuk membuat gula dan melepaskan oksigen.",
  "Fotosintesis memungkinkan tumbuhan membuat makanan.",
  "Fotosintesis membuat gula; respirasi menggunakan gula itu untuk energi.",
  "Fotosintesis membutuhkan cahaya.",
  "Fotosintesis hanya terjadi di batang dan hanya pada malam hari.",
  "Fotosintesis menghasilkan makanan bagi tumbuhan dan melepaskan oksigen ke udara.",
  "Fotosintesis mendukung rantai makanan di sebagian besar ekosistem.",
  "Fotosintesis terutama terjadi di daun, tempat sel mengandung pigmen hijau yang disebut klorofil.",
  "Berfotosintesis sampai mereka tumbuh sayap",
  "Makanan berfotosintesis untuk otak",
  "Berfotosintesis di bawah es",
  "Aktivitas fisik dapat meningkatkan denyut nadi",
  "Aktivitas fisik mendukung kesehatan jangka panjang.",
  "Perubahan fisik mengubah bentuk atau wujud; perubahan kimia membuat bahan baru.",
  "Perubahan fisik selalu menciptakan unsur baru sama sekali",
  "Perubahan fisik sering dapat dibalik.",
  "Perubahan fisik tidak membuat jenis zat baru.",
  "Perubahan fisik menjaga identitas bahan.",
  "Memetik tanaman langka dari taman yang dilindungi.",
  "Memetik tanaman liar langka untuk dibawa pulang sebagai oleh-oleh",
  "Ambil sampah dan masukkan ke tempat sampah, jangan tinggalkan di rumput",
  "Mengambil sampah dan memakai tempat sampah mengurangi pencemaran serta membantu melindungi tumbuhan dan hewan.",
  "Pigmen memengaruhi warna tumbuhan.",
  "Menumpuk limbah selamanya di satu tempat tanpa daur ulang",
  "Rencanakan istirahat minum air di cuaca panas.",
  "Pesawat makan abu, jadi mereka berhenti terbang",
  "Planet tetap di orbitnya karena tarikan gravitasi Matahari.",
  "Planet adalah benda besar yang mengorbit Matahari. Mereka tidak menghasilkan cahaya sendiri seperti bintang — sebaliknya, mereka memantulkan sinar matahari. Bumi, Mars, dan Jupiter adalah contoh planet di tata surya kita.",
  "Planet yang bersinar tepat seperti bintang di malam hari",
  "Planet bergerak dalam orbit hampir lingkaran mengelilingi sebuah bintang.",
  "Perencanaan mencakup apa yang diuji dan bagaimana akan diukur.",
  "Perencanaan membantumu memilih bahan, langkah, variabel, dan aturan keselamatan sebelum kamu mulai.",
  "Perencanaan mencegah kebingungan.",
  "Perencanaan mencegah kesalahan.",
  "Rencana menghapus kebutuhan akan hipotesis",
  "Rencana membuat alat ukur tidak diperlukan",
  "Rencana menghentikan semua pengamatan",
  "Tutup tanaman dan akar yang menahan tanah",
  "Bagian tumbuhan bekerja sebagai satu sistem.",
  "Akar tumbuhan menyerap air dan zat gizi dari tanah.",
  "Akar tumbuhan membantu menahan tanah di tempatnya.",
  "Pemakan tumbuhan disebut herbivora.",
  "Pemakan tumbuhan membantu membentuk pertumbuhan tanaman di habitat.",
  "Menanam bibit untuk mengganti pohon yang telah ditebang.",
  "Tumbuhan (dan beberapa organisme lain) yang membuat makanan dengan energi cahaya",
  "Tumbuhan hanya menyerap air untuk menghasilkan semua energi yang mereka butuhkan.",
  "Tumbuhan selalu mengejar tumbuhan lain.",
  "Tumbuhan dan hewan memperoleh energi dengan cara berbeda.",
  "Tumbuhan dan akar membantu menahan karbon organik dalam jaringan hidup dan tanah",
  "Tumbuhan sangat penting: mereka menghasilkan oksigen yang kita hirup melalui fotosintesis dan menjadi dasar sebagian besar rantai makanan di Bumi.",
  "Tumbuhan penting hanya karena mereka melakukan fotosintesis di laboratorium Sains.",
  "Tumbuhan penting hanya karena mereka menyimpan makanan ekstra di bawah tanah.",
  "Tumbuhan adalah makhluk hidup yang punya kebutuhan.",
  "Tumbuhan tidak penting — hewan bisa bertahan tanpa mereka.",
  "Tumbuhan adalah bagian dari habitat. Mengambil terlalu banyak dapat merugikan satwa liar dan pertumbuhan di masa depan.",
  "Tumbuhan adalah produsen — mereka membuat makanan menggunakan sinar matahari, air, dan karbon dioksida.",
  "Tumbuhan adalah produsen. Hewan yang memakan tumbuhan, dan hewan yang memakan hewan itu, bergantung pada energi makanan tersebut.",
  "Tumbuhan adalah satu-satunya sumber makanan bagi setiap hewan di Bumi.",
  "Tumbuhan adalah produsen di dasar sebagian besar jaring makanan.",
  "Tumbuhan adalah awal banyak rantai makanan.",
  "Tumbuhan biasanya produsen karena mereka membuat makanan menggunakan sinar matahari.",
  "Tumbuhan membangun penghalang beton yang sepenuhnya memblokir aliran air",
  "Tumbuhan dapat membantu menahan tanah, tetapi keamanan lereng tetap membutuhkan perencanaan dan perawatan.",
  "Tumbuhan dapat merasakan lingkungannya.",
  "Tumbuhan menangkap sinar matahari dan menggunakannya untuk membuat makanan selama fotosintesis.",
  "Tumbuhan mendinginkan area setempat dengan teduh dan penguapan air.",
  "Tumbuhan bertukar gas dengan udara selama fotosintesis dan respirasi.",
  "Tumbuhan merasa lebih hangat dekat cahaya dan lebih suka tetap hangat.",
  "Tumbuhan tumbuh menuju cahaya karena membutuhkannya untuk fotosintesis dan membuat makanan. Perilaku ini disebut fototropisme.",
  "Tumbuhan memiliki jaringan tabung kecil yang disebut xilem yang membawa air dari akar ke atas melalui batang dan ke daun.",
  "Tumbuhan membutuhkan cahaya untuk membuat makanan melalui fotosintesis, jadi mereka tumbuh menuju cahaya.",
  "Tumbuhan membutuhkan cahaya untuk membuat makanan. Tanpa cahaya, mereka tidak dapat terus tumbuh dengan baik.",
  "Tumbuhan membutuhkan cahaya untuk memompa zat gizi melalui batang mereka.",
  "Tumbuhan membutuhkan sinar matahari untuk fotosintesis. Tanpa cahaya, tumbuhan tidak dapat tumbuh dengan baik.",
  "Tumbuhan membutuhkan sinar matahari untuk membuat makanan dan tumbuh. Mereka juga membutuhkan air, udara, dan zat gizi tanah.",
  "Tumbuhan membutuhkan jumlah air yang tepat—tidak terlalu sedikit dan tidak terlalu banyak.",
  "Tumbuhan membutuhkan jumlah air yang tepat—tidak terlalu sedikit atau terlalu banyak.",
  "Tumbuhan membutuhkan air dan sinar matahari untuk fotosintesis, proses yang mereka gunakan untuk membuat makanan sendiri dan tumbuh.",
  "Tumbuhan membutuhkan air, dan air hanya berasal dari cahaya.",
  "Tumbuhan membutuhkan air, cahaya, dan udara untuk tumbuh.",
  "Tumbuhan tidak pernah bertukar gas",
  "Tumbuhan secara permanen berhenti mengambil karbon dioksida",
  "Tumbuhan menghasilkan makanan yang dapat digunakan manusia dan hewan.",
  "Tumbuhan menghasilkan oksigen dan menyediakan makanan bagi hewan serta makhluk hidup lain.",
  "Tumbuhan melepaskan karbon dioksida dan mengambil oksigen untuk membuat energi.",
  "Tumbuhan melepaskan oksigen yang dibutuhkan hewan.",
  "Tumbuhan berespirasi pada malam dan siang hari",
  "Tumbuhan berespirasi hanya di siang hari dengan sinar matahari",
  "Tumbuhan berhenti membutuhkan sinar matahari",
  "Tumbuhan seperti rumput",
  "Tumbuhan seperti rumput, daun, dan sayuran",
  "Tumbuhan mendukung lingkungan yang sehat.",
  "Tumbuhan mengambil dan melepaskan gas saat membuat makanan dan tumbuh",
  "Tumbuhan mengambil karbon dioksida saat membuat makanan dalam cahaya.",
  "Tumbuhan mengambil air untuk tumbuh dan tetap sehat.",
  "Tumbuhan mengambil zat gizi dari tanah.",
  "Tumbuhan yang tumbuh di air memiliki ciri khusus yang membantu mereka mengapung atau tetap tegak.",
  "Tumbuhan yang membuat makanan dari sinar matahari",
  "Tumbuhan mengangkut air ke atas melalui tabung kecil yang disebut xilem.",
  "Tumbuhan menggunakan energi cahaya serta mengambil air, udara, dan zat gizi untuk hidup dan tumbuh. Kebutuhan yang kurang membatasi pertumbuhan.",
  "Tumbuhan menggunakan sinar matahari dan air untuk membuat makanan sendiri dan melepaskan oksigen.",
  "Tumbuhan biasanya tidak berespirasi sama sekali",
  "Tumbuhan akan berhenti membutuhkan sinar matahari.",
  "Tumbuhan, batu, dan awan bukan hewan.",
  "Plasma",
  "Plasma, kristal, dan cairan",
  "Plastik",
  "Plastik — selalu berubah menjadi gas saat dipanaskan.",
  "Plastik — menghantarkan listrik lebih baik daripada logam apa pun.",
  "Plastik selalu menghantarkan lebih baik",
  "Plastik selalu tenggelam tanpa bahaya ke dasar laut.",
  "Plastik dan karet sering bertindak sebagai isolator.",
  "Plastik dapat membutuhkan ratusan tahun untuk terurai di lingkungan.",
  "Lapisan plastik sering bertindak sebagai isolator.",
  "Wadah plastik untuk menyimpan makanan mereka.",
  "Plastik adalah sejenis kayu",
  "Plastik adalah bahan buatan manusia. Plastik dibuat dari bahan kimia, banyak di antaranya berasal dari minyak. Tidak seperti kayu atau batu, plastik tidak ada di alam — orang menciptakannya dan memproduksinya. Plastik ringan, tahan air, dan dapat dibentuk menjadi banyak bentuk berbeda.",
  "Plastik ditemukan di alam seperti batu",
  "Plastik dibuat di pabrik dan tidak ditemukan siap pakai di alam",
  "Plastik hanya dibuat dari pasir",
  "Plastik diproduksi, sering dari minyak bumi. Plastik bukan bahan alami seperti kayu atau batu.",
  "Sampah plastik dapat membahayakan satwa liar.",
  "Plastik membuat air laut lebih enak bagi ikan.",
  "Pencemaran plastik membahayakan tumbuhan, hewan, dan saluran air di ekosistem.",
  "Plastik menahan arus listrik, jadi sering digunakan untuk melapisi kabel dan membuat gagang yang aman.",
  "Cangkang plastik",
  "Plastik yang membuat buah",
  "Plastik yang sampai ke laut pecah menjadi potongan yang semakin kecil tetapi tidak pernah benar-benar hilang. Penyu laut, ikan, dan burung laut sering mengira plastik sebagai makanan. Saat mereka memakannya, plastik menyumbat pencernaan dan dapat membunuh mereka. Pencemaran plastik juga merusak terumbu karang dan habitat laut lainnya.",
  "Plastik yang hanya memakai air asin",
  "Pembungkus plastik",
  "Plastik.",
  "Sifat plastik membuatnya berguna untuk banyak benda sehari-hari yang tidak boleh terlalu berat.",
  "Plastik harus didaur ulang atau dibuang secara bertanggung jawab.",
  "Batas lempeng menciptakan gerakan tektonik dan jalur magma",
  "Peta batas lempeng membantu menjelaskan di mana energi geologi dilepaskan. Itu adalah alat berpikir inti ilmu Bumi.",
  "Serbuk sari membawa bahan yang dibutuhkan untuk pembuahan pada tumbuhan berbunga. Angin, air, atau hewan dapat memindahkan serbuk sari.",
  "Serbuk sari membawa bahan yang dibutuhkan untuk produksi biji saat bergerak ke bagian bunga yang tepat.",
  "Serbuk sari adalah bubuk dari bagian jantan bunga. Serbuk sari harus mencapai bagian betina agar biji dapat terbentuk.",
  "Serbuk sari menempel pada lebah dan berpindah antar bunga. Penyerbukan membantu tumbuhan membuat buah dan biji.",
  "Pemindahan serbuk sari memungkinkan pembuahan pada tumbuhan berbunga. Banyak tanaman pangan dan tumbuhan liar mendapat manfaat dari penyerbukan lebah.",
  "Menyerbukinya",
  "Biji yang menyerbuk",
  "Penyerbukan menghubungkan bunga untuk reproduksi.",
  "Penyerbukan penting bagi banyak buah dan biji.",
  "Penyerbukan penting bagi reproduksi tumbuhan.",
  "Penyerbukan dibutuhkan agar banyak tumbuhan membuat biji.",
  "Penyerbukan adalah bagian dari cara banyak tumbuhan berkembang biak.",
  "Penyerbukan adalah pemindahan serbuk sari yang membuahi bunga.",
  "Penyerbukan adalah pemindahan serbuk sari, sering oleh serangga, angin, atau hewan lain. Penyerbukan membantu tumbuhan membuat biji dan menumbuhkan tumbuhan baru.",
  "Penyerbukan mengarah ke pembuahan.",
  "Penyerbukan mengarah ke biji dan buah.",
  "Penyerbukan mendukung produksi biji dan buah.",
  "Penyerbuk sering membantu tumbuhan berbunga.",
  "Penyerbuk mendukung ekosistem dan pasokan makanan.",
  "Penyerbuk mendukung jaring makanan dan pertanian.",
  "Penyerbuk mendukung banyak tumbuhan.",
  "Udara tercemar mengandung partikel dan gas berbahaya yang dapat mengiritasi dan merusak paru-paru, membuat sulit bernapas dan meningkatkan risiko sakit.",
  "Air tercemar dapat membawa zat berbahaya yang merusak kesehatan dan habitat.",
  "Air tercemar merusak kesehatan hewan yang minum atau hidup di dalamnya",
  "Pencemaran dapat berasal dari cerobong asap, mobil, atau sampah.",
  "Pencemaran dapat masuk ke air dari pabrik, pertanian, dan membuang sampah sembarangan.",
  "Pencemaran di tanah memengaruhi segala sesuatu yang tumbuh di dalamnya.",
  "Pencemaran di air dapat meracuni ikan, katak, dan makhluk hidup lain yang bergantung pada air bersih untuk minum, bernapas, dan bertahan hidup.",
  "Bahan pencemar ke tanah (, ) ke tumbuhan hidup.",
  "Pencemaran berarti bahan berbahaya di udara, air, atau tanah yang dapat menyakiti hewan, tumbuhan, dan manusia.",
  "Sumber pencemaran termasuk lalu lintas dan pembakaran bahan bakar.",
  "Pencemaran yang menghilangkan produsen menyebabkan reaksi berantai yang memengaruhi setiap organisme di ekosistem.",
  "Ukuran populasi dapat berubah saat kondisi berubah.",
  "Populasi bergantung pada sumber daya yang tersedia.",
  "Tuangkan bensin ke daun kering di luar ruangan.",
  "Tuangkan campuran melalui saringan",
  "Tuangkan air langsung ke perangkat elektronik yang masih terpasang.",
  "Menuangkan minyak ke tanah",
  "Latihan dan olahraga dapat memperkuat otot.",
  "Latihan berenang dengan insang",
  "Presipitasi → penguapan → kondensasi → pengumpulan",
  "Presipitasi tanpa penguapan atau aliran kembali ke laut",
  "Predator",
  "Predator dan mangsa adalah bagian dari rantai makanan.",
  "Populasi predator dan mangsa saling memengaruhi.",
  "Penglihatan predator membentuk pertahanan mangsa.",
  "Hubungan predator–mangsa membentuk ekosistem.",
  "Pasangan predator–mangsa muncul di seluruh jaring makanan.",
  "Predator dan batas makanan membantu menyeimbangkan ekosistem.",
  "Predator dan mangsa saling memengaruhi.",
];

if (id.length !== en.length) {
  console.error(`Length mismatch: en=${en.length} id=${id.length}`);
  process.exit(1);
}

const map = Object.fromEntries(en.map((k, i) => [k, id[i]]));
fs.writeFileSync(path.join(__dirname, "map-chunk-17.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("wrote map-chunk-17.json keys=", Object.keys(map).length);
