import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(dir, "strings-chunk-11.json"), "utf8"));

const id = [
  "Bagaimana kelelawar sering menemukan serangga dalam gelap?",
  "Bagaimana lebah membantu tumbuhan berbunga?",
  "Bagaimana lebah membantu bunga?",
  "Bagaimana lebah membantu banyak tumbuhan berbunga?",
  "Bagaimana lebah membantu tumbuhan berkembang biak?",
  "Bagaimana burung tetap hangat dalam cuaca dingin?",
  "Bagaimana sistem tubuh bekerja bersama?",
  "Bagaimana sapi mendapat energi?",
  "Bagaimana sirip membantu ikan bertahan hidup?",
  "Bagaimana ikan mendapat oksigen saat hidup di air?",
  "Bagaimana tumbuhan hijau membuat gula untuk makanan?",
  "Bagaimana gas rumah kaca seperti CO₂ membantu menghangatkan Bumi dibandingkan dengan dunia yang memiliki sedikit atmosfer?",
  "Bagaimana planet dalam sering berbeda dari planet luar di tata surya?",
  "Bagaimana ginjal terutama membantu menjaga tubuh seimbang?",
  "Bagaimana banyak kelelawar menemukan makanan dalam gelap?",
  "Bagaimana banyak kelelawar menemukan mangsa dalam gelap?",
  "Bagaimana banyak biji berkelana ke tempat baru jauh dari tumbuhan induk?",
  "Bagaimana banyak hewan kecil melindungi diri dari predator?",
  "Bagaimana kebanyakan bayi mamalia memulai hidup dibandingkan dengan banyak serangga?",
  "Bagaimana otot dan kerangka membantu tubuh bergerak?",
  "Bagaimana tumbuhan memindahkan air dari akar ke daun?",
  "Bagaimana reptil biasanya mendapat panas yang mereka butuhkan?",
  "Bagaimana akar yang tumbuh ke dalam tanah terutama membantu tumbuhan?",
  "Bagaimana kumis membantu kucing?",
  "Bagaimana kamu merasakan sentuhan lembut di lenganmu?",
  "Bagaimana lebah membantu tumbuhan?",
  "Bagaimana paruh burung membantunya bertahan hidup?",
  "Bagaimana otak anak membantu dalam belajar?",
  "Bagaimana buah terbentuk pada tumbuhan?",
  "Bagaimana minum air membantu tubuh?",
  "Bagaimana panas bergerak?",
  "Bagaimana logam berbeda dari kayu dalam menghantarkan panas?",
  "Bagaimana oksigen dari udara sampai ke sel tubuh?",
  "Bagaimana oksigen sampai dari paru-paru ke bagian tubuh lainnya?",
  "Bagaimana melindungi hutan, lahan basah, dan padang rumput membantu hewan?",
  "Bagaimana air hujan terbentuk dalam siklus air?",
  "Bagaimana daur ulang di sekolah membantu lingkungan?",
  "Bagaimana kulit membantu kamu merasakan dunia?",
  "Bagaimana mengaduk air terutama memengaruhi pelarutan garam?",
  "Bagaimana sistem pencernaan bekerja?",
  "Bagaimana cuaca berubah?",
  "Bagaimana mulutmu membantu kamu makan makanan?",
  "Seberapa berat sebuah batu",
  "Seberapa berat benda itu tampak dari luar.",
  "Seberapa panas atau dingin Bulan di malam hari.",
  "Bagaimana planet berbeda dari bintang seperti Matahari?",
  "Bagaimana planet berbeda dari bintang?",
  "Bagaimana percobaan berbeda dari hanya mengamati?",
  "Bagaimana logam berbeda dari kaca dalam menghantarkan listrik?",
  "Bagaimana malam berbeda dari siang?",
  "Bagaimana jantung terhubung dengan sistem peredaran darah?",
  "Bagaimana Cincin Api (sabuk Pasifik gunung berapi dan gempa) terkait dengan kelompok gempa dan letusan?",
  "Seberapa panjang rambutmu tumbuh",
  "Seberapa keras suatu suara",
  "Berapa banyak lengan dan kaki yang dimiliki kebanyakan orang?",
  "Berapa banyak mata yang dimiliki kebanyakan orang?",
  "Berapa banyak jari di setiap tangan?",
  "Berapa banyak indera utama yang dimiliki orang?",
  "Berapa banyak bulan yang dimiliki Bumi?",
  "Berapa banyak gigi yang akan kamu tumbuhkan besok",
  "Berapa banyak cahaya yang disimpan matamu",
  "Seberapa tinggi kamu tahun depan",
  "Seberapa tebal kulitmu terasa",
  "Bintang besar yang sangat jauh yang membuat cahaya sendiri dan terlihat seperti titik dari Bumi",
  "Kegiatan manusia bisa menyusutkan atau merusak habitat.",
  "Aktivitas manusia telah menambahkan sejumlah besar gas rumah kaca ke udara.",
  "Perilaku manusia memengaruhi hasil bagi satwa liar.",
  "Gangguan manusia adalah faktor konservasi yang penting.",
  "Manusia memiliki endoskeleton di dalam tubuh.",
  "Manusia memiliki dua paru-paru, satu di setiap sisi dada, dilindungi oleh tulang rusuk.",
  "Kelembapan dan suhu bersama membentuk bagaimana cuaca panas terasa.",
  "Adaptasi berburu mencakup penglihatan tajam dan cakar pada banyak burung pemangsa.",
  "Kebersihan membantu melindungi kamu dan orang lain.",
  "Hipotesis memandu penyelidikan sebelum kamu mengumpulkan hasil.",
  "Hipotesis memandu penyelidikan.",
  "Hipotesis memandu apa yang diuji.",
  "Hipotesis memandu apa yang kamu ukur dan amati.",
  "Hipotesis harus bisa diuji.",
  "Aku suka buku catatan biru.",
  "Es krim setiap jam",
  "Kristal es yang jatuh dari awan saat sangat dingin",
  "Es selalu lebih gelap daripada air, jadi es lebih cepat hangat",
  "Es adalah air dalam wujud padat. Memanaskan es mengubahnya menjadi air cair.",
  "Es mencair menjadi air cair",
  "Es berubah seketika menjadi logam padat",
  "Es, air cair, dan uap adalah zat yang sama.",
  "Es, air cair, dan uap air adalah zat yang sama dalam wujud berbeda.",
  "Kenali bahan sebelum menggunakannya.",
  "Kenali faktor yang diubah, diukur, dan yang tetap sama.",
  "Kenali apa yang kamu ubah dan apa yang kamu biarkan sama.",
  "Jika bahan kimia tumpah selama laboratorium, apa yang harus kamu lakukan terlebih dahulu?",
  "Jika habitat berubah banyak, hewan mungkin kesulitan bertahan hidup.",
  "Jika ikan predator baru masuk ke danau dan populasinya tumbuh cepat, apa risiko utama bagi danau jika tidak ada yang menyeimbangkannya?",
  "Jika penyakit tumbuhan membunuh sebagian besar produsen di suatu wilayah, apa yang mungkin terjadi?",
  "Jika tumbuhan mendapat lebih banyak cahaya, maka ia akan tumbuh lebih tinggi.",
  "Jika laporan mengatakan tren suhu cocok dengan perubahan iklim yang disebabkan manusia, mengapa perbandingan dengan dekade lebih lama harus ditangani dengan hati-hati?",
  "Jika menggandakan pupuk tidak menggandakan panen, mengapa itu mematahkan model “garis lurus” sederhana antara jumlah pupuk dan hasil?",
  "Jika penangkapan ikan legal turun di perikanan yang sudah terkuras, tetapi penangkapan ilegal naik, apa hasil yang mungkin?",
  "Jika cahaya dan air keduanya berubah, salah satu—atau keduanya—bisa menjelaskan hasilnya. Ubah satu variabel utama pada satu waktu.",
  "Jika satu titik data jauh dari yang lain, apa langkah cerdas berikutnya?",
  "Jika suatu hari dingin, tahun itu pasti lebih dingin dari rata-rata",
  "Jika predator hilang dari ekosistem, apa yang mungkin terjadi?",
  "Jika resolusi tinggi, perangkat pasti akurat",
  "Jika sebarannya kecil, tidak pernah ada kesalahan",
  "Jika alat salah dengan cara yang sama setiap kali, semua nilai bisa bergeser. Periksa peralatan sebelum mengumpulkan data.",
  "Jika terlalu banyak hal berubah sekaligus, kamu tidak bisa tahu perubahan mana yang menyebabkan hasilnya.",
  "Jika kamu tidak yakin tentang suatu langkah dalam percobaan, selalu tanyakan kepada gurumu sebelum melanjutkan.",
  "Jika kamu mengubah lebih dari satu hal sekaligus, kamu tidak bisa tahu perubahan mana yang menyebabkan hasil yang kamu amati. Mengubah hanya satu variabel sambil menjaga yang lain tetap sama membuatnya menjadi uji yang adil. Ini adalah salah satu aturan terpenting dari desain percobaan yang baik.",
  "Jika kamu hanya mengubah jenis tanah dan mengukur pertumbuhan tumbuhan, apa nama jenis tanah itu?",
  "Jika kamu mengukur panjang bayangan dengan cara yang sama setelah kelas setiap hari tetapi selalu lupa menyetel ulang meter, bagaimana kesalahan itu berperilaku sepanjang minggu?",
  "Jika kamu menguji bagaimana air memengaruhi pertumbuhan biji, apa yang harus kamu ubah?",
  "Jika denyut nadimu lebih cepat, apa yang biasanya benar?",
  "Abaikan setiap pengukuran yang kamu buat",
  "Abaikan aturan asap pabrik",
  "Abaikan aturan api di hutan.",
  "Abaikan dan terus bermain keras.",
  "Abaikan jika terlihat seperti air",
  "Abaikan tumpahan pada peralatan listrik.",
  "Abaikan ketidakcocokan sepenuhnya.",
  "Abaikan satuan sejak saat itu",
  "Abaikan tanda peringatan tentang panas.",
  "Mengabaikan semua data dengan sengaja",
  "Mengabaikan awan",
  "Mengabaikan lingkungan agar bisnis bisa tumbuh lebih cepat.",
  "Mengabaikan sampah di taman",
  "Penangkapan ikan ilegal seketika meningkatkan ukuran setiap ikan jantan",
  "Di kota besar, lebih banyak lahan tertutup beton dan jalan, dan lebih sedikit kebun serta pohon tersisa. Apa yang paling mungkin terjadi pada hari yang panas?",
  "Dalam perubahan kimia, bahan baru terbentuk. Membakar kertas menghasilkan abu dan gas—bahan baru.",
  "Dalam studi perilaku di kelas, murid tahu mereka sedang direkam. Mengapa itu bisa mengubah temuan dibandingkan dengan situasi yang tidak disadari?",
  "Dalam senyawa, atom bergabung secara kimia.",
  "Dalam percobaan terkendali, ubah satu variabel dan jaga kondisi lain sesetabil mungkin.",
  "Dalam deret waktu suhu harian, satu titik sangat tidak biasa tanpa penjelasan cuaca. Apa langkah penelitian yang masuk akal sebelum menghapusnya?",
  "Dalam percobaan buta ganda, baik peserta maupun peneliti tidak tahu siapa yang menerima perlakuan nyata atau plasebo. Itu mengurangi bias.",
  "Dalam uji rasa minuman, juri tidak tahu cangkir mana yang asli. Mengapa itu membantu?",
  "Dalam tahun kering, mengapa mengebor akuifer lokal bisa memperdalam tekanan kekeringan di tempat jauh dari sumur?",
  "Dalam percobaan yang adil kamu mengubah satu variabel yang direncanakan saat menguji pengaruh tanah.",
  "Dalam uji yang adil, biasanya hanya satu variabel diubah pada satu waktu.",
  "Dalam uji yang adil, apa nama faktor yang bisa diubah atau diukur?",
  "Dalam uji yang adil, apa itu variabel?",
  "Dalam rantai makanan, apa yang disediakan produsen bagi makhluk hidup lainnya?",
  "Dalam jaring makanan, setiap spesies bergantung pada yang lain untuk makanan. Jika ikan kecil hilang, ikan lebih besar, burung, dan hewan lain yang memakannya kehilangan sumber makanan utama. Populasi mereka pun menurun. Efek riak ini disebut kaskade trofik.",
  "Dalam jaring makanan, apa biasanya yang disebut produsen?",
  "Dalam ekosistem danau, peristiwa tunggal mana yang paling merugikan jaring makanan?",
  "Dalam ekosistem danau, dari mana sebagian besar energi untuk semua makhluk hidup berasal pada awalnya?",
  "Dalam jaring makanan danau, jika populasi ikan kecil tiba-tiba anjlok, apa pengaruh yang paling mungkin?",
  "Dalam campuran zat bisa dipisahkan secara fisik, tetapi dalam senyawa unsur-unsur terikat secara kimia",
  "Dalam campuran, ikatan kimia baru selalu terbentuk di antara setiap bagian",
  "Dalam campuran, bahan asli tetap zat yang terpisah.",
  "Dalam perubahan fisik, bentuk atau wujud bisa berubah, tetapi identitas kimia tetap sama.",
  "Dalam percobaan sederhana, apa variabel yang dipilih dengan baik untuk diubah?",
  "Dalam rantai makanan sederhana, apa yang disediakan tumbuhan?",
  "Dalam studi sederhana tentang produk pereda nyeri baru berdasarkan perasaan orang, mengapa membandingkan dengan kelompok yang mendapat barang mirip tanpa bahan aktif (plasebo)?",
  "Dalam uji tentang mitos pertumbuhan tumbuhan obat, apa sering disebut tumbuhan yang tidak diolah?",
  "Di tempat sampah atau wadah daur ulang yang tepat",
  "Dalam percobaan pemanasan air, peneliti menambah garam dan juga menaikkan api sekaligus. Apa yang salah dengan menyimpulkan “garam menyebabkan perubahan pemanasan”?",
  "Di hampir setiap ekosistem, energi berasal dari Matahari. Tumbuhan dan alga menangkap sinar matahari melalui fotosintesis dan mengubahnya menjadi makanan. Herbivora memakan tumbuhan, karnivora memakan herbivora, dan seterusnya — tetapi semua energi itu pada awalnya berasal dari Matahari.",
  "Dalam perjanjian polusi udara antar negara tetangga, apa yang harus tetap konsisten agar data bisa dibandingkan?",
  "Dalam percobaan tentang pupuk dan tinggi tumbuhan, apa biasanya disebut jumlah pupuk?",
  "Dalam percobaan tentang berapa banyak air yang tersisa di cangkir setelah sehari, apa biasanya hasil terikat versus kondisi yang sengaja kamu ubah?",
  "Dalam percobaan, hanya 50% biji yang berkecambah. Mengapa sulit menarik kesimpulan pasti dari hasil ini saja?",
  "Dalam percobaan, menggunakan alat yang salah memberi data yang salah atau tidak bermakna, meskipun prosedurnya bagus.",
  "Dalam percobaan, kamu menguji ide dengan sengaja mengubah sesuatu.",
  "Di kelas, apa yang biasanya membedakan konduktor listrik dari isolator?",
  "Di bulan dingin, makanan bisa langka. Hewan yang berhibernasi melambat dan beristirahat melewati musim sulit.",
  "Di musim dingin, air bisa lebih sulit digunakan. Menggugurkan daun membantu beberapa pohon beristirahat melewati musim dingin.",
  "Di dalam kerucut",
  "Di musim gugur, daun berubah warna saat klorofil terurai.",
  "Di musim gugur, banyak daun menjadi kuning, merah, atau oranye dan gugur dari pohon saat cahaya dan suhu berubah.",
  "Di banyak tempat, hari musim panas lebih panjang daripada hari musim dingin.",
  "Di banyak wilayah, musim dingin membawa suhu lebih dingin daripada musim lain.",
  "Di iklim Mediterania, musim dingin sering lebih sejuk dan lebih basah daripada musim panas.",
  "Dalam fotosintesis, tumbuhan menggunakan cahaya, air, dan karbon dioksida untuk membuat gula dan melepaskan oksigen.",
  "Dalam fotosintesis, tumbuhan menangkap energi cahaya dan membangun gula. Oksigen dilepaskan sebagai hasil samping yang berguna.",
  "Dalam fotosintesis, tumbuhan menggunakan cahaya, air, dan karbon dioksida untuk membuat gula.",
  "Dalam fotosintesis, tumbuhan menggunakan sinar matahari untuk membuat gula dari air dan karbon dioksida.",
  "Dalam sirkulasi pulmoner, darah berjalan antara jantung dan paru-paru untuk pertukaran gas.",
  "Dalam sains, bukti yang memimpin. Jika data tidak mendukung klaim, klaim harus berubah—atau mungkin dibutuhkan lebih banyak pengujian.",
  "Dengan kata sederhana, apa pekerjaan utama darah dalam tubuh?",
  "Di tanah di.",
  "Di tanah, di air, atau bahkan tanpa tanah dalam kondisi tertentu.",
  "Di musim semi, daun baru tumbuh lagi.",
  "Di musim panas, bagian Bumi tempat kamu tinggal miring ke arah Matahari. Ini berarti Matahari lebih tinggi di langit, sinarnya mengenai tanah lebih langsung, dan tetap di atas lebih banyak jam setiap hari. Sinar matahari lebih langsung selama waktu lebih lama berarti lebih banyak panas.",
  "Di perut",
  "di dada, di sisi kanan tubuh",
  "di dada, sedikit ke kiri dari tengah",
  "Di musim hujan yang lebih sejuk (sering musim dingin)",
  "Di tangan",
  "Di kepala",
  "Di kaki",
  "Di paru-paru, terjadi pertukaran gas. Darah mendapat oksigen untuk tubuh dan melepaskan karbon dioksida untuk diembuskan.",
  "Di paru-paru, oksigen dari udara masuk ke darah, dan karbon dioksida keluar dari darah untuk diembuskan.",
  "Di mulut, di mana mengunyah dan air liur mulai memecah makanan",
  "Dalam urutan kurangi–gunakan ulang–daur ulang, mengurangi datang pertama. Menggunakan lebih sedikit kertas menurunkan penebangan dan manufaktur; daur ulang membantu setelah produk digunakan.",
  "Di tata surya, Bumi adalah planet.",
  "di perut bagian atas, dekat hati",
  "Dalam siklus air, air menguap dari samudra dan danau, naik ke atmosfer, dingin dan mengembun membentuk awan, lalu jatuh kembali ke Bumi sebagai hujan.",
  "Dalam siklus air, air menguap, membentuk awan, jatuh sebagai hujan atau salju, dan kembali ke samudra dan daratan.",
  "Dalam siklus air, air bergerak di antara samudra, daratan, dan udara melalui penguapan, kondensasi, dan curah hujan.",
  "Dalam wujud zat apa saja air bisa berada?",
  "Di musim dingin di banyak tempat",
  "Meningkatkan perjalanan mobil pribadi untuk setiap murid",
  "Meningkatkan aliran darah dan menyiapkan otot untuk usaha keras yang tiba-tiba",
  "Meningkatkan keluaran pabrik untuk mendorong produksi dan lapangan kerja.",
  "Menaikkan suhu meningkatkan kapasitas pelarutan air bagi kebanyakan padatan.",
  "Variabel bebas",
  "Variabel bebas (apa yang kamu ubah)",
  "Jumlah variabel bebas",
  "Variabel bebas versus variabel terikat penting.",
  "Informasi yang dikumpulkan dalam percobaan—angka, pengamatan, dan hasil",
  "Informasi yang dikumpulkan menggunakan inderamu — apa yang kamu lihat, dengar, cium, kecap, atau rasakan.",
  "Menghirup membawa udara segar ke kantung udara kecil. Oksigen masuk ke darah sementara karbon dioksida keluar.",
  "Planet dalam relatif lebih kecil dan sering berbatu",
  "Bahan anorganik berasal dari sumber tidak hidup—batuan, logam, kaca, dan tanah liat adalah contohnya.",
  "Siklus penyelidikan: pertanyaan → hipotesis → percobaan → analisis → kesimpulan.",
  "Serangga memiliki penutup luar keras yang disebut eksoskeleton yang menopang dan melindunginya.",
  "Serangga membantu memindahkan serbuk sari dari bunga ke bunga.",
  "Serangga yang mengunjungi bunga membantu penyerbukan.",
  "Serangga, angin, atau air bisa memindahkan serbuk sari.",
  "Di dalam biji ada tumbuhan bayi dan makanan tersimpan.",
  "Di dalam tubuh ada banyak organ—jantung, paru-paru, lambung, usus, hati, ginjal, dan lainnya—masing-masing dengan pekerjaan penting.",
  "Fotosintesis seketika di kulit",
  "Seketika menciptakan lebih banyak hutan kuno",
  "Isolasi terhadap air dingin",
  "Isolasi dan perilaku cerdas mengurangi kehilangan panas. Beberapa hewan juga berhibernasi atau bermigrasi.",
  "Isolasi membantu menahan panas tubuh.",
  "Isolasi mengurangi kehilangan panas di tempat dingin.",
  "Isolator selalu mencair pada suhu ruang",
  "Isolator penting untuk keselamatan.",
  "Isolator menghalangi aliran listrik dan digunakan untuk menjaga orang aman di sekitar kabel.",
  "Isolator membantu menjaga listrik di tempat yang seharusnya.",
  "Isolator membantu menjaga panas masuk atau keluar.",
  "Isolator mencegah bola lampu menyala.",
  "Isolator melindungi orang dari sengatan listrik.",
  "Isolator melindungi pengguna dari sengatan.",
  "Isolator menahan arus listrik. Karet sering digunakan untuk menutupi kabel demi keselamatan.",
  "Isolator memperlambat atau menghalangi aliran panas atau listrik.",
  "Isolator seperti karet menahan aliran listrik.",
  "Isolator seperti kayu atau plastik tidak menghantarkan listrik dengan baik.",
  "Intensitas harus naik secara bertahap.",
  "Organ dalam seperti jantung, paru-paru, lambung, dan lainnya",
  "Memperkenalkan spesies invasif apa pun untuk bersenang-senang",
  "Menciptakan planet baru untuk menjelaskannya",
  "Menciptakan nilai baru tanpa penjelasan",
  "Menciptakan angka baru tanpa menguji",
  "Menciptakan hasil tanpa uji",
  "Invertebrata, seperti serangga dan cacing, tidak memiliki tulang belakang yang terbuat dari tulang.",
  "Selidiki kemungkinan kesalahan saat hasil terlihat aneh.",
  "Besi",
  "Besi adalah logam keras. Orang menggunakannya untuk membangun dan membuat alat.",
  "Besi berkarat menjadi bahan baru",
];

if (en.length !== id.length) {
  console.error("LENGTH MISMATCH", en.length, id.length);
  process.exit(1);
}
const map = Object.fromEntries(en.map((e, i) => [e, id[i]]));
fs.writeFileSync(path.join(dir, "map-chunk-11.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("map-chunk-11 keys", Object.keys(map).length);
