import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(dir, "strings-chunk-8.json"), "utf8"));

const id = [
  "Elang",
  "Ide awal tanpa pengumpulan data di laboratorium",
  "Telinga adalah organ pendengaran.",
  "Telinga mengumpulkan suara dan mengirim sinyal pendengaran ke otak.",
  "Organ telinga. melaluinya masuk ke otak.",
  "Telinga.",
  "Bumi juga berputar pada porosnya sendiri, sehingga terjadi siang dan malam.",
  "Bumi juga berputar setiap hari sehingga terjadi siang dan malam.",
  "Bumi dan Matahari keduanya diam sepenuhnya di ruang angkasa.",
  "Bumi sebagai satu-satunya benda di alam semesta",
  "Bumi menyelesaikan satu putaran penuh setiap 24 jam.",
  "Bumi memiliki kerak luar yang tipis, mantel yang tebal, dan inti yang sangat panas.",
  "Bumi memiliki empat musim — musim semi, musim panas, musim gugur, dan musim dingin — yang disebabkan oleh kemiringan Bumi saat mengorbit Matahari. Bagian Bumi yang berbeda menerima lebih banyak atau lebih sedikit sinar matahari pada waktu berbeda dalam setahun.",
  "Bumi memiliki satu bulan. Bulan itu mengorbit Bumi dan sering disebut saja sebagai Bulan.",
  "Bumi berada di pusat tata surya.",
  "Bumi itu datar, jadi sudutnya tidak pernah berubah",
  "Bumi terdiri dari kerak, mantel, dan inti",
  "Bumi adalah satu lapisan seragam saja",
  "Bumi hanya kerak tipis di atas ruang kosong",
  "Bumi hanyalah bagian kecil darinya.",
  "Bumi diorbit oleh Matahari, bukan oleh Bulan.",
  "Bumi adalah planet ketiga dari Matahari dan mengorbitnya sekali setiap 365 hari.",
  "Bumi miring pada porosnya dan mengelilingi Matahari sepanjang tahun. Ketika sebuah belahan Bumi miring ke arah Matahari, ia menerima sinar matahari lebih langsung selama lebih banyak jam setiap hari — sehingga terjadi musim panas. Ketika miring menjauh, ia menerima sinar matahari kurang langsung — sehingga terjadi musim dingin.",
  "Bumi membuat sinar mataharinya sendiri hanya di malam hari",
  "Bumi bergerak mengelilingi Matahari pada jalur yang disebut orbit. Satu orbit penuh memakan waktu sekitar 365 hari — satu tahun. Bumi juga berputar pada porosnya sendiri, yang menciptakan siang dan malam dalam siklus 24 jam.",
  "Bumi bergerak lebih dekat ke dan lebih jauh dari Matahari setiap hari.",
  "Bumi bergerak lebih dekat ke atau lebih jauh dari Matahari sepanjang hari.",
  "Bumi tidak pernah mengalami perubahan iklim di masa geologi lalu",
  "Bumi hanya bergerak di ruang angkasa pada siang hari.",
  "Bumi mengorbit Matahari pada jalur yang disebut revolusi, yang memakan waktu sekitar 365 hari.",
  "Bumi mengorbit Matahari sekali setiap tahun.",
  "Bumi mengorbit Matahari sekali setiap tahun.",
  "Bumi lewat di antara Matahari dan Bulan—itu adalah gerhana bulan",
  "Bumi berputar pada porosnya sekali setiap 24 jam. Sisi yang menghadap Matahari mengalami siang, dan sisi yang membelakangi mengalami malam.",
  "Bumi berputar sekali sekitar setiap 24 jam. Sisi yang menghadap Matahari mengalami siang, dan sisi yang membelakangi mengalami malam.",
  "Bumi berputar sehingga bagian planet kita menghadap ke Matahari.",
  "Bumi berputar sehingga sisi kita menghadap ke Matahari.",
  "Bumi berputar pada porosnya setiap 24 jam.",
  "Bumi berputar pada porosnya sehingga setiap sisi menghadap Matahari pada waktu yang berbeda.",
  "Bumi berputar pada porosnya setiap 24 jam. Ketika sisi Bumi tempat kamu tinggal membelakangi Matahari, cahaya Matahari tidak sampai ke kamu — terjadilah malam. Tanpa sinar matahari, lebih gelap dan biasanya lebih sejuk daripada siang hari.",
  "Bumi berputar pada porosnya, membuat satu putaran penuh setiap 24 jam. Ketika sisi Bumi tempat kamu tinggal menghadap Matahari, itu siang hari. Ketika sisi itu membelakangi Matahari, itu malam hari.",
  "Bumi berputar pada porosnya, sehingga sisi yang berbeda menghadap Matahari pada waktu yang berbeda",
  "Bumi berputar pada porosnya sendiri sekali setiap 24 jam. Ketika bagian Bumi tempat kamu tinggal berputar menghadap Matahari, sinar matahari sampai ke kamu dan terjadilah siang. Saat Bumi terus berputar, bagian yang sama membelakangi Matahari dan terjadilah malam.",
  "Bumi berputar pada porosnya sendiri, sehingga bagian yang berbeda menghadap Matahari pada waktu yang berbeda.",
  "Bumi diam sementara Matahari mengitarinya.",
  "Bumi diam sepenuhnya di ruang angkasa.",
  "Bumi diam sementara Bulan mengorbit Matahari tanpa hubungan dengan Bumi",
  "Bumi menerima dan melepaskan radiasi dalam keseimbangan yang berubah.",
  "Bumi mengelilingi Matahari pada jalur elips yang hampir melingkar",
  "Bumi mengelilingi Matahari sekali setiap tahun. Orbit tahunan ini, digabung dengan kemiringan Bumi, memberi kita musim. Bumi juga berputar pada porosnya setiap 24 jam, memberi kita siang dan malam.",
  "Bumi mengelilingi Matahari sekali setiap tahun.",
  "Suhu rata-rata Bumi bergantung pada keseimbangan energinya.",
  "Kemiringan poros Bumi menyebabkan bagian yang berbeda menerima lebih banyak atau lebih sedikit sinar matahari sepanjang tahun.",
  "Poros Bumi miring sekitar 23,5 derajat. Saat Bumi mengorbit Matahari, wilayah yang berbeda menerima jumlah sinar matahari yang berbeda, yang menyebabkan empat musim.",
  "Poros Bumi miring, jadi saat mengorbit Matahari, Belahan Utara dan Selatan bergantian miring ke arah Matahari, sehingga menyebabkan musim.",
  "Putaran harian Bumi pada porosnya sendiri disebut rotasi.",
  "Jarak Bumi dari Matahari sebagai satu-satunya penyebab.",
  "Jarak Bumi dari Matahari hanya sedikit berubah sepanjang tahun dan bukan penyebab utama musim.",
  "Orbit Bumi mengelilingi Matahari adalah alasan utama musim, bukan siang dan malam.",
  "Rotasi Bumi — putarannya pada porosnya — yang menciptakan siklus siang dan malam.",
  "Rotasi Bumi membawa suatu tempat ke dalam cahaya matahari lalu ke dalam bayangan",
  "Rotasi Bumi menyebabkan pergantian siang dan malam setiap 24 jam.",
  "Rotasi Bumi menciptakan defleksi Coriolis yang membengkokkan jalur angin berskala besar",
  "Rotasi Bumi yang menciptakan siklus siang dan malam 24 jam.",
  "Rotasi Bumi membuat Matahari tampak bergerak.",
  "Rotasi Bumi membuat Matahari tampak terbit dan terbenam",
  "Rotasi Bumi memutar tempat yang berbeda menghadap dan membelakangi Matahari, menciptakan siang dan malam.",
  "Bayangan Bumi selalu menutupi sebagian permukaan Bulan di malam hari.",
  "Putaran Bumi menambah defleksi pada gerakan besar yang berlangsung lama. Itu tidak menjelaskan segelas air di meja, tetapi membentuk pola badai global dalam model sederhana.",
  "Struktur Bumi mencakup batas antar lempeng tektonik.",
  "Kemiringan Bumi memengaruhi bagaimana sinar matahari mengenai lintang yang berbeda.",
  "Kemiringan Bumi dan orbitnya mengelilingi Matahari.",
  "Kemiringan Bumi dan jalurnya mengelilingi Matahari",
  "Kemiringan Bumi membantu menciptakan pola musim.",
  "Kemiringan Bumi membantu menciptakan musim.",
  "Kemiringan Bumi, bukan jaraknya dari Matahari, adalah penyebab utama musim.",
  "Kemiringan Bumi, bukan jaraknya dari Matahari, yang menyebabkan musim.",
  "Poros Bumi yang miring saat mengorbit Matahari",
  "Poros Bumi yang miring menyebabkan wilayah berbeda menerima lebih banyak atau lebih sedikit sinar matahari saat mengorbit Matahari",
  "Poros Bumi yang miring menyebabkan wilayah berbeda menerima lebih banyak atau lebih sedikit sinar matahari saat mengorbit Matahari",
  "Perjalanan tahunan Bumi mengelilingi Matahari disebut revolusi.",
  "Jalur tahunan Bumi mengelilingi Matahari terkait dengan musim dan sudut sinar matahari yang berubah.",
  "Gempa bumi yang mengguncang dan memecahkan batuan dengan keras selama peristiwa singkat dan tiba-tiba.",
  "Hanya memakan mamalia lain",
  "Memakan tumbuhan",
  "Makan, minum, dan mencari tempat berlindung",
  "Makan berbagai makanan sehat menyediakan protein, karbohidrat, lemak, vitamin, dan mineral.",
  "Makan memberi tubuhmu bahan bakar.",
  "Makan di pagi hari memberi bahan bakar setelah semalaman tanpa makanan.",
  "Hanya makan permen memberi setiap nutrisi",
  "Makan dengan baik, sering bergerak, beristirahat, dan menjaga kebersihan",
  "Memakan daunnya",
  "Ekholokasi membantu pemburu malam.",
  "Ekholokasi untuk menemukan nektar",
  "Ekholokasi tetap bekerja meski cahaya sedikit.",
  "Keseimbangan ekologi bergantung pada hubungan makan.",
  "Dampak ekologi bergantung pada total tangkapan dalam praktik. Penegakan yang lemah bisa membatalkan pengurangan di atas kertas.",
  "Keseimbangan ekosistem bergantung pada tautan-tautan itu.",
  "Kesehatan ekosistem dimulai dari produksi primer.",
  "Peran ekosistem saling terhubung.",
  "Jasa ekosistem membantu manusia sekaligus satwa liar.",
  "Jasa ekosistem mencakup penyaringan alami.",
  "Pengaruh hanya pada tumbuhan",
  "Telur, burung dewasa, sarang, bulu",
  "Telur, ulat, kepompong, kupu-kupu dewasa",
  "Telur, larva (ulat), kepompong, dewasa",
  "Telur berubah menjadi batu saat diamati.",
  "Elastisitas adalah sifat bahan yang berguna.",
  "Siku",
  "Listrik untuk televisi",
  "Listrik menggunakan pasir",
  "Limbah elektronik berasal dari perangkat lama. Mendaur ulangnya penting karena bisa mengandung bahan berbahaya sekaligus berharga.",
  "Menghilangkan kebutuhan akan sepatu dan keselamatan",
  "Botol plastik dapur yang kosong",
  "Mengakhiri percobaan tanpa penjelasan hasil",
  "Pengaruh energi dan populasi merambat ke atas. Kehilangan produsen membebani seluruh jaring makanan.",
  "Perubahan energi menyertai perubahan wujud.",
  "Energi berubah selama perubahan wujud.",
  "Energi masuk ke rantai makanan melalui produsen.",
  "Energi masuk ke banyak rantai makanan pertanian melalui tumbuhan.",
  "Energi masuk ke jaring makanan melalui fotosintesis, yang dilakukan oleh tumbuhan dan alga.",
  "Energi mengalir melalui jaring makanan.",
  "Energi dari Matahari mendorong sebagian besar siklus.",
  "Energi dari Matahari diserap lalu dikembalikan ke ruang angkasa.",
  "Energi di banyak rantai makanan dimulai dari sinar matahari yang ditangkap tumbuhan.",
  "Energi bergerak dari tumbuhan ke hewan.",
  "Energi bergerak dari produsen ke konsumen sepanjang rantai makanan.",
  "Jalur energi dan ketergantungan konsumen bisa berubah",
  "Energi yang tidak pernah berasal dari makanan",
  "Insinyur memilih bahan berdasarkan kekuatan, kelenturan, ketahanan panas, dan sifat lainnya.",
  "Nikmati alam tanpa mengambil lebih dari yang kamu butuhkan.",
  "Lingkungan dan kesehatan terkait dengan penggunaan bahan kimia yang hati-hati.",
  "Pertukaran lingkungan mencakup pembuatan, pengoperasian, dan pembuangan peralatan.",
  "Variabel lingkungan memengaruhi kinetika reaksi.",
  "Menghapus hasil sebelumnya tanpa mencatatnya",
  "Menghapus data dan mempertahankan kesimpulan.",
  "Menghapus setiap sifat bahan tanpa perubahan energi",
  "Menghapus bukti agar tidak ada yang bisa memeriksa",
  "Pengendalian erosi melindungi tanah dan air.",
  "Erosi tidak terjadi di aliran sungai",
  "Erosi sangat terkait dengan penutup tanah.",
  "Erosi adalah proses di mana batuan, tanah, dan sedimen terkikis dan terbawa ke tempat baru dalam jangka waktu lama.",
  "Erosi terlalu jarang untuk mengubah apa pun di air",
  "Erosi memindahkan tanah dan bisa mengeruhkan aliran sungai.",
  "Kesalahan hanya terjadi di kimia, bukan di ilmu kehidupan.",
  "Kerongkongan",
  "Memperkirakan secara liar tanpa melihat",
  "Etika dalam penelitian sama pentingnya dengan ketepatan.",
  "Air yang menguap bisa kemudian mengembun dan jatuh sebagai curah hujan.",
  "Penguapan → kondensasi → curah hujan → pengumpulan di sumber air",
  "Penguapan dan kondensasi juga merupakan perubahan wujud.",
  "Penguapan dari laut tanpa curah hujan yang kembali",
  "Penguapan meningkat saat suhu naik.",
  "Penguapan adalah perubahan dari cair ke gas—misalnya, air menjadi uap air saat dipanaskan.",
  "Penguapan adalah tahap utama pertama dari siklus air.",
  "Penguapan yang didorong oleh panas dari Matahari",
  "Penguapan, kondensasi, dan curah hujan adalah langkah kunci.",
  "Penguapan, kondensasi, curah hujan, dan aliran kembali ke samudra dan daratan",
  "Pohon hijau abadi mempertahankan daun lebih lama.",
  "Setiap hewan memiliki kebutuhan dasar.",
  "Setiap hewan berhibernasi dengan cara yang sama persis",
  "Setiap hewan membutuhkan makanan, air, dan kondisi yang sesuai seperti tempat berlindung dan suhu agar tetap sehat.",
  "Setiap hewan berubah menjadi produsen",
  "Setiap burung membutuhkan makanan yang sama persis",
  "Setiap percobaan dimulai dengan pertanyaan atau ide untuk diuji.",
  "Setiap hewan hidup membutuhkan makanan untuk energi dan air agar tubuhnya tetap bekerja. Tanpa makanan, hewan tidak bisa tumbuh atau bergerak. Tanpa air, sel-selnya tidak bisa berfungsi.",
  "Setiap bahan berperilaku sama persis",
  "Setiap bahan memiliki sifat yang berbeda.",
  "Setiap bahan memiliki titik beku sendiri.",
  "Setiap bahan memiliki titik leleh sendiri.",
  "Setiap planet di tata surya kita mengorbit Matahari, ditahan pada jalurnya oleh gravitasi Matahari. Beberapa planet berbatu dan kecil, seperti Bumi dan Mars, sementara yang lain adalah bola gas raksasa, seperti Jupiter dan Saturnus. Tetapi kedelapan planet berbagi bintang yang sama — Matahari.",
  "Setiap sel darah merah secara permanen",
  "Setiap tindakan kecil membantu.",
  "Setiap tahap tampak sama persis",
  "Setiap kali kamu menghirup, paru-parumu terisi udara dan mengalirkan oksigen ke aliran darahmu.",
  "Setiap variabel diubah bersama-sama",
  "Pilihan sehari-hari yang membakar lebih sedikit bahan bakar membantu mengurangi polusi udara.",
  "Setiap orang bisa membantu menjaga tempat luar ruangan tetap bersih dan aman.",
  "Setiap orang bisa membantu melindunginya.",
  "Setiap orang bisa membantu lingkungan dengan berhati-hati dalam menggunakan sumber daya.",
  "Setiap orang bisa membantu pelestarian.",
  "Semuanya sekaligus",
  "Segala sesuatu yang sama sekali dikeluarkan dari percobaan.",
  "Segala sesuatu yang TIDAK termasuk dalam percobaan sama sekali.",
  "Segala sesuatu yang tidak kamu uji tetap sama (jumlah air, suhu, waktu mencampur)",
  "Bukti menjadi lebih jelas dengan perbandingan.",
  "Bukti bisa mendukung hipotesis atau menunjukkan bahwa hipotesis itu tidak didukung.",
  "Bukti dari percobaan mendukung kesimpulan.",
  "Bukti lebih penting daripada benar di kali pertama.",
  "Bukti lebih penting daripada hanya menebak.",
  "Bukti bisa mendukung atau menolak hipotesis.",
  "Detail yang tepat tidak pernah penting jika hasilnya terlihat jelas",
  "Contohnya termasuk kelinci di musim dingin dan katak di daun hijau.",
  "Contohnya termasuk zebra, macan tutul, dan gurita.",
  "Menukar gas antara darah dan udara",
  "Menukar gas dengan udara dan memindahkan oksigen ke dalam darah",
  "Menukar gas—mengambil oksigen dan melepaskan karbon dioksida",
  "Menukar oksigen dan karbon dioksida dengan udara",
  "Ekskresi mengeluarkan sisa yang berbahaya.",
  "Ekskresi mengeluarkan limbah dari tubuh.",
  "Organ ekskresi mengelola limbah.",
  "Olahraga bisa memperkuat kebugaran kardiovaskular.",
  "Olahraga membantu menjaga otot tetap kuat.",
  "Olahraga membantu otot tetap kuat.",
  "Olahraga adalah bagian dari gaya hidup sehat.",
  "Olahraga membuat jantung dan paru-paru bekerja lebih keras.",
  "Olahraga menaikkan denyut jantung untuk sementara.",
  "Olahraga menaikkan kebutuhan oksigen tubuh.",
  "Olahraga menghentikan pemompaan jantung.",
  "Olahraga, tidur, dan nutrisi bekerja bersama.",
  "Eksoskeleton berada di luar tubuh.",
  "Harapan saja bisa mengubah bagaimana orang melaporkan perasaan, bahkan tanpa efek obat yang nyata",
  "Desain percobaan sama pentingnya dengan melakukan langkah-langkahnya.",
  "Keselamatan percobaan berarti berhati-hati dan memeriksa bahwa semuanya aman sebelum, selama, dan setelah percobaan.",
  "Percobaan adalah cara ilmiah untuk belajar.",
  "Percobaan melarang menulis apa pun.",
  "Percobaan membantu kita belajar tentang dunia, menguji ide, memahami cara kerja sesuatu, dan menemukan hal baru.",
  "Percobaan membantu kita belajar dengan menguji ide secara hati-hati dan adil.",
  "Percobaan membantu kita belajar.",
  "Percobaan tidak pernah menggunakan pengamatan apa pun.",
  "Percobaan harus dilakukan dengan aman.",
  "Percobaan dimulai dengan pertanyaan dan prediksi.",
  "Percobaan menguji bagaimana mengubah satu variabel memengaruhi variabel lain.",
  "Percobaan yang mengubah satu variabel pada satu waktu menghasilkan hasil yang lebih mudah ditafsirkan dan dipercaya.",
  "Percobaan dengan orang harus selalu melewatkan persetujuan",
  "Kepunahan bisa terjadi karena banyak alasan.",
  "Digit tambahan setelah desimal tidak membuat angka menjadi benar. Kalibrasi memperbaiki kesalahan skala; resolusi hanya menggambarkan kepekaan terhadap perubahan kecil.",
  "Air ekstra mengubah kadar oksigen di tanah dan memengaruhi mikroba tanah.",
  "Habitat ekstrem menuntut adaptasi ekstrem.",
  "Perlindungan mata adalah bagian dari keselamatan luar ruangan.",
  "Kacamata",
  "Mata adalah organ indera yang lembut.",
  "Mata mendeteksi cahaya dan mengirim sinyal saraf ke otak, yang membentuk gambar yang kamu lihat.",
  "Mata menerima cahaya agar otak bisa membentuk gambaran tentang apa yang ada di sekitar kita.",
  "Mata.",
  "Plastik pabrik yang hanya berasal dari penyimpanan minyak",
  "Kelompok yang adil membuat perbandingan bermakna.",
  "Uji yang adil mengontrol kondisi dengan hati-hati.",
  "Uji yang adil membantu menunjukkan sebab dan akibat.",
  "Uji yang adil mengisolasi satu faktor.",
  "Uji yang adil membutuhkan perbandingan yang dipikirkan dengan baik.",
  "Keadilan berarti mengisolasi satu faktor. Jika tidak, perbedaan bisa berasal dari keberuntungan atau kondisi tersembunyi, bukan dari metode.",
  "Pertumbuhan cepat membuktikan tanah dan air tidak pernah perlu dipantau",
  "Gerakan cepat tanpa perubahan penampilan",
  "Gerakan cepat tanpa kecocokan dengan latar belakang",
  "Sinyal cepat membantu tubuh merespons dengan cepat.",
  "Angin kencang tanpa tetesan yang terkumpul",
  "Pernapasan lebih cepat membantu memasukkan lebih banyak udara.",
  "Lapisan lemak menjebak panas di laut yang dingin. Isolasi penting di tempat air menarik panas dengan cepat.",
  "Bulu bertindak seperti mantel. Mengembangkannya menjebak udara yang membantu menahan panas tubuh.",
];

if (en.length !== id.length) {
  console.error("LENGTH MISMATCH", en.length, id.length);
  process.exit(1);
}
const map = Object.fromEntries(en.map((e, i) => [e, id[i]]));
fs.writeFileSync(path.join(dir, "map-chunk-8.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("map-chunk-8 keys", Object.keys(map).length);
