import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(dir, "strings-chunk-10.json"), "utf8"));

const id = [
  "Kaca selalu mengapung di air apa pun bentuknya.",
  "Kaca menghantarkan listrik lebih baik daripada logam apa pun.",
  "Kaca adalah bahan tembus pandang, yang berarti cahaya lewat lurus melaluinya. Sifat itu membuatnya berguna untuk jendela, kacamata, dan botol di mana kamu perlu melihat isi di dalamnya. Tidak semua bahan meneruskan cahaya — kayu dan logam, misalnya, buram.",
  "Kaca tembus pandang. Kamu bisa melihat melaluinya.",
  "Toples kaca dari daur ulang kertas",
  "Kaca.",
  "Pemanasan global mengacu pada kenaikan suhu rata-rata Bumi yang berlangsung lama, bukan satu siang yang hangat.",
  "Mengalami metamorfosis dengan ciri tubuh yang berubah",
  "Kesimpulan yang baik dimulai dari pengamatan dan catatan yang hati-hati.",
  "Data yang baik mendukung keputusan publik.",
  "Drainase yang baik membantu banyak tanaman hias.",
  "Pilihan makanan yang baik mendukung pertumbuhan dan energi.",
  "Grafik yang baik menunjukkan variabel terikat versus variabel bebas.",
  "Kebiasaan yang baik meningkatkan kualitas data.",
  "Hipotesis yang baik memandu apa yang diukur. Percobaan kemudian menghasilkan bukti tentang prediksi.",
  "Penafsiran yang baik diperiksa terhadap catatan asli.",
  "Pencahayaan yang baik dan istirahat mendukung kenyamanan mata.",
  "Metode yang baik membangun kepercayaan pada hasil.",
  "Catatan yang baik membantu kamu membandingkan hasil, mengulang percobaan, dan mendukung kesimpulan dengan bukti.",
  "Catatan yang baik membuat percobaan lebih mudah diulang.",
  "Catatan yang baik mendukung analisis nanti.",
  "Nutrisi yang baik mendukung pertumbuhan dan kesehatan.",
  "Pengamatan yang baik berpegang pada bukti dari indera dan alat.",
  "Perencanaan yang baik datang sebelum mengukur.",
  "Rencana yang baik meningkatkan keadilan dan keselamatan.",
  "Postur yang baik membantu melindungi punggung.",
  "Persiapan yang baik membuatmu lebih aman dan hasil lebih jelas. Mengetahui rencana membantu percobaan berjalan lancar.",
  "Penalaran yang baik memeriksa penjelasan alternatif.",
  "Catatan yang baik mendukung analisis.",
  "Pengelolaan tanah yang baik mengurangi erosi.",
  "Studi yang baik memisahkan efek perlakuan dari konteks psikologis.",
  "Ambil peralatan kaca panas dengan tangan kosong untuk menguji panas.",
  "Font judul grafik",
  "Grafik dan bagan menyampaikan hasil kepada orang lain.",
  "Grafik melarang label apa pun.",
  "Grafik membantu orang memahami data.",
  "Grafik mengubah angka menjadi gambaran visual. Tren, puncak, dan lembah sering lebih mudah dilihat dalam grafik.",
  "Rumput dan tumbuhan lain",
  "Rumput dan tumbuhan",
  "Tarikan gravitasi dari Bulan dan Matahari, ditambah posisi Bumi relatif terhadap keduanya",
  "Gravitasi bekerja pada massa besar, dan air merespons dengan bergeser.",
  "Gravitasi yang menarik semua benda ke bawah ke tanah",
  "Daun hijau sering melakukan fotosintesis.",
  "Tumbuhan hijau terlihat hijau karena mengandung klorofil, yang menerima sinar matahari.",
  "Tumbuhan hijau bergantung pada fungsi daun.",
  "Tumbuhan hijau menggunakan sinar matahari untuk membuat makanan, jadi mereka menghasilkan energi yang memulai banyak rantai makanan.",
  "Gas rumah kaca menyerap semua sinar matahari yang masuk sehingga siang dan malam hilang",
  "Gas rumah kaca memasukkan energi gelombang pendek dan menjebak lebih banyak panas gelombang panjang, sehingga keseimbangan menjadi lebih hangat. Kuncinya adalah penjeratan panas yang lebih kuat, bukan sekadar “Matahari lebih sedikit.”",
  "Gas rumah kaca seperti karbon dioksida dan uap air menjebak panas di atmosfer.",
  "Penutup tanah melindungi tanah dari percikan hujan.",
  "Air tanah mengikuti sistem hidrologi terhubung yang dibagi di suatu wilayah",
  "Air tanah tidak pernah bergerak antar titik",
  "Menumbuhkan bulu alih-alih sisik di samudra",
  "Menumbuhkan tulang tengkorak baru setiap jam",
  "Menumbuhkan tumbuhan tanpa air atau cahaya",
  "Menumbuhkan gigi dari kayu",
  "Menumbuhkan kerangka kedua semalaman",
  "Menumbuhkan insang di punggung mereka",
  "Menumbuhkan gigi baru dari sinar matahari",
  "Arah pertumbuhan bisa meningkatkan kelangsungan hidup.",
  "Pertumbuhan adalah proses alami.",
  "Pertumbuhan seiring waktu tanpa kelahiran atau reproduksi",
  "Pertumbuhan tanpa menggunakan cahaya atau pigmen hijau",
  "Menebak jawaban tanpa melihat",
  "Menebak liar dan melewatkan semua petunjuk.",
  "Menebak cerita tanpa bukti",
  "Menebak ukuran tanpa penggaris atau timbangan",
  "Menebak tanpa melihat",
  "H2O tetap air dalam wujud padat, cair, atau gas.",
  "Habitat saja tidak menentukan kelompok hewan.",
  "Habitat saja tidak memberi tahu kamu kelompoknya.",
  "Habitat dan perilaku membantu mengatur panas tubuh.",
  "Perubahan habitat biasanya tidak berpengaruh",
  "Konservasi habitat adalah strategi perlindungan inti.",
  "Fragmentasi habitat adalah terpecahnya kawasan alami besar menjadi potongan-potongan lebih kecil yang terputus.",
  "Kehilangan habitat karena menebang hutan, membangun, atau polusi menghilangkan apa yang dibutuhkan hewan. Populasi bisa menyusut atau hilang secara lokal.",
  "Kehilangan habitat adalah ancaman besar bagi spesies.",
  "Kehilangan habitat menghilangkan sumber daya yang dibutuhkan hewan, sehingga populasi bisa menurun atau hewan harus pindah.",
  "Kehilangan habitat mengancam banyak spesies.",
  "Kebutuhan habitat bisa berubah selama pertumbuhan.",
  "Perlindungan habitat membantu satwa liar dan manusia.",
  "Perlindungan habitat menjaga ekosistem berfungsi. Tanpa habitat, bahkan hewan yang beradaptasi baik tidak bisa berkembang.",
  "Habitat membentuk adaptasi hewan.",
  "Habitat mencakup makanan dan tempat berlindung.",
  "Habitat mencakup hutan, gurun, samudra, dan padang rumput.",
  "Habitat harus menyediakan air dengan cara tertentu.",
  "Habitat memasok apa yang dibutuhkan makhluk hidup untuk bertahan hidup.",
  "Rambut",
  "Rambut bisa banyak warna.",
  "Rambut mencerna sinyal",
  "Folikel rambut berdetak seperti drum",
  "Rambut terus tumbuh.",
  "Rambut di kepala membantu melindungi dan menghangatkan kepala.",
  "Tangan membantu bekerja, bermain, dan merawat diri.",
  "Tangan membantu kamu memegang benda, merasakan tekstur, dan melakukan tugas hati-hati dengan jari.",
  "Mencuci tangan adalah kebiasaan kesehatan yang sederhana.",
  "Mencuci tangan mengurangi kuman yang bisa masuk ke sistem pencernaan.",
  "Keras dan lembut selalu terasa sama",
  "Bahan keras menahan tekanan, pemotongan, dan pematahan (seperti batu). Bahan lembut mudah ditekan dan dibentuk ulang (seperti kapas).",
  "Permukaan keras mengalirkan hujan ke saluran dan sungai lebih cepat, sehingga permukaan air bisa naik dengan cepat.",
  "Kerja keras menguras persediaan energi dan memberi tekanan pada serat otot. Istirahat, air, dan nutrisi mendukung pemulihan.",
  "Bahan lebih keras bisa menggores yang lebih lembut. Uji gores yang hati-hati membantu membandingkan kekerasan.",
  "Kekerasan dan kelembutan adalah sifat yang bisa kamu rasakan: bahan lembut lebih mudah melengkung, sementara yang keras menahan pelengkungan atau bisa patah.",
  "Kekerasan bergantung hanya pada warna, bukan pada ketahanan terhadap goresan",
  "Kekerasan adalah sifat bahan.",
  "Kekerasan adalah salah satu sifat itu.",
  "Merugikan air, hewan, dan tempat pesisir",
  "Bahan berbahaya di udara yang merusak kesehatan dan lingkungan",
  "Bahan berbahaya di udara yang menyakiti kesehatan dan lingkungan",
  "Panen selalu tumbuh dalam garis lurus sempurna selamanya",
  "Memiliki insang dan tubuh yang cocok untuk berenang di air",
  "Memiliki paru-paru hanya untuk memanjat pohon",
  "Memiliki hanya satu spesies selalu lebih baik",
  "Limbah berbahaya tidak boleh dibuang ke sampah biasa.",
  "Hulu sungai tidak pernah punya polusi, jadi tidak ada hubungan ke hilir",
  "Makan sehat membantu anak tumbuh dengan baik.",
  "Makan sehat mendukung energi dan pertumbuhan.",
  "Ekosistem sehat sering memiliki banyak spesies.",
  "Ginjal sehat membantu menjaga kimia darah seimbang.",
  "Ginjal sehat mendukung darah yang bersih dan seimbang.",
  "Tumbuhan sehat membutuhkan sinar matahari, air, udara, dan nutrisi. Tanpa itu, banyak tumbuhan tumbuh buruk atau mati.",
  "Rutinitas sehat mendukung energi, pertumbuhan, dan sistem tubuh yang kuat.",
  "Tanah sehat mengandung lebih banyak nutrisi, yang membantu tumbuhan tumbuh lebih baik.",
  "Tanah sehat membantu akar bekerja dengan baik.",
  "Tanah sehat tidak boleh tetap basah kuyup sepanjang waktu bagi kebanyakan tumbuhan.",
  "Tanah sehat mendukung pertumbuhan tumbuhan.",
  "Gigi sehat membantu kamu mengunyah makanan dengan baik.",
  "Gigi sehat membantu kamu makan dan berbicara.",
  "Gigi sehat membutuhkan perawatan harian.",
  "Pembuluh sehat mendukung pengantaran oksigen.",
  "Mendengar suara",
  "Pendengaran sangat penting bagi banyak kelelawar yang aktif di malam hari.",
  "Pendengaran adalah salah satu dari lima indera.",
  "Pendengaran berharga dan tidak selalu mudah diperbaiki.",
  "Mendengar suara di bawah tanah",
  "Jantung",
  "Otot jantung bekerja terus-menerus.",
  "Denyut jantung berubah dengan istirahat dan olahraga.",
  "Denyut jantung adalah indikator kebugaran yang berguna.",
  "Denyut jantung adalah denyut per menit.",
  "Denyut jantung merespons aktivitas dan istirahat.",
  "Denyut jantung naik dengan olahraga.",
  "Denyut jantung mendorong gelombang darah melalui arteri.",
  "Panas selalu mengalir dari daerah yang lebih hangat ke daerah yang lebih sejuk. Pergerakan energi ini disebut perpindahan panas.",
  "Panas bisa membakar kulit dengan cepat. Guru menetapkan aturan—seperti menggunakan penjepit dan menunggu pendinginan—untuk mencegah cedera.",
  "Panas hanya bisa bergerak melalui air dan tidak ada yang lain.",
  "Energi panas mendorong banyak perubahan fase.",
  "Energi panas membuat es mencair. Tempat yang lebih hangat memindahkan panas lebih cepat ke es.",
  "Energi panas berpindah dari benda panas ke benda yang lebih sejuk.",
  "Pemuaian panas hanya dari gurun, tanpa pengaruh Bulan atau Matahari",
  "Panas membekukan semua cairan tubuh",
  "Panas dari matahari memberi molekul air cukup energi untuk lepas dari permukaan cairan dan naik ke udara sebagai uap air yang tidak terlihat. Ini disebut penguapan.",
  "Panas dari matahari memberi molekul air energi ekstra, sehingga mereka menguap lebih cepat dari wadah di bawah matahari.",
  "Panas memberi molekul air lebih banyak energi untuk bergerak, memungkinkan mereka berpisah dan mengelilingi lebih banyak partikel zat terlarut, sehingga lebih banyak zat larut.",
  "Panas bergerak dari daerah yang lebih hangat ke daerah yang lebih sejuk.",
  "Keselamatan panas adalah bagian dari tanggung jawab laboratorium.",
  "Panas tinggal di satu tempat dan tidak pernah bergerak sendiri.",
  "Memanaskan tubuh dengan membakar tulang",
  "Perpindahan panas terjadi dalam tiga cara: konduksi, konveksi, dan radiasi.",
  "Panaskan sebanyak mungkin",
  "Pemanasan bisa mengubah lilin dari padat menjadi cair. Ini adalah perubahan wujud fisik.",
  "Perbedaan pemanasan tidak terkait dengan pergerakan udara",
  "Pemanasan memberi molekul air cukup energi untuk lepas ke udara sebagai gas.",
  "Pemanasan atau pendinginan bisa mengubah wujud suatu bahan.",
  "Pemanasan atau pendinginan air bisa mengubah wujudnya.",
  "Pemanasan yang sepenuhnya menyebarkan uap air menjauh",
  "Pemanasan yang mencairkan es menjadi air",
  "Pemanasan tanpa perubahan wujud",
  "Pemanasan tanpa cairan berubah menjadi udara",
  "Batu es hujan es yang berat selalu di tanah",
  "Logam berat",
  "Hujan lebat selalu segera melemahkan tanah tanpa faktor lain",
  "Hujan lebat di tanah gundul atau padat bisa mencuci pupuk dan bahan kimia lain ke limpasan, aliran sungai, dan waduk.",
  "Sepatu batu yang berat",
  "Helm menambah perlindungan ekstra saat berolahraga.",
  "Ciri yang membantu menjadi lebih umum selama banyak generasi.",
  "Membantu ikan bergerak dan tetap seimbang di air",
  "Ayam betina",
  "Herbivora dan karnivora adalah bagian dari rantai makanan dan jaring makanan.",
  "Herbivora adalah bagian penting dari rantai makanan.",
  "Herbivora sering menjadi mangsa karnivora.",
  "Herbivora memakan bahan tumbuhan.",
  "Herbivora memakan tumbuhan.",
  "Herbivora makan bahan tumbuhan. Gigi dan pencernaan kelinci cocok untuk diet itu.",
  "Herbivora makan dari produsen.",
  "Herbivora sering memiliki gigi yang cocok untuk mengunyah tumbuhan.",
  "Herbivora yang memakan tumbuhan",
  "Herbivora tidak akan membutuhkan makanan setelahnya.",
  "Herbivora, karnivora, dan omnivora semuanya berperan penting dalam jaring makanan.",
  "Herbivora, karnivora, dan omnivora memiliki diet yang berbeda.",
  "Hibernasi membantu hewan bertahan di musim dingin.",
  "Hibernasi membantu mereka bertahan di musim dingin.",
  "Hibernasi di dalam kulit biji",
  "Hibernasi adalah tidur musim dingin yang dalam yang membantu hewan menghemat energi saat makanan langka.",
  "Sembunyikan metode dari semua orang",
  "Sembunyikan kesalahan dan buat angka.",
  "Sembunyikan tumpahan agar tidak ada yang memperhatikan",
  "Resolusi tinggi tidak memperbaiki kesalahan pengaturan sistematis",
  "Suhu lebih tinggi, pengadukan, dan potongan lebih kecil",
  "Kecepatan angin lebih tinggi saja, tanpa perubahan suhu",
  "Menahan kerangka diam tanpa gerakan",
  "Tahan napas sampai berhenti.",
  "Memegang dan menuang cairan dengan hati-hati",
  "Lembar kerja pekerjaan rumah",
  "Pekerjaan rumah, Wi-Fi, dan headphone",
  "Kejujuran tentang hasil penting.",
  "Kejujuran adalah bagian dari sains yang baik.",
  "Hormon adalah pembawa pesan kimia dari kelenjar. Mereka membantu mengontrol pertumbuhan, metabolisme, suasana hati, dan lainnya.",
  "Hormon sering bekerja lambat tetapi bisa punya efek yang bertahan lama.",
  "Kuda",
  "Kuda adalah hewan yang kuat dan cepat.",
  "Kuda bisa berlari sangat cepat. Mereka memiliki kaki yang kuat dan panjang.",
  "Permukaan panas dan alat tajam membutuhkan perhatian ekstra.",
  "Air panas mengubah garam padat langsung menjadi gas tanpa melarutkannya",
  "Cuaca panas dan olahraga meningkatkan kebutuhan minum.",
  "Cuaca panas meningkatkan kebutuhan cairan.",
  "Cuaca panas menghilangkan kebutuhan minum",
  "Kucing rumah",
  "Bagaimana adaptasi dan kelangsungan hidup saling berhubungan?",
  "Bagaimana hewan berbeda dari tumbuhan?",
  "Bagaimana unta beradaptasi dengan kehidupan gurun yang kering?",
  "Bagaimana tumbuhan terhubung dengan udara?",
  "Bagaimana musim terkait dengan sudut sinar matahari di suatu wilayah?",
  "Bagaimana hewan bisa membantu tumbuhan menyebarkan biji?",
  "Bagaimana membangun di atas lahan basah tanpa perlindungan terutama bisa merugikan hewan?",
  "Bagaimana kamuflase bisa membantu hewan bertahan hidup?",
  "Bagaimana kamuflase bisa membantu predator dan mangsa?",
  "Bagaimana pupuk bisa membantu tumbuhan?",
  "Bagaimana bulu bisa membantu mamalia?",
  "Bagaimana orang bisa mengurangi polusi udara dalam kehidupan sehari-hari?",
  "Bagaimana tumbuhan di sepanjang aliran sungai bisa membantu menyaring air yang mengalir secara alami?",
  "Bagaimana menyusutnya penutup es dan digantikannya dengan air laut yang lebih gelap, pada prinsipnya, bisa mempercepat pemanasan regional?",
  "Bagaimana sampah bisa terkait dengan tanah kebun?",
  "Bagaimana pohon bisa membantu burung?",
  "Bagaimana kita bisa mengelompokkan hewan berdasarkan ciri tubuh atau cara mereka bergerak?",
  "Bagaimana kita bisa tahu tumbuhan itu hidup, tidak seperti batu?",
  "Bagaimana angin bisa membantu beberapa biji?",
  "Bagaimana kamu bisa membandingkan bahan mana yang lebih keras?",
  "Bagaimana kamu bisa membantu menjaga gigi tetap sehat?",
  "Bagaimana kamu bisa membantu melindungi alam?",
  "Bagaimana kamu bisa melindungi matamu di luar ruangan pada hari yang sangat cerah?",
  "Bagaimana kamu bisa memisahkan pasir dari air?",
  "Bagaimana kamu bisa membedakan konduktor listrik dari isolator di kelas dengan cara sederhana?",
  "Bagaimana kamu bisa membedakan benda keras dari benda lembut?",
  "Bagaimana kamu bisa tahu bahwa suatu permukaan kasar?",
  "Bagaimana kamu bisa tahu bahwa suatu bahan tembus pandang?",
  "Bagaimana awan terbentuk selama badai",
  "Bagaimana cakar kucing membantunya?",
  "Bagaimana hewan di lingkungan gurun panas bertahan dengan sangat sedikit air?",
  "Bagaimana hewan bertahan hidup di lingkungannya?",
];

if (en.length !== id.length) {
  console.error("LENGTH MISMATCH", en.length, id.length);
  process.exit(1);
}
const map = Object.fromEntries(en.map((e, i) => [e, id[i]]));
fs.writeFileSync(path.join(dir, "map-chunk-10.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("map-chunk-10 keys", Object.keys(map).length);
