import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const en = JSON.parse(fs.readFileSync(path.join(dir, "strings-chunk-9.json"), "utf8"));

const id = [
  "Bulu juga membantu.",
  "Bulu dan tulang mamalia berongga saja",
  "Bulu adalah ciri utama burung. Ikan biasanya memiliki sisik dan menggunakan insang di air.",
  "Bulu adalah ciri utama burung. Bulu membantu terbang, mengarahkan, dan tetap hangat.",
  "Bulu untuk terbang di bawah tanah",
  "Bulu membantu terbang dan tetap hangat.",
  "Bulu membantu terbang dan tetap hangat.",
  "Berikan setiap ikan makanan yang sehat",
  "Berikan hewan liar makanan matang agar pengunjung bisa mendekat",
  "Kaki",
  "Pupuk menambahkan nutrisi seperti nitrogen dan fosfor ke tanah agar tumbuhan bisa tumbuh lebih baik.",
  "Pupuk bisa membantu tumbuhan tumbuh lebih kuat.",
  "Pupuk tidak pernah memengaruhi tumbuhan",
  "Pupuk menyediakan mineral dan nutrisi yang mendukung pertumbuhan tumbuhan yang sehat jika digunakan dengan hati-hati.",
  "Lebih sedikit perjalanan mobil sendirian berarti lebih sedikit emisi knalpot.",
  "Serat membantu pencernaan.",
  "Ladang selalu menyerap lebih banyak karbon dioksida daripada hutan sejak hari pertama",
  "Isi sumber air dengan sebanyak mungkin bahan alami.",
  "Terisi udara agar oksigen bisa masuk ke darah",
  "Terisi makanan untuk pencernaan",
  "Merekam selalu membatalkan fisika kelas",
  "Menyaring udara",
  "Menyaring plankton laut dengan insang",
  "Menyaring racun hanya melalui kulit, tanpa hubungan dengan paru-paru",
  "Menyaring darah seperti ginjal",
  "Menyaring darah seperti ginjal",
  "Menyaring darah melindungi lingkungan dalam tubuh. Urine membawa limbah yang dibuang keluar tubuh.",
  "Penyaringan membutuhkan aliran darah yang stabil.",
  "Menyaring limbah dari darah",
  "Filtrasi memisahkan padatan dari cairan.",
  "Filtrasi bekerja ketika satu bahan tidak larut.",
  "Mencari iklim dan sumber makanan yang lebih baik di musim yang berbeda",
  "Jari membantu kita memegang benda.",
  "Ujung jari sangat peka terhadap sentuhan.",
  "Selesaikan segera tanpa menulis apa pun",
  "Sirip dan tubuh yang ramping membantu ikan berenang dengan baik di air.",
  "Sirip dan tubuh berbentuk torpedo",
  "Sirip adalah bagian tubuh yang membantu ikan bergerak di air dan tetap stabil.",
  "Sirip adalah adaptasi berenang yang membantu ikan bergerak di air.",
  "Sirip membantu ikan bergerak dan menjaga keseimbangan.",
  "Sirip membantu ikan berenang dan mengarahkan.",
  "Sirip membantu ikan berenang, berbelok, dan tetap stabil di air.",
  "Sirip membantu berenang.",
  "Api bisa menyebar melalui tumbuhan kering.",
  "Ikan selalu berlipat tiga jumlahnya berapa pun tekannya",
  "Ikan beradaptasi untuk kehidupan di air. Insang memungkinkan mereka mendapat oksigen tanpa naik ke darat.",
  "Ikan beradaptasi untuk kehidupan di air.",
  "Ikan beradaptasi untuk berenang.",
  "Tubuh ikan beradaptasi untuk kehidupan di air.",
  "Tubuh ikan berbentuk untuk kehidupan di air.",
  "Ikan bernapas dengan insang.",
  "Ikan yang mengembuskan api",
  "Ikan menumbuhkan bulu untuk terbang",
  "Ikan memiliki bulu dan terbang jarak jauh",
  "Ikan di air",
  "Ikan hidup di air dan menggunakan sirip untuk berenang.",
  "Ikan hidup di air.",
  "Ikan hidup di air. Insang membantu mereka mengambil oksigen dari air.",
  "Ikan hidup di air. Mereka menggunakan sirip untuk berenang dan insang untuk mengambil oksigen dari air.",
  "Ikan membutuhkan oksigen seperti kita. Insang menarik oksigen dari air agar ikan bisa bernapas di bawah air.",
  "Ikan yang membutuhkan kaki panjang untuk gurun",
  "Ikan berenang di air. Siripnya membantu mereka bergerak.",
  "Ikan mengambil oksigen terlarut dari air melalui insang dan memiliki tubuh berbentuk untuk berenang.",
  "Ikan menggunakan insang di air; lumba-lumba adalah mamalia dengan paru-paru.",
  "Tekanan penangkapan ikan bisa berubah seiring waktu.",
  "Lima",
  "Lima: penglihatan, pendengaran, penciuman, pengecapan, dan perabaan",
  "Awan tetap tanpa curah hujan ke tanah",
  "Berkepak seperti sayap agar tumbuhan bisa terbang",
  "Berkepak untuk menerbangkan tumbuhan melintasi ladang",
  "Risiko banjir terkait dengan hujan dan penutup lahan.",
  "Ciri bunga sering menarik penyerbuk.",
  "Kunjungan ke bunga bisa membantu lebah dan tumbuhan.",
  "Bunga penting bagi banyak siklus hidup tumbuhan.",
  "Bunga sering berwarna-warni dan menarik serangga.",
  "Bunga sering berwarna-warni.",
  "Bunga menarik serangga yang memindahkan serbuk sari. Setelah itu, biji bisa terbentuk dan tumbuh menjadi tumbuhan baru.",
  "Bunga mengandung bagian reproduksi. Setelah penyerbukan dan pembuahan, biji (sering di dalam buah) bisa terbentuk.",
  "Bunga membantu tumbuhan berkembang biak.",
  "Bunga membantu tumbuhan berkembang biak. Mengambil terlalu banyak bisa merugikan populasi tumbuhan dan hewan yang menggunakannya.",
  "Bunga mengubah darah menjadi air",
  "Air yang mengalir selalu bersih apa pun tumbuhan di dekatnya",
  "Bulu yang dikembangkan menjebak udara hangat di dekat tubuh mereka.",
  "Menerbangkannya ke kebun baru",
  "Terbang jarak jauh di udara",
  "Melipat selembar kertas tanpa membakarnya",
  "Melipat kertas mengubah bentuknya, tetapi tetap kertas. Membakar, berkarat, dan memanggang sering membuat bahan baru.",
  "Ikuti petunjuk guru dan kenakan pelindung yang diperlukan.",
  "Makanan (gula) menggunakan cahaya, air, dan karbon dioksida",
  "Makanan dan perawatan",
  "Rantai makanan tidak menghubungkan makhluk hidup",
  "Rantai makanan mencakup predator dan mangsa.",
  "Rantai makanan menunjukkan siapa memakan siapa.",
  "Rantai makanan dimulai dari produsen.",
  "Makanan hilang selamanya",
  "Energi makanan bagi hewan yang memakannya",
  "Energi makanan yang dibuat dari sinar matahari",
  "Energi makanan berhenti berarti selamanya",
  "Makanan untuk energi dan air agar tetap hidup.",
  "Makanan memberi hewan energi yang mereka butuhkan untuk bergerak, tumbuh, dan tetap hangat.",
  "Makanan memberi tubuhmu energi dan bahan bangunan. Makanan yang berbeda membantu kamu tumbuh, bergerak, dan berpikir.",
  "Makanan dikunyah, dipecah di lambung, dan diserap di usus. Limbah keluar dari tubuh.",
  "Makanan hanya untuk mengubah warna rambut.",
  "Makanan adalah sumber energi utama tubuh.",
  "Makanan tidak terkait dengan energi",
  "Makanan yang dibuat di daun memberi makan seluruh tumbuhan.",
  "Makanan bergerak melalui mulut, lambung, dan usus untuk dipecah dan diserap ke dalam darah",
  "Makanan menyediakan semua air yang dibutuhkan hewan, jadi mereka tidak pernah minum.",
  "Makanan menyediakan energi kimia. Pencernaan dan proses tubuh mengubah energi itu menjadi bahan bakar untuk bergerak, tumbuh, dan hangat.",
  "Makanan menyediakan energi untuk otak dan tubuh.",
  "Makanan memasok energi untuk aktivitas dan berpikir.",
  "Makanan berjalan dari mulut melalui saluran pencernaan.",
  "Makanan berjalan melalui jalur pencernaan.",
  "Variasi makanan menghilangkan kebutuhan akan air",
  "Jaring makanan lebih lengkap daripada rantai tunggal. Mereka menunjukkan bagaimana energi menghubungkan banyak tumbuhan dan hewan.",
  "Jaring makanan menjadi tidak terkait dengan energi.",
  "Jaring makanan menghubungkan banyak spesies.",
  "Jaring makanan menunjukkan bagaimana makhluk hidup saling bergantung.",
  "Jaring makanan menunjukkan banyak tautan makan.",
  "Jaring makanan dimulai dengan penangkapan energi.",
  "Makanan yang kamu makan",
  "Makanan, air, tempat berlindung, dan ruang cukup untuk bertahan hidup",
  "Untuk bernapas di bawah air",
  "Misalnya, paru-paru memasukkan oksigen, darah membawanya, dan otot menggunakannya untuk energi.",
  "Untuk terbang",
  "Untuk membuat oksigen",
  "Hanya untuk berenang",
  "Hutan juga memengaruhi iklim dan siklus air.",
  "Hutan adalah rumah bagi lebih dari separuh semua spesies darat di Bumi.",
  "Hutan adalah penyimpan karbon yang penting.",
  "Hutan penting hanya bagi hewan yang tinggal di dalamnya, bukan bagi manusia.",
  "Hutan kadang disebut 'paru-paru Bumi' karena menghasilkan begitu banyak oksigen.",
  "Hutan berguna hanya sebagai sumber bahan bangunan.",
  "Hutan tumbuh kembali segera setelah ditebang, jadi tidak ada kekhawatiran.",
  "Hutan menampung banyak spesies. Menebangnya menghilangkan rumah dan makanan.",
  "Hutan langsung berubah menjadi gurun hanya karena cahaya",
  "Hutan tidak pernah mendukung makhluk hidup",
  "Hutan menghasilkan oksigen, menyerap karbon dioksida, dan menyediakan habitat bagi tak terhitung tumbuhan dan hewan. Mereka juga membantu mengatur siklus air dan melindungi tanah.",
  "Hutan menghasilkan oksigen, menyediakan rumah bagi hewan, dan membantu menjaga udara dan air tetap bersih.",
  "Hutan mendukung banyak makhluk hidup.",
  "Hutan, gurun, kolam, dan samudra adalah habitat.",
  "Membentuk tulang tengkorak baru segera",
  "Pembakaran bahan bakar fosil melepaskan polutan.",
  "Angka empat tidak diizinkan dalam tabel data.",
  "Empat kaki membantu banyak hewan bergerak dengan cepat.",
  "Aktivitas bebas tanpa pertanyaan percobaan",
  "Membekukan sinar matahari saja",
  "Membekukan cairan menjadi padat",
  "Pembekuan terjadi saat suhu turun.",
  "Pembekuan adalah perubahan dari cair ke padat—misalnya, air menjadi es saat didinginkan.",
  "Membeku atau menguap dalam kondisi yang tepat",
  "Membeku, mencair, dan menguap mengubah wujud air tetapi tetap sebagai air.",
  "Air minum segar yang menetes turun dari awan",
  "Air tawar adalah sumber daya terbatas dan semua makhluk hidup membutuhkannya untuk bertahan hidup",
  "Air tawar adalah sumber daya terbatas. Menghematnya membantu manusia, pertanian, dan satwa liar.",
  "Air tawar terbatas, jadi kita perlu melindunginya untuk manusia dan alam",
  "Gesekan antara Bumi dan Bulan memperlambat Bumi di musim dingin dan mempercepatnya di musim panas",
  "Gesekan lebih besar di banyak permukaan kasar.",
  "Perkembangan katak mengubah berudu yang berenang menjadi dewasa berkaki empat. Ciri pernapasan dan gerakan berubah seiring tahap.",
  "Katak dan salamander adalah amfibi.",
  "Katak menetas sudah sebagai mamalia berbulu.",
  "Katak tidak pernah berubah bentuk saat tumbuh.",
  "Katak sering dimulai sebagai berudu di air dan kemudian lebih banyak hidup di darat sebagai dewasa.",
  "Katak memulai hidup sebagai biji di tanah.",
  "Dari meminum darah",
  "Dari menahan napas",
  "Dari berburu hewan",
  "Hanya dari batuan yang mencair",
  "Bukan dari tumbuhan.",
  "Dari batuan dan mineral di dasar danau.",
  "Dari duduk diam sepanjang hari",
  "Dari sinar matahari",
  "Dari makanan yang kamu makan",
  "Dari oksigen yang terlarut dalam air.",
  "Dari Matahari — tumbuhan dan alga menggunakan sinar matahari melalui fotosintesis untuk menghasilkan energi makanan.",
  "Dari air — semakin banyak air di danau, semakin banyak energi yang dihasilkan.",
  "Hanya dari menonton TV",
  "Buah mencerna makanan untuk tulang hewan.",
  "Buah tumbuh di dalam daun saat mendapat cukup sinar matahari.",
  "Buah membantu melindungi dan menyebarkan biji.",
  "Buah adalah bagian dari siklus hidup tumbuhan.",
  "Buah menghentikan tumbuhan membutuhkan cahaya.",
  "Jaringan buah tanpa embrio yang bisa tumbuh",
  "Pohon buah adalah produsen tumbuhan yang diandalkan manusia.",
  "Buah mengubah tumbuhan menjadi batu.",
  "Buah dan sayuran menyediakan nutrisi yang mendukung kesehatan dan pertumbuhan.",
  "Buah berkembang dari bunga tumbuhan setelah diserbuki.",
  "Buah membantu menyebarkan biji dengan menarik hewan yang memakannya.",
  "Buah membantu penyebaran biji dengan menarik hewan.",
  "Buah menyimpan biji. Hewan mungkin memakan buah dan membawa biji ke tempat baru, membantu tumbuhan menyebar.",
  "Buah sering melindungi dan membantu menyebarkan biji.",
  "Buah, kait, sayap, dan bentuk mengapung bisa membantu biji berkelana.",
  "Buah, sayuran, biji-bijian, dan protein masing-masing membantu dengan cara berbeda.",
  "Buah, sayuran, biji-bijian, protein, dan susu semuanya bisa berperan.",
  "Kegelapan penuh tanpa air",
  "Dokumentasi lengkap juga melindungi peneliti dari kesalahpahaman.",
  "Sepenuhnya menggantikan pekerjaan otak dan saraf",
  "Bulu dan lemak membantu menjebak panas agar mamalia bisa bertahan di habitat dingin.",
  "Bulu bisa menjebak panas dan melindungi kulit.",
  "Bulu membantu menahan panas tubuh.",
  "Bulu membantu menahan panas tubuh.",
  "Bulu adalah adaptasi untuk suhu dan perlindungan. Beberapa mamalia memiliki bulu lebih tebal di musim dingin.",
  "Bulu memungkinkan mamalia bernapas di bawah air dengan insang.",
  "Bulu membuat mamalia menghasilkan nektar bunga.",
  "Bulu menggantikan kebutuhan akan makanan.",
  "Bulu yang membuat madu",
  "Kucing berbulu",
  "Perawatan kebun menyesuaikan kebutuhan tumbuhan.",
  "Tukang kebun memberi tumbuhan apa yang mereka butuhkan.",
  "Pertukaran gas antara udara dan darah terjadi di dalam paru-paru.",
  "Pertukaran gas terjadi di paru-paru.",
  "Pertukaran gas di paru-paru mengubah oksigen dalam darah, yang kemudian menuju ke jaringan.",
  "Pertukaran gas di paru-paru mengisi sel darah merah dengan oksigen. Sirkulasi kemudian mengantarkan oksigen itu ke seluruh tubuh.",
  "Pertukaran gas menjaga sel tetap mendapat oksigen.",
  "Struktur pertukaran gas sesuai dengan lingkungan.",
  "Raksasa gas adalah planet sangat besar yang sebagian besar terdiri dari gas. Jupiter dan Saturnus adalah contoh raksasa gas di tata surya kita.",
  "Raksasa gas seperti Jupiter dan Saturnus adalah planet terbesar di tata surya kita.",
  "Gas tidak pernah menjadi wujud zat",
  "Gas masuk dan keluar daun melalui stomata.",
  "Gas seperti karbon dioksida dan metana menjebak panas. Terlalu banyak di antaranya menghangatkan planet.",
  "Geografi memengaruhi iklim.",
  "Perkecambahan adalah proses biji mulai bertunas dan tumbuh.",
  "Perkecambahan adalah saat biji mulai tumbuh.",
  "Perkecambahan adalah saat biji mulai tumbuh. Air dan suhu yang baik membantu tumbuhan kecil di dalamnya bangun.",
  "Perkecambahan memulai siklus hidup tumbuhan dari biji. Akar dan tunas muncul saat kondisi tepat.",
  "Kuman bisa hidup di tangan.",
  "Menjadi lebih besar atau lebih kecil tanpa reaksi kimia",
  "Insang memungkinkan bernapas di air.",
  "Insang dan sirip cocok untuk kehidupan di air. Bentuk tubuh sering mengurangi hambatan saat berenang.",
  "Insang dan bulu sekaligus sebagai dewasa di darat",
  "Insang adalah organ pernapasan untuk ikan.",
  "Insang dikhususkan untuk pertukaran gas di bawah air. Hewan peliharaan darat seperti anjing dan kucing menggunakan paru-paru.",
  "Insang untuk bernapas di bawah air",
  "Insang untuk bernapas di bawah air",
  "Insang membantu ikan menggonggong seperti anjing.",
  "Insang membantu ikan menumbuhkan bulu.",
  "Insang membantu ikan membuat madu.",
  "Insang membantu ikan mengambil oksigen dari air.",
  "Insang memungkinkan ikan bernapas di bawah air.",
  "Insang di paruh mereka",
  "Insang menarik oksigen terlarut dari air agar ikan bisa hidup di bawah air.",
  "Insang mengambil oksigen dari air agar ikan bisa bernapas.",
  "Insang yang mengambil oksigen dari air",
  "Insang untuk bernapas di darat",
  "Insang bekerja di bawah air.",
  "Berikan setiap bibit jumlah air berbeda tanpa mengukur",
  "Memberikan setiap spesies ruang baru tak terbatas secara otomatis",
  "Kelenjar membuat hormon.",
  "Kaca menyerap semua warna cahaya dan mengubahnya menjadi panas.",
  "Kaca selalu sepenuhnya menghalangi cahaya dan benar-benar buram.",
];

if (en.length !== id.length) {
  console.error("LENGTH MISMATCH", en.length, id.length);
  process.exit(1);
}
const map = Object.fromEntries(en.map((e, i) => [e, id[i]]));
fs.writeFileSync(path.join(dir, "map-chunk-9.json"), JSON.stringify(map, null, 2) + "\n", "utf8");
console.log("map-chunk-9 keys", Object.keys(map).length);
