/**
 * Modern Standard Arabic (ar-001) rebuilders for geometry question stems.
 * English is the authority; params/numbers/operators unchanged.
 * Generated by scripts/i18n/bootstrap-ar-001-stem-rebuilders.mjs — review instructional copy.
 */
import { containsHebrew, mapQuestionTextFields } from "../learning-question-content-locale.js";
import { resolveRegisteredContentPack } from "../../lib/content/resolve-registered-pack.js";
import {
  localizeGeometryConceptualQuestionAr001,
  localizeGeometryConceptualTextAr001,
} from "./geometry-conceptual.js";

const geometryContent =
  resolveRegisteredContentPack("ar-001", "learning", "geometry-content.json") || {};

export const GEOMETRY_PT_LABEL_OPTIONS = geometryContent.labelOptions;
export const GEOMETRY_SOLID_NAMES_PT = geometryContent.solidNames;

/** English-keyed solid aliases from content pack (no HE keys in this module). */
const SOLID_ALIASES = geometryContent.solidAliases || {};

/** Phrase HE→EN table cleared — generators emit English. */
const PHRASES = [];

/** English label options only — residual HE stems are stripped, not phrase-translated. */
const SHAPE_WORDS = {
  ...(geometryContent.shapeWords && !Object.keys(geometryContent.shapeWords).some((k) => /(?!)/.test(k))
    ? geometryContent.shapeWords
    : {}),
  ...SOLID_ALIASES,
};

function mapGeometryLabel(text) {
  const t = String(text ?? "").trim();
  if (SOLID_ALIASES[t]) return SOLID_ALIASES[t];
  if (SHAPE_WORDS[t]) return SHAPE_WORDS[t];
  for (const opts of Object.values(GEOMETRY_PT_LABEL_OPTIONS || {})) {
    if (Array.isArray(opts) && opts.includes(t)) return t;
  }
  return null;
}

function isNearlyEmptyStem(text) {
  const t = String(text ?? "")
    .replace(/[_\s.:=?\-−–—,/|()π=3.14]+/gi, "")
    .replace(/radius|diameter|circle|area|perimeter|circumference|of|the|a|what|is/gi, "")
    .trim();
  return t.length < 1;
}

/** Rebuild common procedural stems from params (IDs unchanged). */
export function rebuildGeometryStemAr001(question) {
  const p = question?.params || {};
  const kind = String(p.kind || "").replace(/^story_/, "");
  const radius = Number(p.radius);
  const hasRadius = Number.isFinite(radius) && radius > 0;

  if (kind === "circle_area" && hasRadius) {
    return `دائرة نصف قطرها ${radius}. ما هي المنطقة؟ (ط = 3.14)`;
  }
  if (kind === "circle_perimeter" && hasRadius) {
    return `دائرة نصف قطرها ${radius}. ما هو المحيط؟ (ط = 3.14)`;
  }
  if (kind === "concept_circle" && p.patternFamily === "radius_diameter") {
    return "في الدائرة العلاقة بين القطر ونصف القطر هي:";
  }

  const side = Number(p.side ?? p.sideLength);
  const length = Number(p.length ?? p.a);
  const width = Number(p.width ?? p.b);
  if ((kind === "square_area" || kind.includes("square_area")) && Number.isFinite(side) && side > 0) {
    return `ما هي مساحة المربع الذي ضلعه ${side}؟`;
  }
  if ((kind === "square_perimeter" || kind.includes("square_perimeter")) && Number.isFinite(side) && side > 0) {
    return `ما محيط المربع الذي ضلعه ${side}؟`;
  }
  if (
    (kind === "rectangle_area" || kind.includes("rect_area")) &&
    Number.isFinite(length) &&
    Number.isFinite(width) &&
    length > 0 &&
    width > 0
  ) {
    return `ما هي مساحة المستطيل الذي طوله ${length} وعرضه ${width}؟`;
  }
  if (
    (kind === "rectangle_perimeter" || kind.includes("rect_perimeter") || kind === "story_rectangle_perimeter") &&
    Number.isFinite(length) &&
    Number.isFinite(width) &&
    length > 0 &&
    width > 0
  ) {
    if (String(p.kind || "").startsWith("story_")) {
      return `نريد سياجًا حول حقل مستطيل طوله ${length} وعرضه ${width}. ما محيط الحقل؟`;
    }
    return `ما محيط المستطيل الذي طوله ${length} وعرضه ${width}؟`;
  }

  if ((kind === "story_square_area" || kind === "square_area") && Number.isFinite(side) && side > 0) {
    if (String(p.kind || "").startsWith("story_")) {
      return `لدينا مربع ضلعه ${side}. ما مساحته؟`;
    }
  }
  if ((kind === "story_rectangle_area" || kind === "rectangle_area") && Number.isFinite(length) && Number.isFinite(width) && length > 0 && width > 0) {
    if (String(p.kind || "").startsWith("story_")) {
      return `حقل مستطيل طوله ${length} وعرضه ${width}. ما مساحته؟`;
    }
  }
  if (kind === "shapes_basic_square" || kind === "shapes_basic_rectangle") {
    const shape = String(p.shape || (kind.includes("square") ? "Square" : "Rectangle"));
    const arShape = shape.toLowerCase().includes("square") ? "مربع" : "مستطيل";
    return `ما الشكل الذي يُوصف بأنه ${arShape}؟`;
  }
  if (kind.startsWith("shapes_basic_properties")) {
    const shape = String(p.shape || "");
    const arShape =
      /square/i.test(shape) ? "المربع" : /rectangle/i.test(shape) ? "المستطيل" : "الشكل";
    return `أي خاصية تصف ${arShape} بشكل صحيح؟`;
  }
  if (kind === "triangles" || kind === "triangle_classify") {
    const t = String(p.type || "").toLowerCase();
    if (t.includes("equilateral")) {
      return "مثلث أضلاعه الثلاثة متساوية — ماذا يُسمى؟";
    }
    if (t.includes("isosceles")) {
      return "مثلث له ضلعان متساويان فقط — ماذا يُسمى؟";
    }
    if (t.includes("scalene")) {
      return "مثلث أضلاعه الثلاثة مختلفة — ماذا يُسمى؟";
    }
    return "صنّف المثلث حسب أطوال أضلاعه:";
  }
  if (kind === "quadrilaterals" || kind === "quad_classify") {
    const t = String(p.type || p.shape || "").toLowerCase();
    if (t.includes("square")) return "شكل له أربعة أضلاع متساوية وأربع زوايا قائمة — ماذا يُسمى؟";
    if (t.includes("rectangle")) return "شكل له أربع زوايا قائمة وأضلاع متقابلة متساوية — ماذا يُسمى؟";
    if (t.includes("parallelogram")) return "شكل رباعي أضلاعه المتقابلة متوازية — ماذا يُسمى؟";
    if (t.includes("trapezoid") || t.includes("trapezium")) {
      return "شكل رباعي له زوج واحد فقط من الأضلاع المتوازية — ماذا يُسمى؟";
    }
    if (t.includes("rhombus")) return "شكل رباعي كل أضلاعه متساوية — ماذا يُسمى؟";
    return "صنّف الشكل الرباعي:";
  }
  if (kind === "triangle_perimeter" || kind === "perimeter_triangle") {
    const a = Number(p.side1 ?? p.a);
    const b = Number(p.side2 ?? p.b);
    const c = Number(p.side3 ?? p.c);
    if ([a, b, c].every((n) => Number.isFinite(n) && n > 0)) {
      return `ما محيط المثلث الذي أطوال أضلاعه ${a} و${b} و${c}؟`;
    }
    return "ما محيط المثلث؟";
  }
  if (kind === "parallel_perpendicular" || kind === "lines_parallel_perpendicular") {
    return "هل الخطّان متوازيان أم متعامدان؟";
  }

  return null;
}

function translateGeometryPhrase(text) {
  let out = String(text ?? "").trim();
  if (!out) return out;
  if (!containsHebrew(out)) return out;
  if (SHAPE_WORDS[out]) return SHAPE_WORDS[out];

  const mapped = mapGeometryLabel(out);
  if (mapped) return mapped;

  for (const [from, to] of PHRASES) {
    if (out.includes(from)) out = out.split(from).join(to);
  }

  out = out
    .replace(/(?!)/gu, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  return out;
}

function isShortAnswerField(field) {
  return field === "answers" || field === "options" || field === "الإجابات المقبولة";
}

export function localizeGeometryQuestionAr001(question) {
  if (!question) return question;

  // Conceptual bank may already be Arabic when rendered under ar-001; keep and polish tokens.
  const conceptualized = localizeGeometryConceptualQuestionAr001(question);

  const base = { ...conceptualized };
  if (typeof base.question === "string" && containsHebrew(base.question)) base.question = "";
  if (typeof base.exerciseText === "string" && containsHebrew(base.exerciseText)) base.exerciseText = "";
  if (typeof base.questionLabel === "string" && containsHebrew(base.questionLabel)) base.questionLabel = "";

  const rebuilt = rebuildGeometryStemAr001({ ...conceptualized, ...base, params: conceptualized.params });
  let resolvedStem = rebuilt && !containsHebrew(rebuilt) ? rebuilt : null;
  if (!resolvedStem) {
    const existing = String(conceptualized?.question || conceptualized?.exerciseText || "").trim();
    if (existing && !containsHebrew(existing) && /[\u0600-\u06FF]/.test(existing)) {
      resolvedStem = existing;
    } else if (existing && !containsHebrew(existing)) {
      const mappedStem = localizeGeometryConceptualTextAr001(existing);
      if (mappedStem && mappedStem !== existing && /[\u0600-\u06FF]/.test(mappedStem)) {
        resolvedStem = mappedStem;
      }
    }
  }
  if (!resolvedStem) resolvedStem = "أجب عن السؤال.";

  const out = mapQuestionTextFields({ ...base }, (field, value) => {
    if (field === "question" || field === "sportText" || field === "questionLabel" || field === "exerciseText") {
      if (!value || containsHebrew(value) || isNearlyEmptyStem(value) || !/[\u0600-\u06FF]/.test(String(value))) {
        return resolvedStem;
      }
      return value;
    }
    if (isShortAnswerField(field)) {
      const raw = String(value ?? "").trim();
      const label = mapGeometryLabel(value) || SHAPE_WORDS[raw];
      if (label && label !== raw && /[\u0600-\u06FF]/.test(String(label))) return label;
      const conceptual = localizeGeometryConceptualTextAr001(value);
      if (conceptual && conceptual !== raw) return conceptual;
      if (label) return label;
      if (!containsHebrew(raw)) return raw;
      return raw.replace(/(?!)/gu, "").trim() || raw;
    }
    if (!containsHebrew(String(value ?? ""))) {
      return localizeGeometryConceptualTextAr001(value);
    }
    return translateGeometryPhrase(value);
  });

  out.question = resolvedStem;
  if (!out.exerciseText || containsHebrew(String(out.exerciseText)) || isNearlyEmptyStem(out.exerciseText)) {
    out.exerciseText = resolvedStem;
  }
  out.displayStemSource = rebuilt ? "params" : "passthrough";

  if (typeof out.correctAnswer === "string") {
    const mapped =
      mapGeometryLabel(out.correctAnswer) ||
      SHAPE_WORDS[out.correctAnswer.trim()] ||
      localizeGeometryConceptualTextAr001(out.correctAnswer);
    if (mapped) out.correctAnswer = mapped;
  }

  return out;
}
