/**
 * Modern Standard Arabic (ar-001) rebuilders for math question stems.
 * English is the authority; params/numbers/operators unchanged.
 * Generated by scripts/i18n/bootstrap-ar-001-stem-rebuilders.mjs — review instructional copy.
 */
import { BLANK } from "../math-constants.js";
import { containsHebrew, mapQuestionTextFields } from "../learning-question-content-locale.js";

const WEEKDAYS_PT = [
  "domingo",
  "segunda-feira",
  "terça-feira",
  "quarta-feira",
  "quinta-feira",
  "sexta-feira",
  "sábado"];

/** Residual HE→EN maps cleared — generators emit English. Keep empty for API stability. */
const OBJECTS_PT = {};
const YES_NO = {};
const PRIME_COMPOSITE = {};
const PARITY = {};
const MATH_PHRASES = [];

function applyMathPhrases(text) {
  let out = String(text ?? "");
  for (const [he, en] of MATH_PHRASES) {
    if (out.includes(he)) out = out.split(he).join(en);
  }
  return out;
}

function inferMathLevelKey(question) {
  const lv = String(question?.params?.difficulty || question?.levelKey || "easy");
  if (lv === "hard" || lv === "medium") return lv;
  return "easy";
}

function inferSelectedOp(question) {
  return String(question?.operation || question?.params?.kind || "").replace(/^wp_/, "word_problems");
}

/** Rebuild word-problem / story stems from params when kind is known. */
export function rebuildMathStemAr001(question) {
  const p = question?.params || {};
  const kind = String(p.kind || "");
  const gradeKey = String(question?.gradeKey || p.gradeKey || "g3");

  if (kind === "mul_groups_g1") {
    const objects = OBJECTS_PT[p.objects] || String(p.objects || "items");
    return `هناك ${p.groups} مجموعات. كل مجموعة لديها ${p.perGroup} ${objects}. كم ${objects} يوجد في الكل؟`;
  }
  if (kind === "mul_skip_count_g1") {
    const seq = Array.isArray(p.seq) ? p.seq : [];
    const head = seq.slice(0, -1).join(", ");
    return `العد حسب ${p.perGroup}s: ${head}، ${BLANK}`;
  }
  if (kind === "ns_number_line" || kind === "ns_number_line_g1") {
    const nums = Array.isArray(p.numbers) ? p.numbers : [];
    const line = nums.map((n) => (n === BLANK || n === "__" ? BLANK : n)).join(" - ");
    return `املأ الرقم المفقود على خط الأعداد: ${line}`;
  }
  if (kind === "ns_even_odd" || kind === "ns_parity") {
    return `هل ${p.n ?? p.num} عدد زوجي؟`;
  }
  if (kind === "frac_half" || kind === "frac_half_reverse") {
    if (kind === "frac_half_reverse" && p.whole != null) {
      return `نصف ${BLANK} هو ${p.whole / 2}. ما هو العدد الكامل؟`;
    }
    return `ما هو نصف ${p.whole ?? p.n}؟`;
  }
  if (kind === "frac_quarter" || kind === "frac_quarter_reverse") {
    if (kind === "frac_quarter_reverse" && p.whole != null) {
      return `ربع ${BLANK} هو ${p.whole / 4}. ما هو العدد الكامل؟`;
    }
    return `ما هو ربع ${p.whole ?? p.n}؟`;
  }
  if (
    kind === "frac_compare_like_den_g4" |
    kind === "frac_compare_like_den_g3" |
    kind === "frac_compare_same_den"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      return `أي الكسر أكبر — ${p.n1}/${p.den} أم ${p.n2}/${p.den}؟ اكتب الكسر الأكبر: ${BLANK}`;
    }
  }
  if (
    kind === "frac_same_den_add_g4" |
    kind === "frac_same_den_add" |
    kind === "frac_same_den_sub_g4" |
    kind === "frac_same_den_sub"
  ) {
    if (p.n1 != null && p.n2 != null && p.den != null) {
      const op = p.op === "add" || kind.includes("add") ? "+" : "−";
      return `${p.n1}/${p.den} ${op} ${p.n2}/${p.den} = ${BLANK}`;
    }
  }
  if (kind === "frac_simplify_intro_g4" || kind === "frac_simplify_intro_g3") {
    if (p.num != null && p.den != null) {
      return `بسط الكسر ${p.num}/${p.den}: ${BLANK}`;
    }
  }
  if (kind === "frac_equivalent_expand" || kind === "frac_equivalent") {
    if (p.num != null && p.den != null && p.factor != null) {
      return `أوجد كسرًا مكافئًا لـ ${p.num}/${p.den} (اضرب بـ ${p.factor}): ${BLANK}`;
    }
  }
  if (kind === "wp_simple_add" || kind === "wp_simple_add_g2") {
    if (kind === "wp_simple_add_g2") {
      return `كان هناك ${p.a} أطفال في الفصل وانضم ${p.b} أكثر. كم عدد الأطفال هناك الآن؟`;
    }
    return `لدى الأسد ${p.a} كرات ويحصل على ${p.b} أكثر. كم عدد الكرات التي يمتلكها ليو إجمالاً؟`;
  }
  if (kind === "wp_simple_sub" || kind === "wp_simple_sub_g2") {
    if (kind === "wp_simple_sub_g2") {
      return `يوجد ${p.total} تفاح في السلة. ${p.give} تم تناولها. كم عدد التفاح المتبقي؟`;
    }
    return `لدى ليو ${p.total} ملصقات. يعطي ${p.give} لصديق. كم عدد الملصقات التي تركها ليو؟`;
  }
  if (kind === "wp_pocket_money" || kind === "wp_pocket_money_g2") {
    return `إيما لديها ${p.money} دولار. تشتري وجبة خفيفة مقابل ${p.toy} دولار. كم بقي من المال؟`;
  }
  if (kind === "wp_groups_g2") {
    return `يحتوي كل صف على ${p.per} كراسي. هناك ${p.groups} صفوف من هذا القبيل. كم عدد الكراسي في المجموع؟`;
  }
  if (kind === "wp_groups_g3") {
    return `يحتوي كل صندوق على ${p.per} أقلام رصاص. هناك ${p.groups} صناديق. كم عدد أقلام الرصاص هناك في كل شيء؟`;
  }
  if (kind === "wp_groups_g4") {
    return `يحتوي كل رف على ${p.per} كتب. يوجد ${p.groups} أرفف. كم عدد الكتب الموجودة في المجموع؟`;
  }
  if (kind === "wp_groups_late_g6") {
    return `تحتوي كل حاوية على ${p.per} أجزاء. ⟦تم تسليم حاوية واحدة⟧. كم عدد الأجزاء في الكل؟`;
  }
  if (kind === "wp_groups" || kind === "wp_groups_late") {
    return `يحتوي كل صندوق إمداد على ${p.per} حزم. ${p.groups} تم تسليم الصناديق. كم عدد الحزم في الكل؟`;
  }
  if (kind === "wp_comparison_more") {
    return `نوا لديه ${p.big} بطاقات ويوفال لديه ${p.small} بطاقات. كم عدد البطاقات التي تمتلكها نوا أكثر من يوفال؟`;
  }
  if (kind === "wp_part_whole_g4") {
    return `قاعة بها ${p.whole} مقاعد. ${p.partA} يتم أخذها للعرض والباقي فارغ. كم عدد المقاعد الفارغة؟`;
  }
  if (kind === "wp_part_whole") {
    return `يحتوي الفصل على ${p.whole} طلاب. ${p.partA} في نادي كرة القدم والباقي في نادي الشطرنج. كم عدد الطلاب في نادي الشطرنج؟`;
  }
  if (kind === "wp_change_stack_g4") {
    return `كان المستودع يحتوي على ${p.start} صناديق. ${p.gain} تم إضافة صناديق جديدة و ${p.loss} تم إرسالها إلى فرع آخر. كم عدد الصناديق المتبقية؟`;
  }
  if (kind === "wp_change_stack") {
    return `مكتبة بها ${p.start} كتب. ${p.gain} تمت إضافة كتب جديدة وتم سحب ${p.loss}. كم عدد الكتب الموجودة في المكتبة الآن؟`;
  }
  if (kind === "wp_time_days") {
    const start = WEEKDAYS_PT[p.startDayIdx] || "segunda-feira";
    const end = WEEKDAYS_PT[p.endDayIdx] || "sexta-feira";
    return `إذا كان اليوم ${start}، فكم يومًا حتى ${end}؟`;
  }
  if (kind === "wp_time_date") {
    return `إذا كان اليوم هو ${p.today}الشهر، فما التاريخ الذي سيكون بعد ${p.daysLater} يوم؟`;
  }
  if (kind === "wp_coins") {
    return `لدى الأسد ${p.coins1} عملات معدنية بقيمة دولار واحد و${p.coins2} عملات معدنية بقيمة دولارين. كم من المال لديه في كل شيء؟`;
  }
  if (kind === "wp_coins_spent") {
    return `لدى ليو ${p.total} دولار من العملات المعدنية. يشتري الحلوى بمبلغ ${p.spent} دولار. كم بقي من المال؟`;
  }
  if (kind === "wp_division_simple") {
    return `يوجد ${p.total} تفاح مقسم إلى مجموعات تحتوي كل منها على ${p.perGroup} تفاحة. كم عدد المجموعات هناك؟`;
  }
  if (kind === "wp_leftover") {
    return `${p.total} يتم تقسيم الطلاب إلى مجموعات مكونة من ${p.groupSize}. كم عدد الطلاب الذين تركوا بدون مجموعة كاملة؟`;
  }
  if (kind === "wp_shop_discount") {
    return `سعر القميص ${p.price} دولار مع خصم ${p.discPerc}%. كم تدفع بعد الخصم؟`;
  }
  if (kind === "wp_unit_cm_to_m") {
    return `كم متر يساوي ${p.cm} سنتيمتر؟ = ${BLANK}`;
  }
  if (kind === "wp_unit_g_to_kg") {
    return `كم كيلو جرام ${p.g} جرام؟ = ${BLANK}`;
  }
  if (kind === "wp_distance_time") {
    return `يمشي طفل بسرعة ثابتة ${p.speed} كم/ساعة لمدة ${p.hours} ساعة. كم كيلومترا سوف يسافرون؟`;
  }
  if (kind === "wp_time_sum") {
    return `مقطع فيديو واحد يستمر ${p.l1} دقيقة وآخر يستمر ${p.l2} دقيقة. كم دقيقة يستمر كلا المقطعين معًا؟`;
  }
  if (kind === "wp_average" || kind === "wp_average_g6") {
    if (kind === "wp_average_g6") {
      return `حصل مشروع جماعي على الدرجات ${p.s1} و${p.s2} و${p.s3} على ثلاث مراحل. ما هو متوسط ​​النتيجة (مقربة إلى رقم صحيح)؟`;
    }
    return `سجل ليو ${p.s1} و${p.s2} و${p.s3} في ثلاثة اختبارات. ما هو متوسطه (مقربًا إلى عدد صحيح)؟`;
  }
  if (kind === "wp_multi_step" || kind === "wp_multi_step_g6") {
    return `الأسد لديه ${p.money} دولار. يشتري ${p.a} قلم رصاص و${p.b} قلم رصاص، وسعر كل قطعة ${p.price} دولار. كم من المال بقي بعد التسوق؟`;
  }
  if (kind === "operation_choice_word_problem_probe") {
    return `هناك ${p.groups} مجموعات بها ${p.each} عنصر في كل مجموعة. ما هي العملية التي تجد الإجمالي؟`;
  }

  if (kind.startsWith("wp_") || inferSelectedOp(question) === "word_problems") {
    return null;
  }

  return applyMathLevelPresentationAr001(
    String(question?.question || question?.exerciseText || ""),
    {
      selectedOp: question?.operation || inferSelectedOp(question),
      params: p,
      mathLevelKey: inferMathLevelKey(question),
      gradeKey,
    }
  );
}

/** English mirror of applyMathLevelPresentation (math-question-generator.js). */
export function applyMathLevelPresentationAr001(question, ctx) {
  const q0 = String(question || "");
  if (!q0.trim()) return q0;
  const { selectedOp, params, mathLevelKey, gradeKey } = ctx;
  const kind = String(params?.kind || "");
  if (kind.startsWith("wp_") || selectedOp === "word_problems") return q0;

  if (kind === "ns_comlement100") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 100;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `اصنع ${c}: ماذا تضيف إلى ${b} لتصل إلى ${c}؟ = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `نظرا ${b} + ${BLANK} = ${c}. ما هو الرقم المفقود؟`;
      }
      return `مشكلة كلامية: ${b} ينقصه جزء للوصول إلى ${c} — كم يجب إضافته؟ = ${BLANK}`;
    }
  }

  if (kind === "ns_comlement10") {
    const b = params?.b;
    const c = params?.c != null ? Number(params.c) : 10;
    if (b != null && Number.isFinite(c)) {
      if (mathLevelKey === "easy") {
        return `حتى ${c}: ماذا تضيف إلى ${b} لتنتهي عند ${c}؟ = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `مفقود في المعادلة: ${b} + ${BLANK} = ${c}`;
      }
      return `بدون عمود: ما الإضافة إلى ${c} التي تبدأ بـ ${b}؟ = ${BLANK}`;
    }
  }

  if (kind === "scale_find") {
    const ml = params?.mapLength;
    const rl = params?.realLength;
    if (ml != null && rl != null) {
      if (mathLevelKey === "easy") {
        return `على الخريطة، يبلغ طول الجزء ${ml} سم، وفي الواقع يبلغ ${rl} سم. أكمل المقياس كـ 1:${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `طول الخريطة ${ml} سم، الطول الحقيقي ${rl} سم. ما هو المقياس؟ اكتب الرقم بعد 1: = ${BLANK}`;
      }
      return `الخريطة ${ml} سم والحقيقية ${rl} سم — مقياس الرسم 1:__. ما هو الرقم المفقود؟ = ${BLANK}`;
    }
  }

  if (kind === "scale_map_to_real") {
    const ml = params?.mapLength;
    const sc = params?.scale;
    if (ml != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `على مقياس 1:${sc}، كم سم حقيقي يساوي ${ml} سم على الخريطة؟ = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `مقياس 1: ${sc}. قياس الخريطة ${ml} سم — ما هو الطول الحقيقي بالسم؟ = ${BLANK}`;
      }
      return `مقياس الرسم 1:${sc}، قياس الخريطة ${ml} سم - أوجد الطول الحقيقي بـ سم = ${BLANK}`;
    }
  }

  if (kind === "scale_real_to_map") {
    const rl = params?.realLength;
    const sc = params?.scale;
    if (rl != null && sc != null) {
      if (mathLevelKey === "easy") {
        return `بمقياس 1:${sc}، الطول الحقيقي ${rl} سم — كم سم على الخريطة؟ = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return `الطول الحقيقي ${rl} سم، مقياس 1:${sc}. ما هو الطول على الخريطة؟ = ${BLANK}`;
      }
      return `تحويل حقيقي إلى خريطة: ${rl} سم حقيقي في 1:${sc} — كم سم في الصفحة؟ = ${BLANK}`;
    }
  }

  if (selectedOp === "compare" || kind === "cmp") {
    const raw = params?.exerciseText ? String(params.exerciseText) : "";
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 4;
    if (mathLevelKey === "easy") {
      const opts = [
        `قارن بين الرقمين واملأ (<, =, >): ${raw}`,
        `علامة المقارنة بين الأرقام: ${raw}`,
        `اختر < أو = أو > — قارن: ${raw}`,
        `قارن القيم واملأ العلامة: ${raw}`];
      return opts[pv].trim();
    }
    if (mathLevelKey === "medium") {
      const opts = [
        `املأ علامة المقارنة الصحيحة: ${raw}`,
        `ما هي العلامة التي تقارن بين الزوجين؟ ${raw}`,
        `طابق علامة المقارنة الصحيحة: ${raw}`,
        `املأ الإشارة بين تعبيرات الأرقام: ${raw}`];
      return opts[pv].trim();
    }
    const opts = [
      `املأ علامة المقارنة – تحقق قبل أن تختار: ${raw}`,
      `قارن بعناية واختر علامة: ${raw}`,
      `قارن بعناية واختر علامة: ${raw}`,
      `فحص سريع: ما هي العلامة المناسبة؟ ${raw}`];
    return opts[pv].trim();
  }

  if (selectedOp === "divisibility" || kind === "divisibility") {
    const num = params?.num;
    const div = params?.divisor;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (num != null && div != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `قابلية القسمة: هل ${num} تقسم بالتساوي على ${div}؟`
          : `تحقق: هل ${num} مضاعف لـ ${div} (بدون باقي)؟`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `قواعد القسمة - هل ${num} تقسم على ${div}؟`
          : `القسمة الكاملة: ${num} ÷ ${div} — هل النتيجة عدد صحيح؟`;
      }
      return pv === 0
        ? `التحقق من قابلية القسمة: هل ${num} تقسم على ${div}؟`
        : `المقسومات: هل ${div} تقسم ${num} بالضبط؟`;
    }
  }

  if (selectedOp === "prime_composite" || kind === "prime_composite") {
    const num = params?.num;
    const subKind = String(params?.subKind || "pc_classify");
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (subKind === "pc_factor_count" && num != null) {
      if (mathLevelKey === "easy") return `الأعداد الأولية: كم عدد المقسومات على ${num}؟`;
      if (mathLevelKey === "medium") {
        return `عد المقسومات: كم عدد المقسومات الطبيعية الموجودة في ${num} (بما في ذلك 1 ونفسها)؟`;
      }
      return `المقسومات: كم عدد المقسومات المختلفة الموجودة في ${num}؟`;
    }
    if (subKind === "pc_smallest_prime" && num != null) {
      if (mathLevelKey === "easy") return `العامل الأولي: ما هو أصغر عامل أولي لـ ${num}؟`;
      if (mathLevelKey === "medium") return `أوجد أصغر عامل أولي لـ ${num}.`;
      return `العوامل: ما هو أصغر عامل أولي لـ ${num}؟`;
    }
    if (subKind === "pc_divisor_pick" && num != null && params?.divisorCandidate != null) {
      const d = params.divisorCandidate;
      if (mathLevelKey === "easy") return `التحقق من المقسوم: هل ${d} يقسم ${num} بالتساوي؟`;
      if (mathLevelKey === "medium") return `المقسومات: هل ${num} تقسم على ${d}؟`;
      return `المقسومات: هل ${d} تقسم ${num} بالضبط؟`;
    }
    if (num != null) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `الأعداد الأولية: هل ${num} أولية أم مركبة؟`
          : `التصنيف الأساسي: ${num} — أولي أم مركب؟`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `صنف العدد: ${num} — أولي أم مركب؟`
          : `هل ${num} له قاسمتان طبيعيتان مختلفتان تمامًا؟`;
      }
      return pv === 0
        ? `هل ${num} أولية أم مركبة؟ فكر قبل أن تختار.`
        : `برهان سريع: هل يمكن تقسيم ${num} إلى عاملين أكبر من 1؟`;
    }
  }

  if (selectedOp === "powers" && (kind === "power_base" || kind === "power_calc")) {
    if (kind === "power_calc") {
      if (mathLevelKey === "easy") return `القوى: ${q0}`;
      if (mathLevelKey === "medium") return `تقييم القوة — ${q0}`;
      return `القوى: ${q0}`;
    }
    if (kind === "power_base") {
      if (mathLevelKey === "easy") return `أوجد القاعدة في القوة: ${q0}`;
      if (mathLevelKey === "medium") return `لغز القوة — ${q0}`;
      return `القاعدة المفقودة في القوة: ${q0}`;
    }
  }

  if (selectedOp === "estimation") {
    if (kind === "est_add") {
      if (mathLevelKey === "easy") return q0.replace(/^Estimate\b/i, "تقدير التقريب: تقدير");
      return q0;
    }
    if (kind === "est_mul" || kind === "est_quantity") return q0;
  }

  if (
    kind === "frac_half" |
    kind === "frac_half_reverse" |
    kind === "frac_quarter" |
    kind === "frac_quarter_reverse"
  ) {
    if (mathLevelKey === "easy") return `الكسور: ${q0}`;
    if (mathLevelKey === "medium") return `الكسر كجزء من الكل: ${q0}`;
    return `الكسور: ${q0}`;
  }

  if (kind === "fm_factor") {
    if (mathLevelKey === "easy") return `العوامل: ${q0}`;
    if (mathLevelKey === "medium") return `تحديد المقسوم عليه: ${q0}`;
    return `المقسومات والعوامل: ${q0}`;
  }
  if (kind === "fm_multiple") {
    if (mathLevelKey === "easy") return `المضاعفات: ${q0}`;
    if (mathLevelKey === "medium") return `التحقق من المضاعفات: ${q0}`;
    return `المضاعفات: ${q0}`;
  }

  if (selectedOp === "percentages" || selectedOp === "ratio" || selectedOp === "scale") return q0;

  if (kind === "fm_gcd" && params?.a != null && params?.b != null) {
    const { a, b } = params;
    if (mathLevelKey === "easy") {
      return `GCF: ما هو العامل المشترك الأكبر لـ ${a} و ${b}؟ = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return `العامل المشترك الأكبر (GCD) لـ ${a} و ${b} — ما هو؟ = ${BLANK}`;
    }
    return `GCF: فكر أولاً — GCD(${a}, ${b}) = ${BLANK}`;
  }

  if (kind === "round" && params?.n != null && params?.toWhat != null) {
    const { n, toWhat } = params;
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    if (toWhat === 10) {
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `التقريب إلى العشرات: إلى ماذا يُقرب ${n}؟ = ${BLANK}`
          : `أقرب عشرة: ${n} → ? = ${BLANK}`;
      }
      if (mathLevelKey === "medium") {
        return pv === 0
          ? `تقريب ${n} إلى أقرب عشرة — النتيجة؟ = ${BLANK}`
          : `قاعدة التقريب بالعشرات: ${n} = ${BLANK}`;
      }
      return pv === 0
        ? `التقريب إلى العشرات: ${n} → ? = ${BLANK}`
        : `العدد الصحيح بعد التقريب ${n} إلى العشرات = ${BLANK}`;
    }
    if (mathLevelKey === "easy") {
      return pv === 0
        ? `التقريب إلى المئات: إلى ماذا يُقرب ${n}؟ = ${BLANK}`
        : `أقرب مائة: ${n} = ${BLANK}`;
    }
    if (mathLevelKey === "medium") {
      return pv === 0
        ? `تقريب ${n} إلى أقرب مائة — النتيجة؟ = ${BLANK}`
        : `تقريب إلى المئات: ${n} → ? = ${BLANK}`;
    }
    return pv === 0
      ? `تقريب إلى المئات: ${n} → ? = ${BLANK}`
      : `العدد بعد التقريب ${n} إلى المئات = ${BLANK}`;
  }

  if (kind === "dec_add" || kind === "dec_sub") {
    const pv = Math.abs(Number(params?.presentationVariant) || 0) % 2;
    const a = params?.a;
    const b = params?.b;
    const pl = params?.places ?? 1;
    if (a != null && b != null) {
      const af = Number(a).toFixed(pl);
      const bf = Number(b).toFixed(pl);
      if (kind === "dec_add") {
        if (mathLevelKey === "easy") {
          return pv === 0
            ? `أضف الكسور العشرية: ${af} + ${bf} = ${BLANK}`
            : `المجموع المباشر: ${af} + ${bf} = ${BLANK}`;
        }
        return `أضف الكسور العشرية: ${af} + ${bf} = ${BLANK}`;
      }
      if (mathLevelKey === "easy") {
        return pv === 0
          ? `طرح الأعداد العشرية: ${af} − ${bf} = ${BLANK}`
          : `الفرق المباشر: ${af} − ${bf} = ${BLANK}`;
      }
      return `طرح الأعداد العشرية: ${af} − ${bf} = ${BLANK}`;
    }
  }

  if (selectedOp === "sequences") {
    if (mathLevelKey === "easy") {
      return q0.replace(/^Continue the sequence\b/i, "استمر في نمط الأرقام");
    }
    return q0;
  }

  const looksNumericExercise =
    /=\s*__|=\s*\?\?|___|\?\?=/.test(q0) |
    (/^\d/.test(q0.trim()) && /[+\-×÷]/.test(q0));

  if (looksNumericExercise) return q0;
  if (/^Exercise\b/i.test(q0)) return q0;

  if (containsHebrew(q0) && params?.exerciseText && !containsHebrew(String(params.exerciseText))) {
    return String(params.exerciseText);
  }

  return q0;
}

function isShortAnswerField(field) {
  return field === "answers" || field === "options" || field === "الإجابات المقبولة";
}

function localizeMathField(_field, value, question) {
  const text = String(value ?? "");
  if (!containsHebrew(text)) return text;

  if (YES_NO[text.trim()]) return YES_NO[text.trim()];
  if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
  if (PARITY[text.trim()]) return PARITY[text.trim()];

  const rebuilt = rebuildMathStemAr001(question);
  if (rebuilt && !containsHebrew(rebuilt) && (_field === "question" || _field === "sportText" || _field === "questionLabel")) {
    return rebuilt;
  }

  const presented = applyMathLevelPresentationAr001(text, {
    selectedOp: question?.operation || inferSelectedOp(question),
    params: question?.params || {},
    mathLevelKey: inferMathLevelKey(question),
    gradeKey: question?.gradeKey || "g3",
  });
  if (presented && !containsHebrew(presented)) return presented;

  const phrased = applyMathPhrases(text);
  if (!containsHebrew(phrased)) return phrased;

  const stripped = phrased
    .replace(/(\d+)\s+remainder\s+(\d+)/gu, "1 دولار المتبقي 2 دولار")
    .replace(/(?!)/gu, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  return stripped || text;
}

function isNearlyEmptyStem(text) {
  const t = String(text ?? "")
    .replace(/[_\s.:=?\-−–—,/|]+/g, "")
    .trim();
  return t.length < 2;
}

const OP_SYMBOL_PT = Object.freeze({
  addition: "+",
  subtraction: "−",
  multiplication: "×",
  division: "÷",
});

/**
 * Build display stem from params/kind only (no Hebrew sentence translation).
 * @param {Record<string, unknown>} question
 */
function resolveMathDisplayStem(question) {
  const rebuilt = rebuildMathStemAr001(question);
  if (rebuilt && String(rebuilt).trim() && !containsHebrew(rebuilt)) {
    return { stem: rebuilt, source: "params" };
  }
  const p = question?.params && typeof question.params === "object" ? question.params : {};
  const opRaw = String(question?.operation || p.kind || "").replace(/^wp_/, "");
  const a = p.a ?? question?.a;
  const b = p.b ?? question?.b;
  if (a != null && b != null && OP_SYMBOL_PT[opRaw]) {
    return { stem: `Quantoé ${a} ${OP_SYMBOL_PT[opRaw]} ${b}?`, source: "generic" };
  }
  for (const candidate of [p.exerciseText, question?.exerciseText, question?.question]) {
    if (typeof candidate === "string" && candidate.trim() && !containsHebrew(candidate)) {
      return { stem: String(candidate).trim(), source: "passthrough" };
    }
  }
  return { stem: null, source: "none" };
}

/**
 * Localize math question for Modern Standard Arabic (ar-001) display.
 * Display stems come from params/kind templates — not from translating Hebrew prose.
 * Option tokens use closed dictionaries (logical labels), not sentence MT.
 */
export function localizeMathQuestionAr001(question) {
  if (!question) return question;

  const base = { ...question };
  // Drop authored Hebrew stems so params are the sole stem authority.
  if (typeof base.question === "string" && containsHebrew(base.question)) base.question = "";
  if (typeof base.exerciseText === "string" && containsHebrew(base.exerciseText)) base.exerciseText = "";
  if (typeof base.questionLabel === "string" && containsHebrew(base.questionLabel)) base.questionLabel = "";

  const { stem, source } = resolveMathDisplayStem({ ...question, ...base, params: question.params });
  const resolvedStem = stem || "Solve.";

  const out = mapQuestionTextFields({ ...base }, (field, value, q) => {
    if (field === "question" || field === "sportText" || field === "questionLabel") {
      if (!value || containsHebrew(value) || isNearlyEmptyStem(value)) return resolvedStem;
      return value;
    }
    // Answers/options: closed token maps only (no full-sentence HE→EN).
    if (isShortAnswerField(field)) {
      const text = String(value ?? "");
      if (!containsHebrew(text)) return text;
      if (YES_NO[text.trim()]) return YES_NO[text.trim()];
      if (PRIME_COMPOSITE[text.trim()]) return PRIME_COMPOSITE[text.trim()];
      if (PARITY[text.trim()]) return PARITY[text.trim()];
      if (OBJECTS_PT[text.trim()]) return OBJECTS_PT[text.trim()];
      const digitsOnly = text.replace(/(?!)/gu, "").trim();
      return digitsOnly || text;
    }
    if (!containsHebrew(String(value ?? ""))) return value;
    return value;
  });

  out.question = resolvedStem;
  if (!out.exerciseText || containsHebrew(String(out.exerciseText)) || isNearlyEmptyStem(out.exerciseText)) {
    out.exerciseText = resolvedStem;
  }
  out.displayStemSource = source;

  if (typeof out.correctAnswer === "string") {
    const ca = out.correctAnswer.trim();
    if (YES_NO[ca]) out.correctAnswer = YES_NO[ca];
    else if (PRIME_COMPOSITE[ca]) out.correctAnswer = PRIME_COMPOSITE[ca];
    else if (PARITY[ca]) out.correctAnswer = PARITY[ca];
    else if (containsHebrew(ca)) {
      out.correctAnswer = ca.replace(/(?!)/gu, "").trim() || ca;
    }
  }
  if (Array.isArray(out.answers)) {
    out.answers = out.answers.map((a) =>
      typeof a === "string" ? localizeMathField("answers", a, out) : a
    );
  }
  return out;
}
